using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Intersect.Server.Localization;

internal static partial class ServerLocalizationOverrides
{
    private static partial void AddFrOverrides(IDictionary<string, JObject> overrides)
    {
        overrides["fr"] = new JObject
        {
            ["Account"] = new JObject
            {
                ["AccountAlreadyExists"] = "Le compte existe déjà !",
                ["AccountDoesNotExist"] = "Le compte n'existe pas.",
                ["AdminOnly"] = "Le serveur autorise actuellement uniquement les administrateurs à se connecter. Revenez plus tard !",
                ["AlreadyBanned"] = "{00} a déjà été banni !",
                ["AlreadyMuted"] = "{00} a déjà été réduit au silence !",
                ["BadAccess"] = "Accès refusé ! Niveau de pouvoir invalide !",
                ["BadLogin"] = "Nom d'utilisateur ou mot de passe incorrect.",
                ["BanStatus"] = "Votre compte a été banni depuis : {00} (UTC) par {01}. Le bannissement expire : {02} (UTC). Motif du bannissement : {03}",
                ["Banned"] = "{00} a été banni !",
                ["CharacterExists"] = "Un compte avec ce nom de personnage existe déjà. Veuillez en choisir un autre.",
                ["CharacterDeleted"] = "Le personnage a été supprimé.",
                ["DeleteCharacterError"] = "Ce personnage ne peut pas être supprimé, il est peut-être coincé en ligne en combat.",
                ["EmailExists"] = "Un compte avec cette adresse e-mail existe déjà.",
                ["EmailFail"] = "Impossible d'envoyer l'e-mail de réinitialisation du mot de passe pour le moment. Veuillez réessayer plus tard.",
                ["InvalidClass"] = "Classe invalide sélectionnée. Veuillez réessayer.",
                ["InvalidEmail"] = "L'e-mail choisi ne respecte pas les exigences définies par le serveur.",
                ["InvalidName"] = "Le nom choisi ne respecte pas les exigences définies par le serveur.",
                ["LoadFail"] = "Échec du chargement du compte. Veuillez vous reconnecter.",
                ["PlayerSavingTryAgainLater"] = "'{00}' est en cours de sauvegarde, veuillez réessayer plus tard.",
                ["MaxCharacters"] = "Vous avez déjà créé le nombre maximal de personnages. Supprimez-en un avant d'en créer un autre.",
                ["Muted"] = "{00} a été réduit au silence !",
                ["MuteStatus"] = "Votre compte a été réduit au silence depuis : {00} par {01}. Le silence expire : {02}. Motif du silence : {03}",
                ["NotAllowed"] = "Vous n'avez pas la permission de faire cela.",
                ["NotFound"] = "Erreur : le compte {00} est introuvable !",
                ["RegistrationsBlocked"] = "Les inscriptions de comptes sont actuellement bloquées par le serveur.",
                ["UnbanFail"] = "Échec du débannissement de {00}. L'utilisateur n'est pas banni !",
                ["UnbanSuccess"] = "{00} a été débanni !",
                ["UnknownErrorWhileSaving"] = "Une erreur inconnue s'est produite lors de l'enregistrement de l'utilisateur.",
                ["UnknownServerErrorRetryLogin"] = "Une erreur serveur inconnue s'est produite, veuillez vous reconnecter.",
                ["UnmuteFail"] = "Échec de la levée du silence pour {00}. L'utilisateur n'est pas réduit au silence !",
                ["UnmuteSuccess"] = "{00} n'est plus réduit au silence !",
            },
            ["Alignment"] = new JObject
            {
                ["ChangedTo"] = "Vous appartenez désormais à {00}.",
                ["AlreadyInFaction"] = "Vous appartenez déjà à cette faction.",
                ["GuildMismatch"] = "Votre guilde appartient à une autre faction.",
                ["WingsOn"] = "Vous ne pouvez pas changer de faction tant que vos ailes sont activées.",
                ["WingsNeutral"] = "Vous ne pouvez pas activer vos ailes tant que vous êtes dans la faction neutre.",
                ["SwapCooldown"] = "Vous pourrez changer à nouveau le {date}.",
            },
            ["Bag"] = new JObject
            {
                ["BagInBag"] = "Vous ne pouvez pas ranger un sac dans un autre sac !",
                ["BagInSelf"] = "Vous ne pouvez pas ranger un sac dans lui-même !",
                ["DropNotEmpty"] = "Vous ne pouvez pas jeter un sac s'il n'est pas vide !",
                ["OnlySellEmpty"] = "Impossible de vendre le sac s'il n'est pas vide !",
                ["OnlyTradeEmpty"] = "Impossible d'échanger le sac s'il n'est pas vide !",
                ["SlotOccupied"] = "Cet emplacement est occupé par un autre objet !",
                ["WithdrawInvalid"] = "Objet invalide sélectionné pour récupérer !",
            },
            ["Bank"] = new JObject
            {
                ["DepositInvalid"] = "Objet invalide sélectionné pour déposer !",
                ["DepositSuccessNonStackable"] = "Vous avez stocké : {00}",
                ["DepositSuccessStackable"] = "Vous avez stocké : {00} {01}",
                ["InvalidSlotToSwap"] = "Emplacements invalides pour échanger !",
                ["NotEnoughInInventory"] = "Il n'y a pas {00} de {01} dans votre inventaire à déposer.",
                ["NotEnoughBankSpaceForItem"] = "Il n'y a pas assez de place dans la banque pour stocker {00} {01} !",
                ["NotEnoughBankSpaceForOneOfItem"] = "Il n'y a pas assez de place dans la banque pour stocker un {00} !",
                ["WithdrawInvalid"] = "Objet invalide sélectionné pour retirer !",
                ["WithdrawSuccessNonStackable"] = "Vous avez retiré : {00}",
                ["WithdrawSuccessStackable"] = "Vous avez retiré : {00} {01}",
            },
            ["Chat"] = new JObject
            {
                ["Admin"] = "[ADMIN] {00}: {01}",
                ["AdminCommand"] = "/admin",
                ["AllCommand"] = "/all",
                ["Announcement"] = "[ANNOUNCEMENT] {00}: {01}",
                ["AnnouncementCommand"] = "/announcement",
                ["Global"] = "[GLOBAL] {00}: {01}",
                ["GlobalCommand"] = "/global",
                ["Local"] = "{00}: {01}",
                ["LocalCommand"] = "/local",
                ["MessageCommand"] = "/message",
                ["Party"] = "[PARTY] {00}: {01}",
                ["PartyCommand"] = "/party",
                ["PrivateFrom"] = "[PM] De {00}: {01}",
                ["PrivateTo"] = "[PM] À {00}: {01}",
                ["PrivateMessageCommand"] = "/pm",
                ["ReplyCommand"] = "/reply",
                ["ReplyShortcutCommand"] = "/r",
                ["TooFast"] = "Vous discutez trop vite !",
                ["Trade"] = "[MARKET] {00}: {01}",
                ["TradeCommand"] = "/trade",
                ["TradeNotAllowed"] = "Vous ne pouvez pas encore échanger !",
            },
            ["Class"] = new JObject
            {
                ["LastClass"] = "Dernière classe",
                ["LastClassError"] = "Impossible de supprimer la classe. Vous devez avoir au moins une classe en permanence !",
            },
            ["Color"] = new JObject
            {
            },
            ["Combat"] = new JObject
            {
                ["AddSymbol"] = "+",
                ["Blocked"] = "BLOQUÉ !",
                ["Channeling"] = "Vous canalisez actuellement une autre compétence.",
                ["ChannelingNoAttack"] = "Vous canalisez actuellement un sort, vous ne pouvez pas attaquer.",
                ["Cooldown"] = "Cette compétence est en récupération.",
                ["Critical"] = "COUP CRITIQUE !",
                ["Dash"] = "DASH !",
                ["DynamicRequirement"] = "Vous ne remplissez pas les conditions pour lancer le sort !",
                ["ImmuneToEffect"] = "IMMUNISÉ !",
                ["LevelDown"] = "NIVEAU BAISSÉ !",
                ["LevelUp"] = "NIVEAU AUGMENTÉ !",
                ["Vampirism"] = "VAMPIRISME !",
                ["LowHealth"] = "Pas assez de santé.",
                ["LowMana"] = "Pas assez de mana.",
                ["Miss"] = "RATÉ !",
                ["RemoveSymbol"] = "-",
                ["ResourceRequirements"] = "Vous ne remplissez pas les conditions pour récolter cette ressource !",
                ["Silenced"] = "Vous ne pouvez pas lancer cette capacité tant que vous êtes réduit au silence.",
                ["Sleep"] = "Vous ne pouvez pas lancer cette capacité tant que vous dormez.",
                ["Snared"] = "Vous ne pouvez pas lancer cette capacité tant que vous êtes entravé.",
                ["SleepAttacking"] = "Vous dormez et ne pouvez pas attaquer.",
                ["SleepBlocking"] = "Vous dormez et ne pouvez pas bloquer.",
                ["StunAttacking"] = "Vous êtes étourdi et ne pouvez pas attaquer.",
                ["StunBlocking"] = "Vous êtes étourdi et ne pouvez pas bloquer.",
                ["Stunned"] = "Vous ne pouvez pas lancer cette capacité tant que vous êtes étourdi.",
                ["TargetOutOfRange"] = "La cible est hors de portée !",
                ["ToolRequired"] = "Vous avez besoin d'un {00} pour interagir avec cette ressource !",
                ["TryForgetBoundSpell"] = "Vous ne pouvez pas oublier ce sort.",
                ["InvalidTarget"] = "Cible invalide pour ce sort.",
            },
            ["CommandOutput"] = new JObject
            {
                ["AccountCount"] = " - {00} comptes.",
                ["ActiveConnections"] = "Connexions actives : {00}",
                ["ApiAccessGranted"] = "{00} a désormais l'accès API !",
                ["ApiAccessRevoked"] = "L'accès API de {00} a été révoqué !",
                ["ApiRoleGranted"] = "{00} a désormais le rôle API {01} !",
                ["ApiRoleNotFound"] = "Rôle API {00} introuvable !",
                ["ApiRoleNotGranted"] = "Impossible d'attribuer le rôle API {00}, l'accès API doit d'abord être activé pour {01} !",
                ["ApiRolePrerequisite"] = "Impossible d'accorder le rôle API {00} ! Dépend du rôle {01}.",
                ["ApiRoleRevoked"] = "Le rôle API {01} de {00} a été révoqué !",
                ["ApiRoles"] = "Rôles API pour {00} :",
                ["ApiRolesNotGranted"] = "Aucun rôle API n'a été accordé.",
                ["CharacterCount"] = " - {00} personnages.",
                ["CpsLocked"] = "CPS verrouillé",
                ["CpsUnlocked"] = "CPS déverrouillé",
                ["EventCount"] = " - {00} événements.",
                ["ExperimentalFeatureEnablement"] = "{00} est {01}.",
                ["GameTime"] = "Le temps de jeu est maintenant : {00}",
                ["HelpFooter"] = "Saisissez une commande suivie de {00} pour obtenir les paramètres et les informations d'utilisation.",
                ["HelpHeader"] = "Liste des commandes disponibles :",
                ["ItemCount"] = " - {00} objets.",
                ["SetCount"] = " - {00} ensembles.",
                ["KillSuccess"] = "{00} a été tué !",
                ["ListAccount"] = "Compte",
                ["ListCharacter"] = "Personnage",
                ["ListId"] = "ID",
                ["MapCount"] = " - {00} cartes.",
                ["MetricsDisabled"] = "Collecte de métriques désactivée",
                ["MetricsEnabled"] = "Collecte de métriques activée",
                ["NoClientsConnected"] = "Aucun client connecté",
                ["NpcCount"] = " - {00} NPCs.",
                ["PowerChanged"] = "Le pouvoir de {00} a été mis à jour !",
                ["ServerInfo"] = "Le serveur a :",
                ["SpellCount"] = " - {00} sorts.",
                ["StrayConnections"] = "Connexions perdues : {00}",
                ["VariableChanged"] = "'{01}' défini sur {02} (était {03}) ({00})",
                ["VariableListEmpty"] = "Il n'y a aucune variable à afficher.",
                ["VariableNotFound"] = "Variable '{00}' introuvable",
                ["VariablePrint"] = "{00} {01} = {02}",
            },
            ["Crafting"] = new JObject
            {
                ["AlreadyCrafting"] = "Vous fabriquez déjà un objet !",
                ["CraftFailure"] = "La tentative de fabrication de l'objet {00} a échoué !",
                ["CraftFailureLostItems"] = "La tentative de fabrication de l'objet {00} a échoué et vous avez perdu les matériaux !",
                ["Crafted"] = "Vous avez fabriqué {00} avec succès !",
                ["InJournalMode"] = "Vous ne pouvez pas fabriquer d'objets depuis votre journal d'artisanat !",
                ["NoSpace"] = "Vous n'avez pas assez de place dans l'inventaire pour fabriquer {00} !",
                ["RequirementsNotMet"] = "Vous ne remplissez pas les conditions pour fabriquer cet objet !",
                ["JobExperience"] = "Vous avez reçu {00} points d'expérience en {01}.",
                ["UnknownJobType"] = "Le type de métier {00} n'est pas reconnu.",
            },
            ["Database"] = new JObject
            {
                ["Default"] = "Par défaut",
                ["MigratingAutomatically"] = "L'option --migrate-automatically a été passée au serveur au démarrage, l'utilisateur ne sera donc pas invité.",
                ["NoClasses"] = "Aucune classe trouvée ! Création d'une classe par défaut.",
                ["NoMaps"] = "Aucune carte trouvée ! Création d'une carte vide.",
                ["UpgradeBackup"] = "Veuillez sauvegarder vos bases de données de jeu et de joueurs, puis tapez '{00}' pour continuer ou '{01}' pour quitter.",
                ["UpgradeExit"] = "EXIT",
                ["UpgradeReady"] = "READY",
                ["UpgradeRequired"] = "Vos bases de données doivent être mises à niveau ! Ce processus pourrait corrompre vos données de jeu si des erreurs sont rencontrées.",
            },
            ["Errors"] = new JObject
            {
                ["ErrorFloodBurst"] = "[Flood] : {00} paquets en rafale [Utilisateur : {01} | Joueur : {02} | IP {03}]",
                ["ErrorFloodSize"] = "[Flood] : Taille du paquet : {00} [Utilisateur : {01} | Joueur : {02} | IP {03}]",
                ["ErrorLoadingConfiguration"] = "Échec du chargement des options du serveur ! Appuyez sur une touche pour arrêter.",
                ["ErrorLoadingStrings"] = "Échec du chargement des chaînes ! Appuyez sur une touche pour arrêter.",
                ["ErrorLogged"] = "Une erreur a été enregistrée dans errors.log.",
                ["ErrorServerCrash"] = "Le serveur Intersect a rencontré une erreur et doit se fermer. Les informations d'erreur se trouvent dans resources/logs/errors.log. Appuyez sur Entrée pour quitter.",
                ["ErrorServerCrashNoHalt"] = "Le serveur Intersect a rencontré une erreur et doit se fermer. Les informations d'erreur se trouvent dans resources/logs/errors.log.",
                ["ErrorTimeout"] = "Trop de requêtes échouées. Veuillez patienter et réessayer !",
                ["UnknownErrorTryAgain"] = "Une erreur inconnue s'est produite, veuillez réessayer.",
            },
            ["Events"] = new JObject
            {
                ["CommandParameter"] = "\\param",
                ["EventNameCommand"] = "\\en",
                ["EventParameter"] = "\\evtparam",
                ["EventParameters"] = "\\evtparams",
                ["GlobalSwitch"] = "\\gs",
                ["GlobalVariable"] = "\\gv",
                ["GuildVariable"] = "\\guildvar",
                ["MilitaryHour"] = "\\24hour",
                ["OnlineCountCommand"] = "\\onlinecount",
                ["OnlineListCommand"] = "\\onlinelist",
                ["PeriodEvening"] = "PM",
                ["PeriodMorning"] = "AM",
                ["PlayerGuildCommand"] = "\\pg",
                ["PlayerNameCommand"] = "\\pn",
                ["PlayerSwitch"] = "\\ps",
                ["PlayerVariable"] = "\\pv",
                ["TimeHour"] = "\\hour",
                ["TimeMinute"] = "\\minute",
                ["TimePeriod"] = "\\period",
                ["TimeSecond"] = "\\second",
                ["UserVariable"] = "\\uservar",
                ["WatchdogKill"] = "Événement arrêté car les commandes traitées en une seule frame ont dépassé le seuil de surveillance des événements. (Carte : {00} Événement : {01})",
                ["WatchdogKillCommon"] = "Événement commun arrêté car les commandes traitées en une seule frame dépassent le seuil de surveillance des événements. (Événement {00})",
            },
            ["Formulas"] = new JObject
            {
                ["Missing"] = "Le fichier Formulas.json est manquant. Un fichier de formules par défaut a été généré.",
            },
            ["Friends"] = new JObject
            {
                ["Accept"] = "{00} a accepté votre demande d'ami !",
                ["AlreadyFriends"] = "Vous êtes déjà ami avec {00}.",
                ["Busy"] = "{00} est actuellement occupé. Veuillez réessayer plus tard.",
                ["FriendLoggedIn"] = "{00} s'est connecté.",
                ["FriendNotification"] = "Vous êtes maintenant ami avec {00} !",
                ["FriendRemoved"] = "L'ami a été supprimé.",
                ["FriendRequestSent"] = "La demande d'ami a été envoyée.",
            },
            ["General"] = new JObject
            {
                ["DisabledLowerCase"] = "désactivé",
                ["EnabledLowerCase"] = "activé",
                ["Notice"] = "Avis",
                ["NoticeError"] = "Avis d'erreur",
                ["UnknownErrorPleaseTryAgain"] = "Une erreur inconnue s'est produite, veuillez réessayer.",
            },
            ["Guilds"] = new JObject
            {
                ["AlreadyInGuild"] = "Vous êtes déjà dans une guilde !",
                ["Demoted"] = "{00} a été rétrogradé au rang {01} !",
                ["DisbandGuild"] = "{00} a été dissoute !",
                ["ErrorWhileAcceptingInvite"] = "Une erreur s'est produite lors de l'enregistrement de votre appartenance à la guilde, veuillez réessayer.",
                ["GuildChat"] = "[{00}] {01}: {02}",
                ["GuildCommand"] = "/guild",
                ["GuildLeaderLeave"] = "Un maître de guilde ne peut pas quitter sa propre guilde. Veuillez d'abord transférer les droits de propriété !",
                ["GuildNameInUse"] = "Le nom de guilde choisi est déjà utilisé !",
                ["InviteAlreadyInGuild"] = "Le joueur que vous essayez d'inviter est déjà dans une guilde ou a une invitation en attente.",
                ["InviteDifferentFaction"] = "Vous ne pouvez pas inviter des joueurs d'une faction différente.",
                ["InviteDeclined"] = "Vous avez refusé la demande de rejoindre {00}.",
                ["InviteDeclinedMissingGuild"] = "Vous avez refusé la demande de rejoindre la guilde.",
                ["InviteDeclinedResponse"] = "{00} a refusé votre demande pour rejoindre {01}.",
                ["InviteDeclinedResponseMissingGuild"] = "{00} a refusé votre demande pour rejoindre la guilde.",
                ["InviteNotOnline"] = "Le joueur que vous essayez d'inviter n'est pas en ligne ou n'existe pas.",
                ["InviteSent"] = "Vous avez invité {00} à rejoindre {01} !",
                ["NoLongerAllowedInInstance"] = "Vous n'êtes plus dans la guilde dont vous étiez dans l'instance. Vous avez été renvoyé dans le monde ouvert.",
                ["NoSuchPlayer"] = "Il n'y a pas un tel joueur dans cette guilde.",
                ["NotAllowed"] = "Vous n'avez pas la permission de faire cela.",
                ["NotAllowedDeposit"] = "Vous n'avez pas la permission de déposer des objets dans la banque de guilde de {00} !",
                ["NotAllowedInInstance"] = "Vous devez être dans une guilde pour vous téléporter vers une instance de guilde.",
                ["NotAllowedSwap"] = "Vous n'avez pas la permission d'échanger des objets dans la banque de guilde de {00} !",
                ["NotAllowedWithdraw"] = "Vous n'avez pas la permission de retirer de la banque de guilde de {00} !",
                ["NotInGuild"] = "Vous n'êtes pas dans une guilde.",
                ["NotReceivedInvite"] = "Vous n'avez encore reçu aucune invitation de guilde.",
                ["DifferentFaction"] = "Votre faction ne correspond pas à celle de la guilde.",
                ["FactionApplied"] = "Votre faction a été changée pour correspondre à celle de la guilde.",
                ["Promoted"] = "{00} a été promu au rang {01} !",
                ["RankLimit"] = "Impossible de rejoindre {00} car sa guilde est pleine !",
                ["RankLimitResponse"] = "Cette guilde a déjà atteint la limite de membres pour le rang {00}. Promouvez ou rétrogradez d'autres membres pour faire de la place à {01}.",
                ["Transferred"] = "La propriété de la guilde {00} a été transférée de {01} à {02} !",
                ["VariableInvalid"] = "Nom de guilde invalide !",
                ["VariableNotString"] = "Le nom de guilde fourni ne contient aucun texte.",
                ["Welcome"] = "Bienvenue dans {00} !",
                ["DeleteGuildLeader"] = "Vous ne pouvez pas supprimer un personnage qui est un {00} de guilde. Dissolvez la guilde ou transférez la propriété avant de réessayer.",
                ["GuildCreated"] = "La guilde a été créée avec succès !",
                ["GuildCreationFailed"] = "Échec de la création de la guilde. Veuillez réessayer.",
            },
            ["Intro"] = new JObject
            {
                ["ConsoleActive"] = "Tapez \"exit\" pour arrêter le serveur ou \"help\" pour la liste des commandes.",
                ["Loading"] = "Chargement, veuillez patienter.",
                ["ServerStarted"] = "Serveur démarré. Utilisation du port UDP n°{00}.",
                ["Support"] = "Pour l'aide, le support et les mises à jour, visitez : https://www.ascensiongamedev.com",
                ["Tagline"] = "Moteur ORPG 2D gratuit",
                ["Version"] = "Version {00}",
            },
            ["Items"] = new JObject
            {
                ["Bound"] = "Vous ne pouvez pas jeter cet objet.",
                ["CannotUse"] = "Vous ne pouvez pas utiliser cet objet !",
                ["Cooldown"] = "Vous devez attendre avant d'utiliser cet objet à nouveau !",
                ["DynamicRequirement"] = "Vous ne remplissez pas les conditions pour utiliser cet objet !",
                ["Equipped"] = "Vous ne pouvez pas jeter des objets équipés.",
                ["NoBag"] = "Vous ne pouvez pas ranger cet objet dans un sac.",
                ["NoBank"] = "Vous ne pouvez pas stocker cet objet dans une banque.",
                ["NoSpaceForItem"] = "Il n'y a plus de place pour cet objet !",
                ["NotEnough"] = "Pas assez de {00}s !",
                ["NotImplemented"] = "L'utilisation de ce type d'objet n'est pas encore implémentée.",
                ["Sleep"] = "Vous ne pouvez pas utiliser cet objet pendant que vous dormez.",
                ["Stunned"] = "Vous ne pouvez pas utiliser cet objet pendant que vous êtes étourdi.",
            },
            ["Sets"] = new JObject
            {
                ["DeleteSet"] = "Supprimer l'ensemble",
                ["DeleteSetInUse"] = "Impossible de supprimer l'ensemble tant que des objets s'y réfèrent.",
            },
            ["Mapping"] = new JObject
            {
                ["LastMap"] = "Dernière carte",
                ["LastMapError"] = "Impossible de supprimer la carte. Vous devez avoir au moins une carte en permanence !",
                ["LinkFailure"] = "Échec du lien de carte",
                ["LinkFailureError"] = "Impossible de lier la carte {00} à la carte {01}. Si cette fusion se produisait, les cartes {02} et {03} occuperaient le même espace dans le monde.",
                ["NewFolder"] = "Nouveau dossier",
            },
            ["Migration"] = new JObject
            {
                ["AlreadyUsingProvider"] = "Erreur de migration : la base de données {00} utilise déjà {01} !",
                ["Cancel"] = "Appuyez sur n'importe quelle autre touche pour annuler la migration.",
                ["ConfirmCharacter"] = "y",
                ["DatabaseFileAlreadyExists"] = "{00} existe déjà. Écraser ? (y/n)",
                ["DefaultDatabase"] = "intersect_{00}_{01}",
                ["DefaultHost"] = "localhost",
                ["DefaultPortMySql"] = "3306",
                ["DefaultUsername"] = "root",
                ["EnterConnectionStringParameters"] = "Veuillez saisir les paramètres de votre chaîne de connexion :",
                ["GameDatabaseName"] = "Jeu",
                ["LoggingDatabaseName"] = "Logging",
                ["MigratingDbSet"] = "Migration des entités dans {00}...",
                ["MigrationCanceled"] = "Migration annulée",
                ["MigrationComplete"] = "Migration terminée ! Appuyez sur Entrée pour quitter.",
                ["MySqlConnecting"] = "Veuillez patienter, tentative de connexion à la base de données...",
                ["MySqlConnectionError"] = "Erreur lors de l'ouverture de la connexion à la base de données ! Erreur : {00}",
                ["MySqlNotEmpty"] = "La base de données doit être vide avant la migration ! Veuillez supprimer toutes les tables avant de continuer. Migration annulée.",
                ["MySqlTryAgain"] = "Voulez-vous réessayer de saisir vos informations de connexion ? (y/n)",
                ["PlayerDatabaseName"] = "Joueur",
                ["PromptDatabase"] = "Base de données ({00}) :",
                ["PromptHost"] = "Hôte ({00}) :",
                ["PromptPassword"] = "Mot de passe (vide) :",
                ["PromptPort"] = "Port ({00}) :",
                ["PromptUsername"] = "Utilisateur ({00}) :",
                ["SelectContext"] = "Quelle base de données souhaitez-vous migrer :",
                ["SelectDatabase"] = "[{00}] {01} (utilise actuellement {02}) {03}",
                ["SelectDatabaseType"] = "[{00}] {01}",
                ["SelectProvider"] = "Sélectionnez le moteur vers lequel migrer la base de données {00} :",
                ["SqliteRecommended"] = "SQLite est fortement recommandé !",
                ["StartingMigration"] = "Démarrage de la migration, veuillez patienter ! Cela peut prendre plusieurs minutes selon la taille de votre jeu.",
                ["StoppingServer"] = "Veuillez patienter, arrêt du serveur et sauvegarde de la base de données actuelle...",
                ["TryAgainCharacter"] = "y",
            },
            ["NetDebug"] = new JObject
            {
                ["Hastebin"] = "Informations de débogage réseau téléversées vers {00} (copiées dans le presse-papiers). Partagez ce lien avec AGD lorsque vous demandez de l'aide pour mettre votre jeu en ligne !",
                ["PleaseWait"] = "Veuillez patienter pendant l'exécution des diagnostics réseau...",
                ["SavedToFile"] = "Informations de débogage réseau enregistrées dans netdebug.txt ! Téléversez ce fichier et partagez-le avec AGD lorsque vous demandez de l'aide pour mettre votre jeu en ligne !",
            },
            ["Networking"] = new JObject
            {
                ["ServerFull"] = "Le serveur est actuellement plein. Veuillez réessayer plus tard.",
            },
            ["Notifications"] = new JObject
            {
                ["Copyright"] = "Copyright (c) 2020-2025 Ascension Game Dev, Tous droits réservés",
                ["Product"] = "Moteur de jeu Intersect",
            },
            ["Parties"] = new JObject
            {
                ["AlreadyDenied"] = "Votre invitation de groupe a déjà été rejetée !",
                ["Busy"] = "{00} est occupé. Veuillez réessayer plus tard !",
                ["CannotCreateInstance"] = "Seul le chef du groupe peut créer une instance partagée.",
                ["Declined"] = "{00} a rejeté votre invitation de groupe !",
                ["Disbanded"] = "Le groupe a été dissous.",
                ["InInstance"] = "Vous ne pouvez pas inviter quelqu'un dans un groupe lorsque vous êtes dans une instance !",
                ["InstanceFailed"] = "Votre groupe a échoué dans l'instance...",
                ["InstanceInProgress"] = "Le groupe n'a pas encore terminé son instance.",
                ["InstanceInUse"] = "Impossible de créer une nouvelle instance : les membres du groupe sont encore dans l'ancienne.",
                ["InstanceLivesRemaining"] = "Il reste {00} vies à votre groupe dans cette instance !",
                ["InParty"] = "{00} est déjà dans un groupe !",
                ["Joined"] = "{00} a rejoint le groupe !",
                ["Kicked"] = "Vous avez été expulsé du groupe !",
                ["LeaderInviteOnly"] = "Seul le chef du groupe peut envoyer des invitations à votre groupe.",
                ["Left"] = "Vous avez quitté le groupe.",
                ["LimitReached"] = "Vous avez atteint la limite maximale de membres du groupe. Expulsez un autre membre avant d'en ajouter.",
                ["MemberKicked"] = "{00} a été expulsé du groupe !",
                ["MemberLeft"] = "{00} a quitté le groupe !",
                ["NoMoreLivesRemaining"] = "Votre groupe n'a plus de vies restantes ! Vous réapparaîtrez hors de l'instance à votre prochaine mort.",
                ["NotInParty"] = "Vous n'êtes pas dans un groupe.",
                ["OutOfRange"] = "La cible est hors de portée ou hors ligne.",
                ["WrongInstance"] = "Votre groupe est actuellement dans une autre instance.",
            },
            ["PasswordResetNotification"] = new JObject
            {
                ["Subject"] = "Intersect Game Engine - Code de réinitialisation du mot de passe",
            },
            ["Player"] = new JObject
            {
                ["Admin"] = "{00} a reçu des pouvoirs administratifs !",
                ["AdminJoined"] = "Vous êtes administrateur ! Appuyez sur Insert à tout moment pour accéder au menu d'administration ou sur F2 pour les informations de débogage.",
                ["AdminSetPower"] = "Seuls les administrateurs peuvent définir le pouvoir !",
                ["BeenWarpedTo"] = "Vous avez été téléporté vers {00}.",
                ["CannotAlterOwnPower"] = "Vous ne pouvez pas modifier votre propre pouvoir !",
                ["CannotWarpToYourself"] = "Vous ne pouvez pas vous téléporter vers vous-même.",
                ["Deadmin"] = "Les pouvoirs administratifs de {00} ont été révoqués !",
                ["HasWarpedTo"] = "{00} a été téléporté vers vous.",
                ["InstanceUpdate"] = "Votre ID d'instance a changé de {00} à {01}.",
                ["Kicked"] = "{00} a été expulsé par {01} !",
                ["Killed"] = "{00} a été tué par {01} !",
                ["Left"] = "{00} a quitté {01}.",
                ["LevelLost"] = "Vous avez perdu un niveau ! Vous êtes maintenant niveau {00} !",
                ["LevelUp"] = "Vous avez gagné un niveau ! Vous êtes maintenant niveau {00} !",
                ["Moderator"] = "{00} a reçu des pouvoirs de modération !",
                ["ModeratorJoined"] = "Vous êtes modérateur ! Appuyez sur Insert à tout moment pour accéder au menu d'administration ou sur F2 pour les informations de débogage.",
                ["Offline"] = "Utilisateur non en ligne !",
                ["OverworldReturnAdmin"] = "Vous avez renvoyé {00} dans le monde ouvert.",
                ["OverworldReturned"] = "Vous avez été renvoyé dans le monde ouvert.",
                ["PlayerNotFound"] = "Le joueur '{00}' est introuvable !",
                ["InvalidItem"] = "Objet invalide sélectionné.",
                ["InvalidQuantity"] = "La quantité doit être supérieure à zéro.",
                ["ItemGiveFailed"] = "Impossible de donner {00}x {01} à {02}.",
                ["ItemGiveSuccess"] = "Vous avez donné {00}x {01} à {02}.",
                ["ItemReceivedFromAdmin"] = "{00} vous a donné {01}x {02}.",
                ["ItemSpawnFailed"] = "Impossible de créer {00}x {01} pour {02}.",
                ["ItemSpawnSuccess"] = "Vous avez créé {00}x {01} pour {02}.",
                ["ItemSpawnedNearYou"] = "{00} a créé {01}x {02} près de vous.",
                ["PowerChanged"] = "Votre pouvoir a été modifié !",
                ["ServerKicked"] = "{00} a été expulsé par le serveur !",
                ["ServerKilled"] = "{00} a été tué par le serveur !",
                ["LearnedSpell"] = "Vous avez appris le sort {00} !",
                ["ForgotSpell"] = "Vous avez oublié le sort {00} !",
                ["StatPoints"] = "Vous avez {00} points de statistiques disponibles à dépenser !",
                ["WarpedTo"] = "Téléporté vers {00}.",
                ["WarpedToYou"] = "{00} s'est téléporté vers vous.",
            },
            ["Portchecking"] = new JObject
            {
                ["AntivirusCheck"] = "2. Les programmes antivirus peuvent également bloquer les connexions. Vous devrez peut-être ajouter Intersect Server.exe à vos exclusions antivirus.",
                ["CheckFirewalls"] = "1. Les pare-feu peuvent bloquer les connexions à votre serveur. Vérifiez les pare-feu de votre système (par ex., iptables, FirewallD, Windows Firewall).",
                ["CheckRouterUpnp"] = "Il semble que l'UPnP ait échoué. Vous devrez peut-être activer l'UPnP sur votre routeur ou transférer les ports manuellement pour autoriser les connexions à votre serveur.",
                ["ConnectionInfo"] = "Informations de connexion :",
                ["DebuggingSteps"] = "Étapes de débogage (pour autoriser l'accès public) :",
                ["DocumentationUrl"] = "https://docs.freemmorpgmaker.com/en-US/deploy/forwarding/",
                ["PortCheckerAndUpnpDisabled"] = "Le service de vérification de ports et l'UPnP ont été désactivés. Veuillez vérifier l'état du serveur manuellement avec un client.",
                ["PortNotOpenTryingUpnp"] = "Le port {0} n'est pas ouvert, tentative via UPnP...",
                ["PortNotOpenUpnpDisabled"] = "Le port {0} n'est pas ouvert, mais UPnP est désactivé. Vérifiez la redirection de ports de votre routeur et la configuration du pare-feu de l'ordinateur.",
                ["ProbablyFirewall"] = "UPnP a apparemment réussi, mais le serveur n'est pas accessible sur le port {0}. Vérifiez le pare-feu de la machine sur laquelle ce serveur s'exécute.",
                ["PublicIp"] = "IP publique : {00}",
                ["PublicPort"] = "Port public : {00}",
                ["RouterUpnpFailed"] = "UPnP a échoué. Veuillez vérifier l'état du serveur manuellement à l'aide d'un client.",
                ["TryingUpnp"] = "Tentative d'ouverture du port via UPnP...",
                ["UpnpSucceededPortCheckerDisabled"] = "UPnP a réussi, mais le vérificateur de ports est désactivé. Veuillez vérifier l'état du serveur manuellement à l'aide d'un client.",
                ["WithinRestrictedNetwork"] = "3. Si vous êtes sur un campus universitaire ou dans un réseau d'entreprise, vous n'avez probablement pas l'autorisation d'ouvrir des ports ou d'héberger des jeux. Dans ce cas, explorez des options d'hébergement externe !",
            },
            ["Quests"] = new JObject
            {
                ["Abandoned"] = "Quête abandonnée : {00} !",
                ["Completed"] = "Quête : {00} terminée !",
                ["Declined"] = "Quête refusée : {00} !",
                ["ItemTask"] = "{00} mise à jour ! {01}/{02} {03} récupérés !",
                ["NpcTask"] = "{00} mise à jour ! {01}/{02} {03} tués !",
                ["Started"] = "Quête commencée : {00} !",
                ["TaskCompleted"] = "Tâche terminée !",
                ["Updated"] = "Quête : {00} mise à jour !",
            },
            ["Regex"] = new JObject
            {
                ["Email"] = "^(([\\w-]+\\.)+[\\w-]+|([a-zA-Z]{1}|[\\w-]{2,}))@((([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])){1}|([a-zA-Z]+[\\w-]+\\.)+[a-zA-Z]{2,4})$",
                ["GuildName"] = "^[a-zA-Z0-9 ]{3,20}$",
                ["Username"] = "^[a-zA-Z0-9]{2,20}$",
            },
            ["Shops"] = new JObject
            {
                ["Bound"] = "Cet objet est lié à vous et ne peut pas être vendu !",
                ["CannotAfford"] = "La transaction a échoué en raison de fonds insuffisants.",
                ["DoesNotAccept"] = "Cette boutique n'accepte pas cet objet !",
                ["FailedToRemoveItem"] = "Échec du retrait des objets de l'emplacement {00} pour le joueur {01}. Quantité à retirer : {02} à {03}",
                ["InventoryFull"] = "Vous n'avez pas assez de place pour acheter cet objet !",
                ["SuccessfullyRemovedItem"] = "Suppression réussie de {00} objets de l'emplacement {01} pour le joueur {02} à {03}",
                ["TransactionFailed"] = "La transaction a échoué !",
            },
            ["Trading"] = new JObject
            {
                ["Accepted"] = "L'échange a réussi !",
                ["AlreadyDenied"] = "Votre demande d'échange a déjà été refusée !",
                ["Bound"] = "Cet objet est lié à vous et ne peut pas être échangé !",
                ["Busy"] = "{00} est occupé. Veuillez réessayer plus tard !",
                ["Declined"] = "L'échange a été refusé !",
                ["InvalidOffer"] = "Objet invalide sélectionné pour offrir !",
                ["InvalidRevoke"] = "Objet invalide sélectionné pour révoquer !",
                ["ItemsDropped"] = "Plus d'espace dans l'inventaire. Certains de vos objets ont été déposés au sol !",
                ["OfferAccepted"] = "{00} a accepté votre offre. Veuillez confirmer l'échange.",
                ["OutOfRange"] = "La cible de l'échange est hors de portée ou hors ligne.",
                ["RevokeNotAllowed"] = "Vous ne pouvez pas révoquer cet objet, {00} a déjà accepté l'échange !",
            },
            ["Upnp"] = new JObject
            {
                ["FailedForwardingTcp"] = "Échec de la redirection automatique du port TCP {00} via UPnP. UPnP est peut-être désactivé dans les paramètres de votre routeur, ou ce port est peut-être déjà redirigé.",
                ["FailedForwardingUdp"] = "Échec de la redirection automatique du port UDP {00} via UPnP. UPnP est peut-être désactivé dans les paramètres de votre routeur, ou ce port est peut-être déjà redirigé.",
                ["ForwardedTcp"] = "Redirection automatique du port TCP {00} via UPnP réussie.",
                ["ForwardedUdp"] = "Redirection automatique du port UDP {00} via UPnP réussie.",
                ["InitializationFailed"] = "Échec de l'initialisation du service UPnP. Vous n'avez peut-être pas de routeur, ou l'UPnP de votre routeur est désactivé.",
                ["Initialized"] = "Initialisation du service UPnP réussie.",
            },
            ["Mail"] = new JObject
            {
                ["inventoryfull"] = "Pas assez de place dans votre inventaire",
                ["receiveitem"] = "Vous avez reçu un objet !",
                ["playernotfound"] = "Joueur introuvable !",
                ["newmail"] = "Vous avez reçu un nouveau courrier !",
                ["mailnotfound"] = "Courrier introuvable !",
                ["invaliditem"] = "L'objet sélectionné est invalide ou ne peut pas être joint au courrier.",
                ["broadcastsent"] = "Courrier de diffusion envoyé.",
                ["broadcastfailed"] = "Échec de l'envoi du courrier de diffusion.",
                ["broadcastmissingtitle"] = "L'objet du courrier est obligatoire.",
                ["broadcastmissingmessage"] = "Le message du courrier est obligatoire.",
                ["broadcastmissingitem"] = "Au moins un objet joint au courrier est requis.",
                ["broadcastinvalidquantity"] = "Les quantités des pièces jointes du courrier doivent être supérieures à zéro.",
                ["broadcasttoomanyattachments"] = "La diffusion de courrier peut inclure au maximum {00} objets joints.",
                ["broadcastnorecipients"] = "Il n'y avait aucun destinataire pour le courrier de diffusion.",
            },
            ["Market"] = new JObject
            {
                ["invalidlisting"] = "Annonce invalide.",
                ["listingcreated"] = "Votre objet a été listé sur le marché.",
                ["listingunavailable"] = "Cette annonce n'est plus disponible.",
                ["notenoughmoney"] = "Vous n'avez pas assez d'argent.",
                ["inventoryfull"] = "Votre inventaire est plein.",
                ["itempurchased"] = "Vous avez acheté l'objet.",
                ["salecompleted"] = "Vente sur le marché terminée",
                ["yoursolditem"] = "Vous avez vendu un objet via le marché !",
                ["expiredlisting"] = "Annonce expirée",
                ["yourlistingexpired"] = "Une de vos annonces de marché a expiré. L'objet vous a été retourné.",
                ["transactionfailed"] = "La transaction de marché a échoué.",
                ["cannotlist"] = "Vous ne pouvez pas lister cet objet.",
                ["cannotremoveitem"] = "Impossible de retirer l'objet de votre inventaire.",
            },
        };
    }
}
