using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Intersect.Server.Localization;

internal static partial class ServerLocalizationOverrides
{
    private static partial void AddPtOverrides(IDictionary<string, JObject> overrides)
    {
        overrides["pt"] = new JObject
        {
            ["Account"] = new JObject
            {
                ["AccountAlreadyExists"] = "A conta já existe!",
                ["AccountDoesNotExist"] = "A conta não existe.",
                ["AdminOnly"] = "No momento, o servidor está permitindo apenas a conexão de administradores. Por favor, volte mais tarde!",
                ["AlreadyBanned"] = "{00} já foi banido!",
                ["AlreadyMuted"] = "{00} já foi silenciado!",
                ["BadAccess"] = "Acesso negado! Nível de poder inválido!",
                ["BadLogin"] = "Nome de usuário ou senha incorretos.",
                ["BanStatus"] = "Sua conta foi banida desde: {00} (UTC) por {01}. O banimento expira: {02} (UTC). Motivo do banimento: {03}",
                ["Banned"] = "{00} foi banido!",
                ["CharacterExists"] = "Já existe uma conta com este nome de personagem. Por favor escolha outro.",
                ["CharacterDeleted"] = "O personagem foi excluído.",
                ["DeleteCharacterError"] = "Este personagem não pode ser excluído, ele pode estar preso online em combate.",
                ["EmailExists"] = "Já existe uma conta com este endereço de e-mail.",
                ["EmailFail"] = "Falha ao enviar seu e-mail de redefinição de senha neste momento. Por favor, tente novamente mais tarde.",
                ["InvalidClass"] = "Classe inválida selecionada. Por favor, tente novamente.",
                ["InvalidEmail"] = "O e-mail escolhido não atende aos requisitos definidos pelo servidor.",
                ["InvalidName"] = "O nome escolhido não atende aos requisitos definidos pelo servidor.",
                ["LoadFail"] = "Falha ao carregar a conta. Por favor, tente fazer login novamente.",
                ["PlayerSavingTryAgainLater"] = "'{00}' está sendo salvo no momento, tente novamente mais tarde.",
                ["MaxCharacters"] = "Você já criou o número máximo de personagens. Exclua um antes de criar outro.",
                ["Muted"] = "{00} foi silenciado!",
                ["MuteStatus"] = "Sua conta foi silenciada desde: {00} por {01}. O silêncio expira: {02}. Motivo do silêncio: {03}",
                ["NotAllowed"] = "Você não tem permissão para fazer isso.",
                ["NotFound"] = "Erro: A conta {00} não foi encontrada!",
                ["RegistrationsBlocked"] = "Os registros de contas estão atualmente bloqueados pelo servidor.",
                ["UnbanFail"] = "Falha ao desbanir {00}. O usuário não está banido!",
                ["UnbanSuccess"] = "{00} foi desbanido!",
                ["UnknownErrorWhileSaving"] = "Ocorreu um erro desconhecido ao salvar o usuário.",
                ["UnknownServerErrorRetryLogin"] = "Ocorreu um erro de servidor desconhecido. Tente fazer login novamente.",
                ["UnmuteFail"] = "Falha ao dessilenciar {00}. O usuário não está silenciado!",
                ["UnmuteSuccess"] = "{00} foi dessilenciado!",
            },
            ["Alignment"] = new JObject
            {
                ["ChangedTo"] = "Agora você pertence a {00}.",
                ["AlreadyInFaction"] = "Você já pertence a esta facção.",
                ["GuildMismatch"] = "Sua guilda pertence a uma facção diferente.",
                ["WingsOn"] = "Você não pode mudar de facção enquanto suas asas estiverem ativadas.",
                ["WingsNeutral"] = "Você não pode ativar suas asas enquanto estiver na facção neutra.",
                ["SwapCooldown"] = "Você pode mudar novamente em {date}.",
            },
            ["Bag"] = new JObject
            {
                ["BagInBag"] = "Você não pode guardar uma bolsa dentro de outra bolsa!",
                ["BagInSelf"] = "Você não pode guardar uma bolsa dentro dela mesma!",
                ["DropNotEmpty"] = "Você não pode deixar cair uma bolsa a menos que esteja vazia!",
                ["OnlySellEmpty"] = "Não é possível vender a bolsa a menos que esteja vazia!",
                ["OnlyTradeEmpty"] = "Não é possível trocar a bolsa a menos que ela esteja vazia!",
                ["SlotOccupied"] = "Esse slot está ocupado por outro item!",
                ["WithdrawInvalid"] = "Item inválido selecionado para retirar!",
            },
            ["Bank"] = new JObject
            {
                ["DepositInvalid"] = "Item inválido selecionado para depósito!",
                ["DepositSuccessNonStackable"] = "Você armazenou: {00}",
                ["DepositSuccessStackable"] = "Você armazenou: {00} {01}",
                ["InvalidSlotToSwap"] = "Slots inválidos para trocar!",
                ["NotEnoughInInventory"] = "Não há {00} de {01} em seu inventário para depositar.",
                ["NotEnoughBankSpaceForItem"] = "Não há espaço suficiente no banco para armazenar {00} de {01}!",
                ["NotEnoughBankSpaceForOneOfItem"] = "Não há espaço suficiente no banco para guardar {00}!",
                ["WithdrawInvalid"] = "Item inválido selecionado para retirada!",
                ["WithdrawSuccessNonStackable"] = "Você retirou: {00}",
                ["WithdrawSuccessStackable"] = "Você retirou: {00} {01}",
            },
            ["Chat"] = new JObject
            {
                ["Admin"] = "[ADMIN] {00}: {01}",
                ["AdminCommand"] = "/admin",
                ["AllCommand"] = "/all",
                ["Announcement"] = "[ANNOUNCEMENT] {00}: {01}",
                ["AnnouncementCommand"] = "/announcement",
                ["Global"] = "[GLOBAL] {00}: {01}",
                ["GlobalCommand"] = "/global",
                ["Local"] = "{00}: {01}",
                ["LocalCommand"] = "/local",
                ["MessageCommand"] = "/message",
                ["Party"] = "[PARTY] {00}: {01}",
                ["PartyCommand"] = "/party",
                ["PrivateFrom"] = "[PM] De {00}: {01}",
                ["PrivateTo"] = "[PM] Para {00}: {01}",
                ["PrivateMessageCommand"] = "/pm",
                ["ReplyCommand"] = "/reply",
                ["ReplyShortcutCommand"] = "/r",
                ["TooFast"] = "Você está conversando muito rápido!",
                ["Trade"] = "[MARKET] {00}: {01}",
                ["TradeCommand"] = "/trade",
                ["TradeNotAllowed"] = "Você não pode negociar ainda!",
            },
            ["Class"] = new JObject
            {
                ["LastClass"] = "Última classe",
                ["LastClassError"] = "Falha ao excluir a classe. Você deve ter pelo menos uma classe o tempo todo!",
            },
            ["Color"] = new JObject
            {
            },
            ["Combat"] = new JObject
            {
                ["AddSymbol"] = "+",
                ["Blocked"] = "BLOQUEADO!",
                ["Channeling"] = "Você está atualmente canalizando outra habilidade.",
                ["ChannelingNoAttack"] = "Você está canalizando um feitiço e não pode atacar.",
                ["Cooldown"] = "Esta habilidade está em tempo de recarga.",
                ["Critical"] = "GOLPE CRÍTICO!",
                ["Dash"] = "DASH!",
                ["DynamicRequirement"] = "Você não atende aos requisitos para lançar o feitiço!",
                ["ImmuneToEffect"] = "IMUNE!",
                ["LevelDown"] = "NÍVEL ABAIXO!",
                ["LevelUp"] = "SUBIU DE NÍVEL!",
                ["Vampirism"] = "VAMPIRISMO!",
                ["LowHealth"] = "Saúde insuficiente.",
                ["LowMana"] = "Mana insuficiente.",
                ["Miss"] = "ERROU!",
                ["RemoveSymbol"] = "-",
                ["ResourceRequirements"] = "Você não atende aos requisitos para colher este recurso!",
                ["Silenced"] = "Você não pode lançar esta habilidade enquanto estiver silenciado.",
                ["Sleep"] = "Você não pode lançar esta habilidade enquanto dorme.",
                ["Snared"] = "Você não pode lançar esta habilidade enquanto estiver preso.",
                ["SleepAttacking"] = "Você está dormindo e não pode atacar.",
                ["SleepBlocking"] = "Você está dormindo e não pode bloquear.",
                ["StunAttacking"] = "Você está atordoado e não pode atacar.",
                ["StunBlocking"] = "Você está atordoado e não pode bloquear.",
                ["Stunned"] = "Você não pode lançar esta habilidade enquanto estiver atordoado.",
                ["TargetOutOfRange"] = "O alvo está fora do alcance!",
                ["ToolRequired"] = "Você precisa de {00} para interagir com este recurso!",
                ["TryForgetBoundSpell"] = "Você não pode esquecer este feitiço.",
                ["InvalidTarget"] = "Alvo inválido para este feitiço.",
            },
            ["CommandOutput"] = new JObject
            {
                ["AccountCount"] = "- {00} Contas.",
                ["ActiveConnections"] = "Conexões ativas: {00}",
                ["ApiAccessGranted"] = "{00} agora tem acesso API!",
                ["ApiAccessRevoked"] = "{00} teve seu acesso à API revogado!",
                ["ApiRoleGranted"] = "{00} agora tem a função API {01}!",
                ["ApiRoleNotFound"] = "Função API {00} não encontrada!",
                ["ApiRoleNotGranted"] = "Falha ao atribuir função API {00}, o acesso API deve ser ativado para {01} primeiro!",
                ["ApiRolePrerequisite"] = "A função API {00} não pôde ser concedida! Depende da função {01}.",
                ["ApiRoleRevoked"] = "{00} teve sua função de API {01} revogada!",
                ["ApiRoles"] = "Funções de API para {00}:",
                ["ApiRolesNotGranted"] = "Nenhuma função de API foi concedida.",
                ["CharacterCount"] = "- {00} Personagens.",
                ["CpsLocked"] = "CPS bloqueado",
                ["CpsUnlocked"] = "CPS desbloqueado",
                ["EventCount"] = "- {00} Eventos.",
                ["ExperimentalFeatureEnablement"] = "{00} é {01}.",
                ["GameTime"] = "A hora do jogo é agora: {00}",
                ["HelpFooter"] = "Digite qualquer comando seguido de {00} para parâmetros e informações de uso.",
                ["HelpHeader"] = "Lista de comandos disponíveis:",
                ["ItemCount"] = "- {00} Itens.",
                ["SetCount"] = "- {00} Conjuntos.",
                ["KillSuccess"] = "{00} foi morto!",
                ["ListAccount"] = "Conta",
                ["ListCharacter"] = "Personagem",
                ["ListId"] = "ID",
                ["MapCount"] = "- {00} Mapas.",
                ["MetricsDisabled"] = "Coleta de métricas desativada",
                ["MetricsEnabled"] = "Coleta de métricas ativada",
                ["NoClientsConnected"] = "Nenhum cliente conectado",
                ["NpcCount"] = "- {00} NPCs.",
                ["PowerChanged"] = "{00} teve seu poder atualizado!",
                ["ServerInfo"] = "O servidor tem:",
                ["SpellCount"] = "- {00} Feitiços.",
                ["StrayConnections"] = "Conexões perdidas: {00}",
                ["VariableChanged"] = "'{01}' definido como {02} (era {03}) ({00})",
                ["VariableListEmpty"] = "Não há variáveis para exibir.",
                ["VariableNotFound"] = "Variável '{00}' não encontrada",
                ["VariablePrint"] = "{00} {01} = {02}",
            },
            ["Crafting"] = new JObject
            {
                ["AlreadyCrafting"] = "Você já está criando um item!",
                ["CraftFailure"] = "A tentativa de fabricar o item {00} falhou!",
                ["CraftFailureLostItems"] = "A tentativa de fabricar o item {00} falhou e você perdeu os materiais!",
                ["Crafted"] = "Você criou {00} com sucesso!",
                ["InJournalMode"] = "Você não pode criar itens do seu diário de artesanato!",
                ["NoSpace"] = "Você não tem espaço de inventário suficiente para criar {00}!",
                ["RequirementsNotMet"] = "Você não atende aos requisitos para fabricar este item!",
                ["JobExperience"] = "Você recebeu {00} pontos de experiência em {01}.",
                ["UnknownJobType"] = "O tipo de trabalho {00} não é reconhecido.",
            },
            ["Database"] = new JObject
            {
                ["Default"] = "Padrão",
                ["MigratingAutomatically"] = "O sinalizador --migrate-automatically foi passado ao servidor na inicialização, portanto o usuário não será avisado.",
                ["NoClasses"] = "Nenhuma classe encontrada! Criando uma classe padrão.",
                ["NoMaps"] = "Nenhum mapa encontrado! Criando um mapa vazio.",
                ["UpgradeBackup"] = "Faça um backup dos bancos de dados de jogos e jogadores e digite '{00}' para continuar ou '{01}' para sair.",
                ["UpgradeExit"] = "SAIR",
                ["UpgradeReady"] = "PRONTO",
                ["UpgradeRequired"] = "Seus bancos de dados precisam ser atualizados! Este processo pode corromper os dados do jogo se algum erro for encontrado.",
            },
            ["Errors"] = new JObject
            {
                ["ErrorFloodBurst"] = "[Flood]: {00} Pacotes em rajada [Usuário: {01} | Jogador: {02} | IP {03}]",
                ["ErrorFloodSize"] = "[Flood]: Tamanho do pacote: {00} [Usuário: {01} | Jogador: {02} | IP {03}]",
                ["ErrorLoadingConfiguration"] = "Falha ao carregar as opções do servidor! Pressione qualquer tecla para desligar.",
                ["ErrorLoadingStrings"] = "Falha ao carregar strings! Pressione qualquer tecla para desligar.",
                ["ErrorLogged"] = "Um erro foi registrado em erros.log.",
                ["ErrorServerCrash"] = "O servidor Intersect encontrou um erro e deve ser fechado. Informações de erro podem ser encontradas em resources/logs/errors.log. Pressione Enter para sair.",
                ["ErrorServerCrashNoHalt"] = "O servidor Intersect encontrou um erro e deve ser fechado. Informações de erro podem ser encontradas em resources/logs/errors.log.",
                ["ErrorTimeout"] = "Muitas solicitações com falha. Aguarde e tente novamente!",
                ["UnknownErrorTryAgain"] = "Ocorreu um erro desconhecido, tente novamente.",
            },
            ["Events"] = new JObject
            {
                ["CommandParameter"] = "\\param",
                ["EventNameCommand"] = "\\en",
                ["EventParameter"] = "\\evtparam",
                ["EventParameters"] = "\\evtparams",
                ["GlobalSwitch"] = "\\gs",
                ["GlobalVariable"] = "\\gv",
                ["GuildVariable"] = "\\guildvar",
                ["MilitaryHour"] = "\\24hour",
                ["OnlineCountCommand"] = "\\onlinecount",
                ["OnlineListCommand"] = "\\onlinelist",
                ["PeriodEvening"] = "PM",
                ["PeriodMorning"] = "AM",
                ["PlayerGuildCommand"] = "\\pg",
                ["PlayerNameCommand"] = "\\pn",
                ["PlayerSwitch"] = "\\ps",
                ["PlayerVariable"] = "\\pv",
                ["TimeHour"] = "\\hour",
                ["TimeMinute"] = "\\minute",
                ["TimePeriod"] = "\\period",
                ["TimeSecond"] = "\\second",
                ["UserVariable"] = "\\uservar",
                ["WatchdogKill"] = "Evento interrompido devido a comandos processados em um único quadro excederem o limite do Event Watchdog. (Mapa: {00} Evento: {01})",
                ["WatchdogKillCommon"] = "Evento comum interrompido devido a comandos processados em um único quadro excederem o limite do Event Watchdog. (Evento {00})",
            },
            ["Formulas"] = new JObject
            {
                ["Missing"] = "O arquivo Formulas.json está ausente. Um arquivo de fórmulas padrão foi gerado.",
            },
            ["Friends"] = new JObject
            {
                ["Accept"] = "{00} aceitou seu pedido de amizade!",
                ["AlreadyFriends"] = "Você já é amigo de {00}.",
                ["Busy"] = "{00} está ocupado no momento. Por favor, tente novamente mais tarde.",
                ["FriendLoggedIn"] = "{00} fez login.",
                ["FriendNotification"] = "Agora você é amigo de {00}!",
                ["FriendRemoved"] = "Amigo foi removido.",
                ["FriendRequestSent"] = "O pedido de amizade foi enviado.",
            },
            ["General"] = new JObject
            {
                ["DisabledLowerCase"] = "desativado",
                ["EnabledLowerCase"] = "habilitado",
                ["Notice"] = "Aviso",
                ["NoticeError"] = "Aviso de erro",
                ["UnknownErrorPleaseTryAgain"] = "Ocorreu um erro desconhecido, tente novamente.",
            },
            ["Guilds"] = new JObject
            {
                ["AlreadyInGuild"] = "Você já está em uma guilda!",
                ["Demoted"] = "{00} foi rebaixado para {01}!",
                ["DisbandGuild"] = "{00} foi dissolvido!",
                ["ErrorWhileAcceptingInvite"] = "Ocorreu um erro ao salvar sua associação à guilda. Tente novamente.",
                ["GuildChat"] = "[{00}] {01}: {02}",
                ["GuildCommand"] = "/guild",
                ["GuildLeaderLeave"] = "Um Mestre da Guilda não pode sair de sua própria guilda. Por favor, transfira os direitos de propriedade primeiro!",
                ["GuildNameInUse"] = "O nome da guilda que você escolheu já está em uso!",
                ["InviteAlreadyInGuild"] = "O jogador que você está tentando convidar já está em uma guilda ou tem um convite pendente.",
                ["InviteDifferentFaction"] = "Você não pode convidar jogadores de uma facção diferente.",
                ["InviteDeclined"] = "Você recusou o pedido de adesão a {00}.",
                ["InviteDeclinedMissingGuild"] = "Você recusou o pedido para ingressar na guilda.",
                ["InviteDeclinedResponse"] = "{00} recusou seu pedido de adesão a {01}.",
                ["InviteDeclinedResponseMissingGuild"] = "{00} recusou seu pedido para ingressar na guilda.",
                ["InviteNotOnline"] = "O jogador que você está tentando convidar não está online ou não existe.",
                ["InviteSent"] = "Você convidou {00} para se juntar a {01}!",
                ["NoLongerAllowedInInstance"] = "Você não está mais na guilda em cuja instância estava conectado. Você foi transportado de volta para o mundo.",
                ["NoSuchPlayer"] = "Não existe tal jogador nesta guilda.",
                ["NotAllowed"] = "Você não tem permissão para fazer isso.",
                ["NotAllowedDeposit"] = "Você não tem permissão para depositar itens no banco da guilda de {00}!",
                ["NotAllowedInInstance"] = "Você deve estar em uma guilda para se teleportar para uma instância de guilda.",
                ["NotAllowedSwap"] = "Você não tem permissão para trocar itens no banco da guilda de {00}!",
                ["NotAllowedWithdraw"] = "Você não tem permissão para fazer saques do banco da guilda de {00}!",
                ["NotInGuild"] = "Você não está em uma guilda.",
                ["NotReceivedInvite"] = "Você ainda não recebeu nenhum convite de guilda.",
                ["DifferentFaction"] = "Sua facção não corresponde à facção da guilda.",
                ["FactionApplied"] = "Sua facção foi alterada para corresponder à da guilda.",
                ["Promoted"] = "{00} foi promovido a {01}!",
                ["RankLimit"] = "Falha ao entrar em {00} porque a guilda deles está cheia!",
                ["RankLimitResponse"] = "Esta guilda já atingiu seu limite de membros para o cargo {00}. Promova ou rebaixe outros membros para abrir espaço para {01}.",
                ["Transferred"] = "A propriedade da guilda de {00} foi transferida de {01} para {02}!",
                ["VariableInvalid"] = "Nome de guilda inválido!",
                ["VariableNotString"] = "O nome da guilda fornecido não contém nenhum texto.",
                ["Welcome"] = "Bem-vindo a {00}!",
                ["DeleteGuildLeader"] = "Você não pode excluir um personagem que seja {00} da guilda. Por favor, dissolva a guilda ou transfira a propriedade antes de tentar novamente.",
                ["GuildCreated"] = "A guilda foi criada com sucesso!",
                ["GuildCreationFailed"] = "Falha ao criar guilda. Por favor, tente novamente.",
            },
            ["Intro"] = new JObject
            {
                ["ConsoleActive"] = "Digite 'exit' para desligar o servidor ou 'help' para obter uma lista de comandos.",
                ["Loading"] = "Carregando, aguarde.",
                ["ServerStarted"] = "Servidor iniciado. Usando porta UDP #{00}.",
                ["Support"] = "Para ajuda, suporte e atualizações, visite: https://www.ascensiongamedev.com",
                ["Tagline"] = "Motor ORPG 2D gratuito",
                ["Version"] = "Versão {00}",
            },
            ["Items"] = new JObject
            {
                ["Bound"] = "Você não pode descartar este item.",
                ["CannotUse"] = "Você não pode usar este item!",
                ["Cooldown"] = "Você deve esperar antes de usar este item novamente!",
                ["DynamicRequirement"] = "Você não atende aos requisitos para usar este item!",
                ["Equipped"] = "Você não pode descartar itens equipados.",
                ["NoBag"] = "Você não pode armazenar este item em uma bolsa.",
                ["NoBank"] = "Você não pode armazenar este item em um banco.",
                ["NoSpaceForItem"] = "Não há mais espaço para esse item!",
                ["NotEnough"] = "Não há {00}s suficientes!",
                ["NotImplemented"] = "O uso deste tipo de item ainda não está implementado.",
                ["Sleep"] = "Você não pode usar este item enquanto dorme.",
                ["Stunned"] = "Você não pode usar este item enquanto estiver atordoado.",
            },
            ["Sets"] = new JObject
            {
                ["DeleteSet"] = "Excluir conjunto",
                ["DeleteSetInUse"] = "Não é possível excluir o conjunto enquanto os itens ainda fazem referência a ele.",
            },
            ["Mapping"] = new JObject
            {
                ["LastMap"] = "Último mapa",
                ["LastMapError"] = "Falha ao excluir o mapa. Você deve ter pelo menos um mapa o tempo todo!",
                ["LinkFailure"] = "Falha no link do mapa",
                ["LinkFailureError"] = "Falha ao vincular o mapa {00} ao mapa {01}. Se essa fusão acontecesse, os mapas {02} e {03} ocupariam o mesmo espaço no mundo.",
                ["NewFolder"] = "Nova pasta",
            },
            ["Migration"] = new JObject
            {
                ["AlreadyUsingProvider"] = "Erro de migração: O banco de dados {00} já está usando {01}!",
                ["Cancel"] = "Pressione qualquer outra tecla para cancelar a migração.",
                ["ConfirmCharacter"] = "sim",
                ["DatabaseFileAlreadyExists"] = "{00} já existe. Substituir? (s/n)",
                ["DefaultDatabase"] = "intersect_{00}_{01}",
                ["DefaultHost"] = "localhost",
                ["DefaultPortMySql"] = "3306",
                ["DefaultUsername"] = "root",
                ["EnterConnectionStringParameters"] = "Insira os parâmetros da string de conexão:",
                ["GameDatabaseName"] = "Jogo",
                ["LoggingDatabaseName"] = "Registro",
                ["MigratingDbSet"] = "Migrando entidades em {00}...",
                ["MigrationCanceled"] = "Migração cancelada",
                ["MigrationComplete"] = "Migração concluída! Pressione Enter para sair.",
                ["MySqlConnecting"] = "Aguarde, tentando se conectar ao banco de dados...",
                ["MySqlConnectionError"] = "Erro ao abrir conexão com o banco de dados! Erro: {00}",
                ["MySqlNotEmpty"] = "O banco de dados deve estar vazio antes da migração! Exclua todas as tabelas antes de continuar. Migração cancelada.",
                ["MySqlTryAgain"] = "Gostaria de tentar inserir suas informações de conexão novamente? (s/n)",
                ["PlayerDatabaseName"] = "Jogador",
                ["PromptDatabase"] = "Banco de dados ({00}):",
                ["PromptHost"] = "Host ({00}):",
                ["PromptPassword"] = "Senha (vazia):",
                ["PromptPort"] = "Porta ({00}):",
                ["PromptUsername"] = "Usuário ({00}):",
                ["SelectContext"] = "Qual banco de dados você gostaria de migrar:",
                ["SelectDatabase"] = "[{00}] {01} (atualmente usando {02}) {03}",
                ["SelectDatabaseType"] = "[{00}] {01}",
                ["SelectProvider"] = "Selecione para qual mecanismo migrar o banco de dados {00}:",
                ["SqliteRecommended"] = "SQLite é fortemente recomendado!",
                ["StartingMigration"] = "Iniciando a migração, aguarde! Isso pode levar vários minutos dependendo do tamanho do seu jogo.",
                ["StoppingServer"] = "Aguarde, parando o servidor e salvando o banco de dados atual...",
                ["TryAgainCharacter"] = "sim",
            },
            ["NetDebug"] = new JObject
            {
                ["Hastebin"] = "Informações de depuração de rede enviadas para {00} (copiadas para a área de transferência). Compartilhe este link com a AGD ao solicitar ajuda para colocar seu jogo online!",
                ["PleaseWait"] = "Aguarde enquanto o diagnóstico de rede é executado...",
                ["SavedToFile"] = "Informações de depuração de rede salvas em netdebug.txt! Carregue esse arquivo e compartilhe-o com AGD ao solicitar ajuda para colocar seu jogo online!",
            },
            ["Networking"] = new JObject
            {
                ["ServerFull"] = "O servidor está cheio no momento. Por favor, tente novamente mais tarde.",
            },
            ["Notifications"] = new JObject
            {
                ["Copyright"] = "Copyright (c) 2020-2025 Ascension Game Dev, todos os direitos reservados",
                ["Product"] = "Motor de jogo Intersect",
            },
            ["Parties"] = new JObject
            {
                ["AlreadyDenied"] = "Seu convite para o grupo já foi rejeitado!",
                ["Busy"] = "{00} está ocupado. Por favor, tente novamente mais tarde!",
                ["CannotCreateInstance"] = "Somente o líder do grupo pode criar uma instância compartilhada.",
                ["Declined"] = "{00} recusou seu convite para o grupo!",
                ["Disbanded"] = "O grupo foi dissolvido.",
                ["InInstance"] = "Você não pode convidar alguém para um grupo enquanto estiver em uma instância!",
                ["InstanceFailed"] = "Seu grupo falhou na instância...",
                ["InstanceInProgress"] = "O grupo ainda não concluiu sua instância.",
                ["InstanceInUse"] = "Não é possível criar uma nova instância – os membros do grupo ainda estão na antiga.",
                ["InstanceLivesRemaining"] = "Seu grupo tem {00} vidas restantes nesta instância!",
                ["InParty"] = "{00} já está em um grupo!",
                ["Joined"] = "{00} juntou-se ao grupo!",
                ["Kicked"] = "Você foi expulso do grupo!",
                ["LeaderInviteOnly"] = "Somente o líder do grupo pode enviar convites para o seu grupo.",
                ["Left"] = "Você saiu do grupo.",
                ["LimitReached"] = "Você atingiu o limite máximo de membros do grupo. Expulse outro membro antes de adicionar mais.",
                ["MemberKicked"] = "{00} foi expulso do grupo!",
                ["MemberLeft"] = "{00} saiu do grupo!",
                ["NoMoreLivesRemaining"] = "Seu grupo não tem mais vidas restantes! Você reaparecerá fora da instância na sua próxima morte.",
                ["NotInParty"] = "Você não está em um grupo.",
                ["OutOfRange"] = "O alvo está fora do alcance ou off-line.",
                ["WrongInstance"] = "Seu grupo está atualmente executando uma instância diferente.",
            },
            ["PasswordResetNotification"] = new JObject
            {
                ["Subject"] = "Intersect Game Engine - Código de redefinição de senha",
            },
            ["Player"] = new JObject
            {
                ["Admin"] = "{00} recebeu poderes administrativos!",
                ["AdminJoined"] = "Você é um administrador! Pressione Insert a qualquer momento para acessar o menu de administração ou F2 para informações de depuração.",
                ["AdminSetPower"] = "Somente administradores podem definir poder!",
                ["BeenWarpedTo"] = "Você foi teleportado para {00}.",
                ["CannotAlterOwnPower"] = "Você não pode alterar seu próprio poder!",
                ["CannotWarpToYourself"] = "Você não pode se teleportar para si mesmo.",
                ["Deadmin"] = "{00} teve seus poderes administrativos cassados!",
                ["HasWarpedTo"] = "{00} foi teleportado para você.",
                ["InstanceUpdate"] = "O ID da sua instância mudou de {00} para {01}.",
                ["Kicked"] = "{00} foi expulso por {01}!",
                ["Killed"] = "{00} foi morto por {01}!",
                ["Left"] = "{00} saiu {01}.",
                ["LevelLost"] = "Você perdeu um nível! Você está agora no nível {00}!",
                ["LevelUp"] = "Você subiu de nível! Você está agora no nível {00}!",
                ["Moderator"] = "{00} recebeu poderes de moderação!",
                ["ModeratorJoined"] = "Você é um moderador! Pressione Insert a qualquer momento para acessar o menu de administração ou F2 para informações de depuração.",
                ["Offline"] = "O usuário não está online!",
                ["OverworldReturnAdmin"] = "Você devolveu {00} ao mundo.",
                ["OverworldReturned"] = "Você foi devolvido ao mundo.",
                ["PlayerNotFound"] = "O jogador '{00}' não foi encontrado!",
                ["InvalidItem"] = "Item inválido selecionado.",
                ["InvalidQuantity"] = "A quantidade deve ser maior que zero.",
                ["ItemGiveFailed"] = "Incapaz de fornecer {00}x {01} para {02}.",
                ["ItemGiveSuccess"] = "Você deu {00}x {01} para {02}.",
                ["ItemReceivedFromAdmin"] = "{00} deu a você {01}x {02}.",
                ["ItemSpawnFailed"] = "Não foi possível gerar {00}x {01} para {02}.",
                ["ItemSpawnSuccess"] = "Você gerou {00}x {01} para {02}.",
                ["ItemSpawnedNearYou"] = "{00} gerou {01}x {02} perto de você.",
                ["PowerChanged"] = "Seu poder foi modificado!",
                ["ServerKicked"] = "{00} foi expulso pelo servidor!",
                ["ServerKilled"] = "{00} foi morto pelo servidor!",
                ["LearnedSpell"] = "Você aprendeu o feitiço {00}!",
                ["ForgotSpell"] = "Você esqueceu o feitiço {00}!",
                ["StatPoints"] = "Você tem {00} pontos de estatísticas disponíveis para serem gastos!",
                ["WarpedTo"] = "Teleportado para {00}.",
                ["WarpedToYou"] = "{00} teleportado para você.",
            },
            ["Portchecking"] = new JObject
            {
                ["AntivirusCheck"] = "2. Programas antivírus também podem estar bloqueando conexões. Pode ser necessário adicionar Intersect Server.exe às exclusões de antivírus.",
                ["CheckFirewalls"] = "1. Os firewalls podem estar bloqueando as conexões com o seu servidor. Verifique os firewalls do seu sistema (por exemplo, iptables, FirewallD, Firewall do Windows).",
                ["CheckRouterUpnp"] = "Parece que UPnP falhou. Pode ser necessário ativar UPnP em seu roteador ou encaminhar manualmente a porta para permitir conexões com seu servidor.",
                ["ConnectionInfo"] = "Informações de conexão:",
                ["DebuggingSteps"] = "Etapas de depuração (para permitir acesso público):",
                ["DocumentationUrl"] = "https://docs.freemmorpgmaker.com/en-US/deploy/forwarding/",
                ["PortCheckerAndUpnpDisabled"] = "O serviço de verificação de porta e UPnP foram desativados. Verifique o status do servidor manualmente com um cliente.",
                ["PortNotOpenTryingUpnp"] = "A porta {0} não está aberta, tentando UPnP...",
                ["PortNotOpenUpnpDisabled"] = "A porta {0} não está aberta, mas UPnP está desabilitada. Verifique o encaminhamento de porta do roteador e as configurações do firewall do computador.",
                ["ProbablyFirewall"] = "UPnP supostamente teve sucesso, mas o servidor não está acessível na porta {0}. Verifique o firewall da máquina em que este servidor está sendo executado.",
                ["PublicIp"] = "IP público: {00}",
                ["PublicPort"] = "Porta pública: {00}",
                ["RouterUpnpFailed"] = "UPnP falhou. Verifique o status do servidor manualmente usando um cliente.",
                ["TryingUpnp"] = "Tentando abrir a porta usando UPnP...",
                ["UpnpSucceededPortCheckerDisabled"] = "UPnP foi bem-sucedido, mas o verificador de porta está desativado. Verifique o status do servidor manualmente usando um cliente.",
                ["WithinRestrictedNetwork"] = "3. Se você estiver em um campus universitário ou em uma rede comercial, provavelmente não terá permissão para abrir portas ou hospedar jogos. Neste caso, você deve explorar opções de hospedagem externa!",
            },
            ["Quests"] = new JObject
            {
                ["Abandoned"] = "Missão abandonada: {00}!",
                ["Completed"] = "Missão: {00} concluída!",
                ["Declined"] = "Missão recusada: {00}!",
                ["ItemTask"] = "{00} atualizado! {01}/{02} {03}(s) coletados!",
                ["NpcTask"] = "{00} atualizado! {01}/{02} {03}(s) mortos!",
                ["Started"] = "Missão iniciada: {00}!",
                ["TaskCompleted"] = "Tarefa concluída!",
                ["Updated"] = "Missão: {00} atualizada!",
            },
            ["Regex"] = new JObject
            {
                ["Email"] = "^(([\\w-]+\\.)+[\\w-]+|([a-zA-Z]{1}|[\\w-]{2,}))@((([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])){1}|([a-zA-Z]+[\\w-]+\\.)+[a-zA-Z]{2,4})$",
                ["GuildName"] = "^[a-zA-Z0-9 ]{3,20}$",
                ["Username"] = "^[a-zA-Z0-9]{2,20}$",
            },
            ["Shops"] = new JObject
            {
                ["Bound"] = "Este item está vinculado a você e não pode ser vendido!",
                ["CannotAfford"] = "A transação falhou devido a fundos insuficientes.",
                ["DoesNotAccept"] = "Esta loja não aceita esse item!",
                ["FailedToRemoveItem"] = "Falha ao remover itens do slot {00} para o jogador {01}. Quantidade a remover: {02} a {03}",
                ["InventoryFull"] = "Você não tem espaço suficiente para comprar esse item!",
                ["SuccessfullyRemovedItem"] = "{00} itens removidos com sucesso do slot {01} para o jogador {02} em {03}",
                ["TransactionFailed"] = "Falha na transação!",
            },
            ["Trading"] = new JObject
            {
                ["Accepted"] = "A negociação foi um sucesso!",
                ["AlreadyDenied"] = "Sua solicitação de negociação já foi negada!",
                ["Bound"] = "Este item está vinculado a você e não pode ser negociado!",
                ["Busy"] = "{00} está ocupado. Por favor, tente novamente mais tarde!",
                ["Declined"] = "A negociação foi recusada!",
                ["InvalidOffer"] = "Item inválido selecionado para oferta!",
                ["InvalidRevoke"] = "Item inválido selecionado para revogar!",
                ["ItemsDropped"] = "Sem espaço no inventário. Alguns de seus itens caíram no chão!",
                ["OfferAccepted"] = "{00} aceitou sua oferta. Por favor, confirme a negociação.",
                ["OutOfRange"] = "O alvo de troca está fora do alcance ou off-line.",
                ["RevokeNotAllowed"] = "Você não pode revogar este item, {00} já aceitou a troca!",
            },
            ["Upnp"] = new JObject
            {
                ["FailedForwardingTcp"] = "Falha ao encaminhar automaticamente a porta TCP {00} usando UPnP. O UPnP pode estar desativado nas configurações do seu roteador ou esta porta já pode estar encaminhada.",
                ["FailedForwardingUdp"] = "Falha ao encaminhar automaticamente a porta UDP {00} usando UPnP. O UPnP pode estar desativado nas configurações do seu roteador ou esta porta já pode estar encaminhada.",
                ["ForwardedTcp"] = "Porta TCP {00} encaminhada automaticamente com sucesso usando UPnP.",
                ["ForwardedUdp"] = "Porta UDP {00} encaminhada automaticamente com sucesso usando UPnP.",
                ["InitializationFailed"] = "Falha na inicialização do serviço UPnP. Você pode não ter um roteador ou o UPnP no seu roteador pode estar desativado.",
                ["Initialized"] = "Inicialização do serviço UPnP bem-sucedida.",
            },
            ["Mail"] = new JObject
            {
                ["inventoryfull"] = "Não há espaço suficiente em seu inventário.",
                ["receiveitem"] = "Você recebeu um item!",
                ["playernotfound"] = "Jogador não encontrado!",
                ["newmail"] = "Você recebeu um novo correio!",
                ["mailnotfound"] = "Correio não encontrado!",
                ["invaliditem"] = "O item selecionado é inválido ou não pode ser anexado ao correio.",
                ["broadcastsent"] = "Correio em massa enviado.",
                ["broadcastfailed"] = "Falha ao enviar correio em massa.",
                ["broadcastmissingtitle"] = "O assunto do correio é obrigatório.",
                ["broadcastmissingmessage"] = "A mensagem do correio é obrigatória.",
                ["broadcastmissingitem"] = "É necessário pelo menos um item de anexo do correio.",
                ["broadcastinvalidquantity"] = "As quantidades de anexos de correio devem ser maiores que zero.",
                ["broadcasttoomanyattachments"] = "O correio em massa pode incluir no máximo {00} itens de anexo.",
                ["broadcastnorecipients"] = "Não havia destinatários para o correio em massa.",
            },
            ["Market"] = new JObject
            {
                ["invalidlisting"] = "Listagem inválida.",
                ["listingcreated"] = "Seu item foi listado no mercado.",
                ["listingunavailable"] = "Esta listagem não está mais disponível.",
                ["notenoughmoney"] = "Você não tem dinheiro suficiente.",
                ["inventoryfull"] = "Seu inventário está cheio.",
                ["itempurchased"] = "Você comprou o item.",
                ["salecompleted"] = "Venda no mercado concluída.",
                ["yoursolditem"] = "Você vendeu um item no mercado!",
                ["expiredlisting"] = "Listagem expirada.",
                ["yourlistingexpired"] = "Uma de suas listagens de mercado expirou. O item foi devolvido para você.",
                ["transactionfailed"] = "A transação de mercado falhou.",
                ["cannotlist"] = "Você não pode listar este item.",
                ["cannotremoveitem"] = "Não foi possível remover o item do seu inventário.",
            },
        };
    }
}
