using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Intersect.Client.Localization;

internal static partial class ClientLocalizationOverrides
{
    private static partial void AddFrOverrides(IDictionary<string, JObject> overrides)
    {
        overrides["fr"] = new JObject
        {
            ["Market"] = new JObject
            {
                ["sellwindow"] = @"Vendre sur le marché",
                ["selectitem"] = @"Sélectionnez un objet de votre inventaire",
                ["publish_colon"] = @"Publier :",
                ["quantity"] = @"Quantité",
                ["price"] = @"Prix",
                ["taxes_estimated"] = @"🧾 Taxe estimée : {0}",
                ["taxes_0"] = @"🧾 Taxe estimée : 0",
                ["splitpackages"] = @"Diviser en paquets (1, 10, 100, 1000)",
                ["publish"] = @"Publier",
                ["noItemSelected"] = @"⚠️ Aucun objet sélectionné.",
                ["invalidItem"] = @"⚠️ Objet introuvable dans l'inventaire.",
                ["invalidQuantity"] = @"❌ La quantité doit être supérieure à zéro.",
                ["invalidPrice"] = @"❌ Le prix doit être supérieur à zéro.",
                ["quantityExceeds"] = @"❌ La quantité dépasse les objets disponibles ({0}).",
                ["priceOutOfRange"] = @"❌ Le prix doit être compris entre {0} et {1} 🪙.",
                ["pricehint"] = @"Prix suggéré : {0}",
                ["pricerange"] = @"Plage suggérée : {0}/{1}",
                ["listedSuccessfully"] = @"Offre créée avec succès !",
                ["windowTitle"] = @"Marché mondial",
                ["itemNameLabel"] = @"Nom de l'objet :",
                ["itemTypeLabel"] = @"Type :",
                ["all"] = @"Tous",
                ["minPriceLabel"] = @"Prix min :",
                ["maxPriceLabel"] = @"Prix max :",
                ["searchButton"] = @"Rechercher",
                ["sellButton"] = @"Vendre",
                ["retryButton"] = @"Réessayer",
                ["headerItemName"] = @"Nom de l'objet",
                ["headerQuantity"] = @"Quantité",
                ["headerPrice"] = @"Prix",
                ["noResults"] = @"❌ Aucun résultat trouvé.",
                ["itemSubTypeLabel"] = @"Sous-types",
                ["Buy"] = @"Acheter",
            },
            ["PlayerShops"] = new JObject
            {
                ["CreatorTitle"] = @"Boutique de joueurs",
                ["ShopNameLabel"] = @"Nom de la boutique",
                ["ShopNamePlaceholder"] = @"Entrez un nom convivial pour la boutique",
                ["Hint"] = @"Faites glisser des objets dans les emplacements pour configurer votre boutique.",
                ["DecorationLabel"] = @"Décoration",
                ["SelectSlot"] = @"Sélectionnez un emplacement d’annonce à modifier.",
                ["QuantityInput"] = @"Quantité",
                ["PriceInput"] = @"Prix à l’unité",
                ["ClearSlot"] = @"Vider l’emplacement",
                ["CreateShop"] = @"Entrer en mode marchand",
                ["Cancel"] = @"Annuler",
                ["StatusReady"] = @"Prêt à envoyer.",
                ["StatusSubmitting"] = @"Envoi de la demande...",
                ["ErrorMissingName"] = @"Entrez un nom de boutique.",
                ["ErrorMissingItems"] = @"Ajoutez au moins un objet.",
                ["ErrorInvalidQuantity"] = @"La quantité doit être supérieure à zéro.",
                ["ErrorInvalidPrice"] = @"Le prix doit être supérieur à zéro.",
                ["ErrorInvalidInventory"] = @"L’objet sélectionné n’est plus dans votre inventaire.",
                ["ErrorNotEnoughItems"] = @"Pas assez d’objets dans l’emplacement d’inventaire {0}.",
                ["SelectedItemLabel"] = @"Sélectionné : {0}",
                ["EmptySlot"] = @"Emplacement vide",
                ["SlotQuantity"] = @"Quantité : {0}/{1}",
                ["SlotPrice"] = @"Prix : {0}",
                ["BrowserTitle"] = @"Boutique de {0}",
                ["BrowserOwner"] = @"Propriétaire : {0}",
                ["BrowserPriceEach"] = @"Prix : {0} l’unité",
                ["BrowserAvailable"] = @"Disponible : {0}",
                ["BrowserTotal"] = @"Total : {0}",
                ["BrowserBuy"] = @"acheter",
                ["BrowserEmpty"] = @"Cette boutique n’a aucun objet en vente.",
                ["BrowseStatus"] = @"Sélectionnez un objet pour commencer.",
                ["UnknownItem"] = @"Objet inconnu",
            },
            ["MailBox"] = new JObject
            {
                ["title"] = @"Boîte aux lettres",
                ["sendtitle"] = @"Envoyer un courrier",
                ["send"] = @"envoyer",
                ["close"] = @"Fermer",
                ["itemnone"] = @"Aucun",
                ["mailto"] = @"à",
                ["mailtitle"] = @"Titre",
                ["mailmsg"] = @"Message",
                ["mailitem"] = @"Objet",
                ["mailquantity"] = @"Quantité",
                ["mails"] = @"Courriers",
                ["sender"] = @"Expéditeur",
                ["take"] = @"Récupérer le courrier (Delete)",
                ["additem"] = @"Ajouter un objet",
                ["attachments"] = @"Pièces jointes",
                ["sendMailButton"] = @"📤 Envoyer le courrier",
                ["closeButton"] = @"❌ Fermer",
                ["unknownSender"] = @"Expéditeur inconnu",
                ["noSubject"] = @"Sans objet",
                ["selectQuantity"] = @"Sélectionner la quantité",
                ["enterQuantity"] = @"Saisir la quantité",
            },
            ["Breaking"] = new JObject
            {
                ["WindowTitle"] = @"Démantèlement d’objet",
                ["Title"] = @"Démonter des objets",
                ["SelectedItem"] = @"Objet sélectionné",
                ["ResultItems"] = @"Résultats possibles",
                ["Break"] = @"Démonter",
                ["NoItemSelected"] = @"Aucun objet sélectionné à démonter !",
                ["BreakSuccess"] = @"L’objet a été démonté avec succès.",
                ["BreakFail"] = @"L’objet n’a pas pu être démonté.",
                ["ConfirmBreak"] = @"Êtes-vous sûr de vouloir démonter cet objet ?",
                ["Close"] = @"Fermer",
                ["ItemLocked"] = @"Cet objet ne peut pas être démonté.",
                ["NothingToGain"] = @"Démonter cet objet ne donne aucun matériau.",
            },
            ["Enchanting"] = new JObject
            {
                ["WindowTitle"] = @"Enchantement d’objets",
                ["Title"] = @"Enchantement d’objets",
                ["SelectedItem"] = @"Objet sélectionné",
                ["Cost"] = @"Coût d’enchantement",
                ["Chance"] = @"Chances de réussite",
                ["UseAmulet"] = @"Utiliser une amulette de protection",
                ["Enchant"] = @"enchanter",
                ["NoItemSelected"] = @"Aucun objet sélectionné à enchanter !",
                ["EnchantSuccess"] = @"L’objet a été enchanté avec succès !",
                ["EnchantFail"] = @"L’enchantement a échoué. Bonne chance la prochaine fois !",
                ["InsufficientCurrency"] = @"Vous n’avez pas assez de monnaie pour enchanter cet objet.",
                ["Close"] = @"Fermer",
                ["Projection"] = @"Projection",
                ["MaxEnchantReached"] = @"L’objet a atteint le niveau maximum d’enchantement !",
            },
            ["Job"] = new JObject
            {
                ["job"] = @"Fenêtre des métiers",
                ["Farming"] = @"agriculture",
                ["Fishing"] = @"pêche",
                ["Mining"] = @"mine",
                ["Lumberjack"] = @"bûcheron",
                ["Hunting"] = @"chasse",
                ["Blacksmith"] = @"forgeron",
                ["Cooking"] = @"cuisine",
                ["Alchemy"] = @"alchimie",
                ["Crafting"] = @"artisanat",
                ["Jewerly"] = @"joaillerie",
                ["Tanner"] = @"tanneur",
                ["Tailoring"] = @"couture",
                ["None"] = @"Aucun",
                ["MaxLevel"] = @"Niveau max",
                ["ExpValue"] = @"{0} / {1}",
                ["Exp"] = @"EXP : ",
                ["Level"] = @"Niveau {0}",
            },
            ["AdminWindow"] = new JObject
            {
                ["Access"] = @"Accès",
                ["Access1"] = @"Modérateur",
                ["Access2"] = @"Administrateur",
                ["Ban"] = @"Bannir",
                ["BanCaption"] = @"Bannir {00}",
                ["BanPrompt"] = @"Bannir {00} ne lui permettra pas d’accéder à ce jeu pendant la durée que vous fixez !",
                ["SortMapList"] = @"Trier la liste des cartes",
                ["SortMapListTooltip"] = @"Trie les cartes en une hiérarchie plate, dans l’ordre alphanumérique selon les paramètres régionaux de l’ordinateur.",
                ["Face"] = @"Visage",
                ["KickPlayer"] = @"Expulser",
                ["KillPlayer"] = @"Tuer",
                ["QuickActions"] = @"Actions rapides",
                ["AdditionalInterfaces"] = @"Outils supplémentaires",
                ["MapList"] = @"Liste des cartes",
                ["Mute"] = @"Mettre en sourdine",
                ["MuteCaption"] = @"Mettre en sourdine {00}",
                ["MutePrompt"] = @"Mettre en sourdine {00} ne lui permettra pas de discuter en jeu pendant la durée que vous fixez !",
                ["Name"] = @"Nom",
                ["NamePlaceholder"] = @"Nom du joueur",
                ["None"] = @"Aucun",
                ["LeaveInstance"] = @"Quitter l’instance",
                ["SetFace"] = @"Définir le visage",
                ["SetPower"] = @"Définir la puissance",
                ["SetSprite"] = @"Définir le sprite",
                ["Appearance"] = @"Apparence",
                ["Sprite"] = @"sprite :",
                ["Item"] = @"Objet",
                ["ItemManagement"] = @"Objets",
                ["Quantity"] = @"Quantité",
                ["AllowOverflow"] = @"Autoriser le dépassement de banque",
                ["ReserveSpawn"] = @"Réserver l’apparition pour le joueur",
                ["GiveItem"] = @"Donner un objet",
                ["SpawnItem"] = @"Générer un objet",
                ["MailBroadcast"] = @"Diffusion de courrier",
                ["MailSubject"] = @"Sujet",
                ["MailMessage"] = @"Message",
                ["MailAttachmentItem"] = @"Pièce jointe {00} objet",
                ["MailAttachmentQuantity"] = @"Pièce jointe {00} quantité",
                ["MailOnlineOnly"] = @"Joueurs en ligne uniquement",
                ["MailSend"] = @"Envoyer le courrier",
                ["Title"] = @"administration",
                ["Unban"] = @"Débannir",
                ["UnbanCaption"] = @"Débannir {00}",
                ["UnbanPrompt"] = @"Êtes-vous sûr de vouloir débannir {00} ?",
                ["Unmute"] = @"Retirer la sourdine",
                ["UnmuteCaption"] = @"Retirer la sourdine {00}",
                ["UnmutePrompt"] = @"Êtes-vous sûr de vouloir retirer la sourdine de {00} ?",
                ["WarpPlayerToMe"] = @"Téléporter le joueur vers moi",
                ["WarpMeToPlayer"] = @"Me téléporter vers le joueur",
            },
            ["Bags"] = new JObject
            {
                ["RetrieveItem"] = @"Récupérer l’objet",
                ["RetrieveItemPrompt"] = @"Combien de {00} souhaitez-vous récupérer ?",
                ["StoreItem"] = @"Déposer l’objet",
                ["StoreItemPrompt"] = @"Combien de {00} souhaitez-vous déposer ?",
                ["Title"] = @"Sac",
            },
            ["Bank"] = new JObject
            {
                ["DepositItem"] = @"Déposer l’objet",
                ["DepositItemPrompt"] = @"Combien de {00} souhaitez-vous déposer ?",
                ["NoSpace"] = @"Plus d’espace dans votre banque pour cet objet !",
                ["Title"] = @"Banque",
                ["WithdrawItem"] = @"Retirer l’objet",
                ["WithdrawItemPrompt"] = @"Combien de {00} souhaitez-vous retirer ?",
                ["WithdrawItemNoSpace"] = @"Plus d’espace dans votre inventaire pour cet objet !",
                ["All"] = @"Tous",
                ["Sort"] = @"Trier",
                ["BankValue"] = @"Valeur bancaire : {00}",
                ["BankValueFull"] = @"{00} Monnaies globales",
            },
            ["BanMute"] = new JObject
            {
                ["Cancel"] = @"Annuler",
                ["Duration"] = @"Durée :",
                ["FiveDays"] = @"5 jours",
                ["FourDays"] = @"4 jours",
                ["Forever"] = @"indéfiniment",
                ["IncludeIp"] = @"Inclure l’IP :",
                ["OneDay"] = @"1 jour",
                ["OneMonth"] = @"1 mois",
                ["OneWeek"] = @"1 semaine",
                ["OneYear"] = @"1 an",
                ["Okay"] = @"OK",
                ["Reason"] = @"Raison :",
                ["SixMonths"] = @"6 mois",
                ["ThreeDays"] = @"3 jours",
                ["TwoDays"] = @"2 jours",
                ["TwoMonths"] = @"2 mois",
                ["TwoWeeks"] = @"2 semaines",
            },
            ["Bestiary"] = new JObject
            {
                ["Title"] = @"Bestiaire",
                ["SearchPlaceholder"] = @"Rechercher...",
                ["SectionStats"] = @"Statistiques",
                ["SectionDrops"] = @"Butin",
                ["SectionSpells"] = @"Sorts",
                ["SectionBehavior"] = @"Comportement",
                ["SectionLore"] = @"Histoire",
                ["Locked"] = @"verrouillé",
                ["Unlocked"] = @"déverrouillé",
                ["UnlockNotice"] = @"Déverrouillé {1} pour {0}",
                ["LockedKills"] = @"🔒 Vaincre {0}/{1} fois pour déverrouiller.",
                ["LockedInfo"] = @"🔒 Informations verrouillées.",
                ["AggressiveLabel"] = @"Agressif : {0}",
                ["MovementLabel"] = @"Mouvement : {0}",
                ["FleeHpLabel"] = @"Fuite % PV : {0}%",
                ["SwarmLabel"] = @"Essaim : {0}",
                ["Yes"] = @"Oui",
                ["No"] = @"Non",
                ["LorePlaceholder"] = @"(Ici vous pouvez insérer un système optionnel de descriptions de PNJ)",
            },
            ["Character"] = new JObject
            {
                ["AttackSpeed"] = @"Vitesse d’attaque : {00}s",
                ["CooldownReduction"] = @"Réduction du temps de recharge : {00}%",
                ["Equipment"] = @"Équipement :",
                ["ExtraBuffs"] = @"Bonus supplémentaires",
                ["ExtraExp"] = @"EXP bonus : {00}%",
                ["HealthRegen"] = @"Régénération de santé : {00}%",
                ["CriticalChance"] = @"Chances de coup critique : {00}%",
                ["LevelAndClass"] = @"Niveau : {00}, Classe : {01}",
                ["Lifesteal"] = @"Vol de vie : {00}%",
                ["Luck"] = @"Chance : {00}%",
                ["ManaRegen"] = @"Régénération de mana : {00}%",
                ["Manasteal"] = @"Vol de mana : {00}%",
                ["BasicAttackDamage"] = @"Dégâts de base : {00} | Vrais : {01}-{02}",
                ["Points"] = @"Points : {00}",
                ["StatLabelValue"] = @"{00} : {01}",
                ["Stats"] = @"Statistiques :",
                ["Agility"] = @"Agilité :",
                ["Tenacity"] = @"Ténacité : {00}%",
                ["FlatDamage"] = @"Bonus de dégâts : {00}",
                ["FlatCures"] = @"Bonus de soins : {00}",
                ["Title"] = @"Informations du personnage",
            },
            ["CharacterCreation"] = new JObject
            {
                ["Back"] = @"Retour",
                ["Class"] = @"classe",
                ["Create"] = @"créer",
                ["Female"] = @"Femme",
                ["Gender"] = @"Genre",
                ["Hint"] = @"Personnaliser",
                ["Hint2"] = @"votre personnage",
                ["InvalidName"] = @"Le nom du personnage n’est pas valide. Utilisez des caractères alphanumériques d’une longueur entre 2 et 20.",
                ["Male"] = @"Homme",
                ["Name"] = @"Nom",
                ["Title"] = @"Créer un nouveau personnage",
            },
            ["CharacterSelection"] = new JObject
            {
                ["Delete"] = @"Supprimer",
                ["DeletePrompt"] = @"Êtes-vous sûr de vouloir supprimer {00} ? Cette action est irréversible !",
                ["DeleteTitle"] = @"Supprimer {00}",
                ["Empty"] = @"Emplacement de personnage vide",
                ["Info"] = @"Niveau : {00}, Classe : {01}",
                ["Logout"] = @"Déconnexion",
                ["ChangePassword"] = @"Changer le mot de passe",
                ["Name"] = @"{00}",
                ["New"] = @"Nouveau",
                ["Play"] = @"Jouer",
                ["Title"] = @"Sélectionnez un personnage pour jouer",
            },
            ["Chatbox"] = new JObject
            {
                ["Channel"] = @"Canal :",
                ["ChannelAdmin"] = @"admin",
                ["ClearLogButtonToolTip"] = @"Effacer les messages du journal de chat",
                ["EnterChat"] = @"Cliquez ici pour discuter.",
                ["EnterChat1"] = @"Appuyez sur '{00}' pour discuter.",
                ["EnterChat2"] = @"Appuyez sur '{00}' ou '{01}' pour discuter.",
                ["Send"] = @"envoyer",
                ["Title"] = @"Chat",
                ["ToggleLogButtonToolTip"] = @"Basculer la visibilité du journal de chat",
                ["TooFast"] = @"Vous discutez trop vite !",
                ["UnableToCopy"] = @"Il semble que vous ne pouvez pas copier/coller sur cette plateforme. Assurez-vous d’avoir installé les paquets 'xclip' ou 'wl-clipboard' si vous utilisez Linux.",
            },
            ["Combat"] = new JObject
            {
                ["AttackWhileCastingDeny"] = @"Vous ne pouvez pas attaquer pendant que vous lancez un sort.",
                ["WarningCharacterSelect"] = @"Vous essayez de vous déconnecter en combat ! Votre personnage restera en jeu jusqu’à la fin du combat. Êtes-vous sûr de vouloir vous déconnecter maintenant ?",
                ["WarningExitDesktop"] = @"Vous essayez de quitter en combat ! Votre personnage restera en jeu jusqu’à la fin du combat. Êtes-vous sûr de vouloir quitter maintenant ?",
                ["WarningLogout"] = @"Vous essayez de vous déconnecter en combat ! Votre personnage restera en jeu jusqu’à la fin du combat. Êtes-vous sûr de vouloir vous déconnecter maintenant ?",
                ["WarningTitle"] = @"Avertissement de combat !",
            },
            ["Content"] = new JObject
            {
            },
            ["Controls"] = new JObject
            {
                ["HotkeyXLabel"] = @"Touche de raccourci {00} :",
                ["Listening"] = @"Écoute",
            },
            ["Crafting"] = new JObject
            {
                ["Craft"] = @"Fabriquer 1",
                ["CraftAll"] = @"Fabriquer {00}",
                ["CraftChance"] = @"Chance d’échec : {00}%",
                ["CraftingTime"] = @"Temps de fabrication : {00}s",
                ["CraftStop"] = @"Arrêter",
                ["DestroyMaterialsChance"] = @"Chance de détruire les matériaux : {00}%",
                ["IncorrectResources"] = @"Vous n’avez pas les ressources nécessaires pour fabriquer cet objet.",
                ["Ingredients"] = @"Requis :",
                ["Product"] = @"Résultat :",
                ["Recipes"] = @"Recettes :",
                ["RecipeListEntry"] = @"{00}) {01}",
                ["Exp"] = @"EXP : {00}",
                ["CraftingName"] = @"Artisanat",
            },
            ["Credits"] = new JObject
            {
                ["Back"] = @"Retour au menu principal",
                ["Title"] = @"Crédits",
            },
            ["Debug"] = new JObject
            {
                ["SectionGPUStatistics"] = @"Statistiques GPU",
                ["SectionGPUAllocations"] = @"Allocations GPU",
                ["SectionSystemStatistics"] = @"Statistiques système",
                ["RenderTargetAllocations"] = @"Allocations de cibles de rendu",
                ["TextureAllocations"] = @"Allocations de textures",
                ["TextureCount"] = @"Ressources de texture",
                ["UsedVRAM"] = @"VRAM utilisée",
                ["FreeVRAM"] = @"VRAM libre",
                ["TotalVRAM"] = @"VRAM totale",
                ["FreeVirtualRAM"] = @"RAM libre (virtuelle)",
                ["TotalVirtualRAM"] = @"RAM totale (virtuelle)",
                ["FreePhysicalRAM"] = @"RAM libre (physique)",
                ["TotalPhysicalRAM"] = @"RAM totale (physique)",
                ["ControlUnderCursor"] = @"Contrôle sous le curseur",
                ["DrawDebugOutlines"] = @"Dessiner les contours de débogage",
                ["Draws"] = @"Dessins",
                ["EnableLayoutHotReloading"] = @"Activer le rechargement à chaud de la mise en page expérimentale",
                ["IncludeTextNodesInHover"] = @"Inclure les nœuds de texte au survol",
                ["ViewClickedNodeInDebugger"] = @"Voir le nœud cliqué dans le débogueur",
                ["ViewClickedNodeInDebuggerTooltip"] = @"Maintenez Alt pour désactiver ceci temporairement (afin de pouvoir désactiver cette option)",
                ["EntitiesDrawn"] = @"Entités dessinées",
                ["Fps"] = @"FPS",
                ["InterfaceObjects"] = @"Objets d’interface",
                ["KnownEntities"] = @"Entités connues",
                ["KnownMaps"] = @"Cartes connues",
                ["LightsDrawn"] = @"Lumières dessinées",
                ["Map"] = @"Carte",
                ["MapsDrawn"] = @"Cartes dessinées",
                ["Ping"] = @"ping",
                ["ShutdownServer"] = @"Arrêter le serveur",
                ["ShutdownServerAndExit"] = @"Arrêter le serveur et quitter",
                ["FormatTextureFromAtlas"] = @"{00} (depuis l’atlas)",
                ["Time"] = @"temps",
                ["Title"] = @"Déboguer",
                ["TitleX"] = @"Débogage n°{0}",
                ["TabLabelSystem"] = @"Système",
                ["TabLabelInfo"] = @"Infos",
                ["TabLabelAssets"] = @"Ressources",
                ["ReloadAsset"] = @"Recharger la ressource",
                ["AssetsSearchPlaceholder"] = @"Filtrer les ressources...",
            },
            ["EntityBox"] = new JObject
            {
                ["Exp"] = @"EXP :",
                ["ExpValue"] = @"{00} / {01}",
                ["Level"] = @"Niv. {00}",
                ["Map"] = @"{00}",
                ["MaxLevel"] = @"Niveau max",
                ["NameAndLevel"] = @"{00} {01}",
                ["Vital0"] = @"PV :",
                ["Vital0Value"] = @"{00} / {01}",
                ["Vital1"] = @"PM :",
                ["Vital1Value"] = @"{00} / {01}",
            },
            ["Alerts"] = new JObject
            {
                ["FallbackTitle"] = @"Alerte",
            },
            ["Errors"] = new JObject
            {
                ["DisconnectionEvent"] = @"Fournissez ce message à votre administrateur : {0}",
                ["DisplayNotSupported"] = @"Paramètre d’affichage invalide !",
                ["DisplayNotSupportedError"] = @"La résolution plein écran {00} n’est pas prise en charge par cet appareil !",
                ["HostNotFound"] = @"Erreur de résolution DNS. Signalez-le à l’administrateur du jeu.",
                ["LoadFile"] = @"Impossible de charger un {00}. Envoyez à l’administrateur du jeu une copie de votre journal d’erreurs dans le répertoire des journaux.",
                ["LostConnection"] = @"Connexion au serveur de jeu perdue. Assurez-vous d’être connecté à Internet et réessayez !",
                ["NotConnected"] = @"Non connecté au serveur de jeu. Êtes-vous en ligne ?",
                ["InvalidStateReturnToMainMenu"] = @"Un état invalide a été détecté et nous avons dû revenir au menu principal.",
                ["OpenAllLink"] = @"https://goo.gl/Nbx6hx",
                ["OpenGlLink"] = @"https://goo.gl/RSP3ts",
                ["PasswordInvalid"] = @"Le mot de passe n’est pas valide. Utilisez des caractères alphanumériques d’une longueur entre 4 et 20.",
                ["ResourcesNotFound"] = @"Le répertoire des ressources est introuvable ! Intersect va se fermer.",
                ["Title"] = @"Erreur !",
                ["UsernameInvalid"] = @"Le nom d’utilisateur n’est pas valide. Utilisez des caractères alphanumériques d’une longueur entre 2 et 20.",
            },
            ["Words"] = new JObject
            {
                ["LcaseSound"] = @"son",
                ["LcaseSprite"] = @"sprite",
            },
            ["EventWindow"] = new JObject
            {
                ["Continue"] = @"Continuer",
            },
            ["ForgotPass"] = new JObject
            {
                ["Back"] = @"Retour",
                ["Disclaimer"] = @"Si un compte existe avec le nom d’utilisateur ou l’adresse e-mail fournis, un e-mail avec un code de réinitialisation de mot de passe sera envoyé à l’adresse associée au compte.",
                ["UsernameOrEmailPlaceholder"] = @"Nom d’utilisateur ou adresse e-mail",
                ["Submit"] = @"Envoyer",
                ["Title"] = @"Réinitialiser le mot de passe",
            },
            ["Friends"] = new JObject
            {
                ["AddFriend"] = @"Ajouter un ami",
                ["AddFriendPrompt"] = @"Qui souhaitez-vous ajouter comme ami ?",
                ["InFight"] = @"Vous êtes actuellement en combat !",
                ["Offline"] = @"Hors ligne",
                ["RemoveFriend"] = @"Supprimer un ami",
                ["RemoveFriendPrompt"] = @"Voulez-vous supprimer {00} de votre liste d’amis ?",
                ["Request"] = @"Demande d’ami",
                ["RequestPrompt"] = @"{00} vous a envoyé une demande d’ami. Acceptez-vous ?",
                ["Title"] = @"Amis",
            },
            ["GameMenu"] = new JObject
            {
                ["Achievements"] = @"Succès",
                ["Character"] = @"Informations du personnage",
                ["Friends"] = @"Amis",
                ["Items"] = @"Inventaire",
                ["Menu"] = @"Ouvrir le menu",
                ["Party"] = @"Groupe",
                ["Quest"] = @"Journal des quêtes",
                ["Spells"] = @"Livre de sorts",
                ["Jobs"] = @"Métiers",
            },
            ["General"] = new JObject
            {
                ["MapItemStackable"] = @"{01} {00}",
                ["None"] = @"Aucun",
                ["FpsLabelFormat"] = @"{0}fps",
                ["PingLabelFormat"] = @"{0}ms",
            },
            ["Guilds"] = new JObject
            {
                ["Add"] = @"+",
                ["Bank"] = @"Banque de guilde {00}",
                ["Demote"] = @"Rétrograder en {00}",
                ["DemotePrompt"] = @"Êtes-vous sûr de vouloir rétrograder {00} au rang {01} ?",
                ["DemoteTitle"] = @"Rétrograder un membre de la guilde",
                ["Guild"] = @"guilde",
                ["GuildTip"] = @"Envoyez une invitation de guilde à {00}.",
                ["Invite"] = @"inviter",
                ["InviteAlreadyInGuild"] = @"Le joueur que vous essayez d’inviter est déjà dans une guilde ou a une invitation en attente.",
                ["InviteMemberPrompt"] = @"Qui souhaitez-vous inviter à {00} ?",
                ["InviteMemberTitle"] = @"Inviter un joueur",
                ["InviteRequestPrompt"] = @"{00} souhaite vous inviter à rejoindre sa guilde, {01}. Acceptez-vous ?",
                ["InviteRequestPromptMissingGuild"] = @"{00} souhaite vous inviter à rejoindre sa guilde. Acceptez-vous ?",
                ["InviteRequestTitle"] = @"Invitation de guilde",
                ["Kick"] = @"expulser",
                ["KickPrompt"] = @"Êtes-vous sûr de vouloir expulser {00} ?",
                ["KickTitle"] = @"Expulser un membre de guilde",
                ["Leave"] = @"quitter",
                ["LeavePrompt"] = @"Êtes-vous sûr de vouloir quitter votre guilde ?",
                ["LeaveTitle"] = @"Quitter la guilde",
                ["NotAllowedDeposit"] = @"Vous n’avez pas la permission de déposer des objets dans la banque de guilde de {00}.",
                ["NotAllowedSwap"] = @"Vous n’avez pas la permission d’échanger des objets dans la banque de guilde de {00}.",
                ["NotAllowedWithdraw"] = @"Vous n’avez pas la permission de retirer de l’argent de la banque de guilde de {00}.",
                ["NotInGuild"] = @"Vous n’êtes actuellement pas dans une guilde !",
                ["OfflineListEntry"] = @"[{00}] {01} - {02}",
                ["OnlineListEntry"] = @"[{00}] {01} - {02}",
                ["PM"] = @"MP",
                ["Promote"] = @"Promouvoir en {00}",
                ["PromotePrompt"] = @"Êtes-vous sûr de vouloir promouvoir {00} au rang {01} ?",
                ["PromoteTitle"] = @"Promouvoir un membre de la guilde",
                ["Tooltip"] = @"Niv. {00} {01}",
                ["Transfer"] = @"Transférer",
                ["TransferToMemberPrompt"] = @"Cette action transférera entièrement la propriété de votre guilde à \c{{#80ff80}}{00}\c{{}} et vous perdrez votre rang \c{{#ff9f40}}{01}\c{{}}.\n\nSi vous êtes sûr de vouloir céder votre guilde, saisissez '\c{{#ff8080}}{02}\c{{}}' ci-dessous.",
                ["TransferTitle"] = @"Transférer la guilde",
            },
            ["InputBox"] = new JObject
            {
                ["Cancel"] = @"Annuler",
                ["No"] = @"Non",
                ["Okay"] = @"OK",
                ["Yes"] = @"Oui",
            },
            ["MapItemWindow"] = new JObject
            {
                ["LootButton"] = @"Tout piller",
                ["Title"] = @"Butin",
            },
            ["Internals"] = new JObject
            {
                ["Bounds"] = @"Limites",
                ["Color"] = @"Couleur",
                ["ColorOverride"] = @"Substitution de couleur",
                ["CoordinateX"] = @"x",
                ["CoordinateY"] = @"y",
                ["CoordinateZ"] = @"z",
                ["ExperimentalFeatureTooltip"] = @"Cette fonctionnalité est expérimentale et peut causer des problèmes lorsqu’elle est activée.",
                ["GlobalItem"] = @"Global {00}",
                ["LocalItem"] = @"Local {00}",
                ["Name"] = @"Nom",
                ["NotApplicable"] = @"N/A",
                ["ResolutionXByY"] = @"{0}x{1}",
                ["Type"] = @"Type",
                ["InnerBounds"] = @"Limites internes",
                ["Margin"] = @"Marge",
                ["Padding"] = @"Remplissage",
                ["Dock"] = @"Ancrage",
                ["Alignment"] = @"Alignement",
                ["TextAlign"] = @"Alignement du texte",
                ["OuterBounds"] = @"Limites externes",
                ["Font"] = @"police",
                ["AutoSizeToContents"] = @"Taille auto au contenu",
                ["FontSize"] = @"Taille de police",
                ["AutoSizeToContentWidth"] = @"Taille auto à la largeur du contenu",
                ["AutoSizeToContentHeight"] = @"Taille auto à la hauteur du contenu",
                ["AutoSizeToContentWidthOnChildResize"] = @"TA largeur sur redimensionnement enfant",
                ["AutoSizeToContentHeightOnChildResize"] = @"TA hauteur sur redimensionnement enfant",
                ["IsVisibleInParent"] = @"VisibleDansParent",
                ["IsVisibleInTree"] = @"Visible dans l’arbre",
                ["IsDisabled"] = @"Désactivé",
                ["IsDisabledByTree"] = @"DésactivéParArbre",
            },
            ["Inventory"] = new JObject
            {
                ["DropItemPrompt"] = @"Combien d’unités de {00} souhaitez-vous jeter ?",
                ["DropItemTitle"] = @"Jeter un objet",
                ["DropPrompt"] = @"Voulez-vous supprimer l’objet : {00} ?",
                ["EquippedSymbol"] = @"E",
                ["Title"] = @"Inventaire",
                ["Sort"] = @"Trier",
                ["All"] = @"Tout",
            },
            ["EntityContextMenu"] = new JObject
            {
                ["AddFriend"] = @"Ajouter un ami",
                ["InviteToGuild"] = @"Inviter à la guilde",
                ["InviteToParty"] = @"Inviter au groupe",
                ["PrivateMessage"] = @"Message privé",
                ["Trade"] = @"Échanger",
                ["InspectPlayer"] = @"Inspecter le joueur",
                ["ManagePlayerShop"] = @"Gérer ma boutique",
            },
            ["ItemContextMenu"] = new JObject
            {
                ["Bag"] = @"Sac {00}",
                ["Bank"] = @"Banque {00}",
                ["Cast"] = @"Lancer {00}",
                ["Drop"] = @"Jeter {00}",
                ["Equip"] = @"Équiper {00}",
                ["Learn"] = @"Apprendre {00}",
                ["Open"] = @"Ouvrir {00}",
                ["Sell"] = @"Vendre {00}",
                ["Show"] = @"Afficher {00}",
                ["Trade"] = @"Échanger {00}",
                ["Unequip"] = @"Déséquiper {00}",
                ["Use"] = @"Utiliser {00}",
            },
            ["SpellContextMenu"] = new JObject
            {
                ["Cast"] = @"Lancer {00}",
                ["Forget"] = @"Oublier {00}",
                ["LevelUp"] = @"Monter de niveau {00}",
            },
            ["BankContextMenu"] = new JObject
            {
                ["Withdraw"] = @"Retirer {00}",
            },
            ["BagContextMenu"] = new JObject
            {
                ["Withdraw"] = @"Retirer {00}",
            },
            ["TradeContextMenu"] = new JObject
            {
                ["Withdraw"] = @"Retirer {00}",
            },
            ["ChatContextMenu"] = new JObject
            {
                ["FriendInvite"] = @"Envoyer une demande d’ami à {00}",
                ["GuildInvite"] = @"Inviter {00} dans la guilde",
                ["PartyInvite"] = @"Inviter {00} dans un groupe",
                ["PM"] = @"Envoyer un message privé à {00}",
            },
            ["ShopContextMenu"] = new JObject
            {
                ["Buy"] = @"Acheter {00}",
            },
            ["ItemDescription"] = new JObject
            {
                ["Amount"] = @"Quantité :",
                ["AttackSpeed"] = @"Vitesse d’attaque :",
                ["AttackSpeedComparison"] = @"Vitesse d’attaque : {00} ({01})",
                ["BagSlots"] = @"Emplacements de sac :",
                ["Bagged"] = @"Mis en sac",
                ["Banked"] = @"En banque",
                ["BaseDamage"] = @"Dégâts de base :",
                ["BaseDamageType"] = @"Type de dégâts :",
                ["BlockAbsorption"] = @"Absorption du blocage :",
                ["BlockAmount"] = @"Valeur de blocage :",
                ["BlockChance"] = @"Chance de blocage :",
                ["CastSpell"] = @"Lance le sort : {00}",
                ["CritChance"] = @"Chance de critique :",
                ["CritMultiplier"] = @"Multiplicateur de critique :",
                ["Description"] = @"{00}",
                ["DropOnDeath"] = @"Chance de drop à la mort :",
                ["Dropped"] = @"Lâché",
                ["GuildBanked"] = @"En banque de guilde",
                ["ItemLimits"] = @"Ne peut pas être {00}",
                ["Multiplier"] = @"{00}x",
                ["Percentage"] = @"{00}%",
                ["RegularAndPercentage"] = @"{00} + {01}%",
                ["ResourceBonusLabel"] = @"Bonus",
                ["ResourceEffectLabel"] = @"Effet",
                ["ResourceStatModifiedLabel"] = @"Statistiques modifiées",
                ["ResourceVitalModifiedLabel"] = @"Vitalité modifiée",
                ["ScalingPercentage"] = @"Pourcentage d’échelonnement :",
                ["ScalingStat"] = @"Statistiques d’échelonnement :",
                ["SingleUse"] = @"Usage unique",
                ["Sold"] = @"Vendu",
                ["StatGrowthRange"] = @"{00} à {01}",
                ["TeachSpell"] = @"Enseigne le sort : {00}",
                ["Traded"] = @"Échangé",
                ["TwoHand"] = @"2M",
                ["UnknownEffect"] = @"Effet inconnu",
                ["UnknownItemType"] = @"Type inconnu",
                ["UnknownStat"] = @"Statistique inconnue",
                ["UnknownVital"] = @"Vital inconnu",
            },
            ["Keys"] = new JObject
            {
                ["KeyNameWithModifier"] = @"{00} + {01}",
            },
            ["LoginWindow"] = new JObject
            {
                ["Back"] = @"Retour",
                ["ForgotPassword"] = @"Mot de passe oublié ?",
                ["Login"] = @"Connexion",
                ["Password"] = @"Mot de passe",
                ["SavePassword"] = @"Enregistrer le mot de passe",
                ["Title"] = @"Connexion",
                ["Username"] = @"Nom d’utilisateur",
            },
            ["Main"] = new JObject
            {
                ["GameName"] = @"Intersect",
            },
            ["MainMenu"] = new JObject
            {
                ["Credits"] = @"Crédits",
                ["Exit"] = @"Quitter",
                ["Login"] = @"Connexion",
                ["Register"] = @"S’inscrire",
                ["Settings"] = @"Paramètres",
                ["SettingsTooltip"] = @"",
                ["Start"] = @"Démarrer",
                ["Title"] = @"Menu principal",
            },
            ["Settings"] = new JObject
            {
                ["Apply"] = @"Appliquer",
                ["AudioSettingsTab"] = @"Audio",
                ["AutoCloseWindows"] = @"Fermer automatiquement les fenêtres",
                ["AutoToggleChatLog"] = @"Basculer automatiquement la visibilité du journal de chat",
                ["Cancel"] = @"Annuler",
                ["EnableLighting"] = @"Activer les effets de lumière",
                ["FormatResolution"] = @"{00}x{01}",
                ["FormatZoom"] = @"{00}x",
                ["Fps120"] = @"120",
                ["Fps30"] = @"30",
                ["Fps60"] = @"60",
                ["Fps90"] = @"90",
                ["ShowFPSCounter"] = @"Afficher le compteur de FPS",
                ["ShowAchievementNotifications"] = @"Afficher les notifications de succès",
                ["ShowPingCounter"] = @"Afficher le compteur de ping",
                ["Fullscreen"] = @"Plein écran",
                ["GameSettingsTab"] = @"Jeu",
                ["InformationSettings"] = @"Informations",
                ["InterfaceSettings"] = @"Interface",
                ["ControlsTab"] = @"Contrôles",
                ["Language"] = @"Langue",
                ["LanguageReloadNotice"] = @"Certaines fenêtres doivent être rouvertes.",
                ["MusicVolume"] = @"Volume de musique : {00}%",
                ["SectionVolume"] = @"Volume",
                ["VolumeMusic"] = @"musique",
                ["VolumeSoundEffects"] = @"Effets sonores",
                ["Resolution"] = @"Résolution",
                ["ResolutionCustom"] = @"Résolution personnalisée",
                ["Restore"] = @"Restaurer les valeurs par défaut",
                ["SoundVolume"] = @"Volume sonore : {00}%",
                ["ShowExperienceAsPercentage"] = @"Afficher l’expérience en pourcentage",
                ["ShowFriendOverheadHpBar"] = @"Afficher la barre de PV au-dessus des amis",
                ["ShowFriendOverheadInformation"] = @"Afficher les informations au-dessus des amis",
                ["ShowGuildOverheadHpBar"] = @"Afficher la barre de PV au-dessus des membres de la guilde",
                ["ShowGuildOverheadInformation"] = @"Afficher les informations au-dessus des membres de la guilde",
                ["ShowHealthAsPercentage"] = @"Afficher la santé en pourcentage",
                ["ShowNpcOverheadHpBar"] = @"Afficher la barre de PV au-dessus des PNJ",
                ["ShowNpcOverheadInformation"] = @"Afficher les informations au-dessus des PNJ",
                ["ShowManaAsPercentage"] = @"Afficher le mana en pourcentage",
                ["ShowMyOverheadHpBar"] = @"Afficher ma barre de PV au-dessus",
                ["ShowMyOverheadInformation"] = @"Afficher mes informations au-dessus",
                ["ShowPartyOverheadHpBar"] = @"Afficher la barre de PV au-dessus des membres du groupe",
                ["ShowPartyOverheadInformation"] = @"Afficher les informations au-dessus des membres du groupe",
                ["ShowPlayerOverheadHpBar"] = @"Afficher la barre de PV au-dessus des joueurs",
                ["ShowPlayerOverheadInformation"] = @"Afficher les informations au-dessus des joueurs",
                ["SimplifiedEscapeMenu"] = @"Menu Échap simplifié",
                ["StickyTarget"] = @"Cible collante",
                ["FPS"] = @"FPS",
                ["TargetingSettings"] = @"Ciblage",
                ["AutoTurnToTarget"] = @"Tourner automatiquement vers la cible",
                ["AutoSoftRetargetOnSelfCast"] = @"Re-ciblage doux automatique lors d’un auto-lancement",
                ["AutoSoftRetargetOnSelfCastTooltip"] = @"Lorsque ceci est activé et qu’un ennemi est ciblé et qu’un sort amical à cible unique est utilisé, le sort sera lancé sur soi sans retirer la cible de l’ennemi.",
                ["Title"] = @"Paramètres",
                ["TypewriterText"] = @"Texte machine à écrire",
                ["UIScale"] = @"Échelle de l’UI",
                ["UnlimitedFps"] = @"Sans limite",
                ["VideoSettingsTab"] = @"Vidéo",
                ["Vsync"] = @"V-Sync",
                ["EnableScrollingWorldZoom"] = @"Activer le défilement pour changer l’échelle du monde en jeu",
                ["WorldScale"] = @"Échelle du monde",
                ["WorldScaleTooltip"] = @"L’échelle du monde est disponible uniquement après la connexion au serveur.",
            },
            ["Parties"] = new JObject
            {
                ["InFight"] = @"Vous êtes actuellement en combat !",
                ["InvitePrompt"] = @"{00} vous a invité à rejoindre son groupe. Acceptez-vous ?",
                ["Kick"] = @"Expulser {00}",
                ["KickLabel"] = @"expulser",
                ["Leader"] = @"Chef",
                ["LeaderTip"] = @"chef du groupe",
                ["Leave"] = @"Quitter le groupe",
                ["LeaveTip"] = @"quitter le groupe",
                ["Name"] = @"{00} - Niv. {01}",
                ["PartyInvite"] = @"Invitation de groupe",
                ["Title"] = @"groupe",
                ["Vital0"] = @"PV :",
                ["Vital0Value"] = @"{00} / {01}",
                ["Vital1"] = @"PM :",
                ["Vital1Value"] = @"{00} / {01}",
            },
            ["Achievements"] = new JObject
            {
                ["CategoryLabel"] = @"Catégorie : {00}",
                ["Completed"] = @"Succès terminé",
                ["CompletedNotification"] = @"Succès terminé : {00}",
                ["DifficultyLabel"] = @"Difficulté : {00}",
                ["FilterCompleted"] = @"Terminés",
                ["FilterInProgress"] = @"En cours",
                ["FilterPending"] = @"En attente",
                ["InProgress"] = @"Succès en cours",
                ["Pending"] = @"Succès en attente",
                ["Progress"] = @"Progression :",
                ["ProgressValue"] = @"{00}/{01}",
                ["ProgressValueSimple"] = @"{00}",
                ["RewardCurrency"] = @"Monnaie : {00}",
                ["RewardExperience"] = @"Expérience : {00}",
                ["RewardNone"] = @"Aucune récompense",
                ["RewardItem"] = @"{00}x {01}",
                ["RewardResource"] = @"{00}x {01}",
                ["RewardTitles"] = @"Titres : {00}",
                ["RewardsTitle"] = @"Récompenses",
                ["Title"] = @"Succès",
            },
            ["QuestLog"] = new JObject
            {
                ["Abandon"] = @"abandonner",
                ["AbandonPrompt"] = @"Êtes-vous sûr de vouloir abandonner la quête ""{00}"" ?",
                ["AbandonTitle"] = @"Abandonner la quête : {00}",
                ["Back"] = @"Retour",
                ["Completed"] = @"Quête terminée",
                ["CurrentTask"] = @"Tâche actuelle :",
                ["InProgress"] = @"Quête en cours",
                ["NotStarted"] = @"Quête non commencée",
                ["TaskItem"] = @"{00}/{01} {02}(s) collecté(s).",
                ["TaskNpc"] = @"{00}/{01} {02}(s) tué(s).",
                ["Title"] = @"Journal des quêtes",
            },
            ["QuestOffer"] = new JObject
            {
                ["Accept"] = @"Accepter",
                ["Decline"] = @"Refuser",
                ["Title"] = @"Offre de quête",
            },
            ["QuestRewardExp"] = new JObject
            {
                ["PlayerExpTooltip"] = @"EXP joueur",
                ["JobExpTooltip"] = @"EXP {0}",
                ["JobGenericTooltip"] = @"EXP de métier",
                ["GuildExpTooltip"] = @"EXP de guilde",
                ["FactionHonorTooltip"] = @"Honneur {0}",
                ["FactionHonorGenericTooltip"] = @"Honneur de faction",
                ["FactionNeutralName"] = @"Neutre",
                ["FactionSerolfName"] = @"Serolf",
                ["FactionNidrajName"] = @"Nidraj",
            },
            ["Regex"] = new JObject
            {
                ["Email"] = @"^(([\w-]+\.)+[\w-]+|([a-zA-Z]{1}|[\w-]{2,}))@((([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])){1}|([a-zA-Z]+[\w-]+\.)+[a-zA-Z]{2,4})$",
                ["Password"] = @"^[-_=\+`~!@#\$%\^&\*()\[\]{}\\|;\:'"",<\.>/\?a-zA-Z0-9]{4,64}$",
                ["Username"] = @"^[a-zA-Z0-9]{2,20}$",
            },
            ["Registration"] = new JObject
            {
                ["Back"] = @"Retour",
                ["ConfirmPassword"] = @"Confirmer le mot de passe :",
                ["Email"] = @"E-mail :",
                ["EmailInvalid"] = @"L’e-mail est invalide.",
                ["Password"] = @"Mot de passe :",
                ["PasswordMismatch"] = @"Les mots de passe ne correspondent pas.",
                ["Register"] = @"S’inscrire",
                ["Title"] = @"Inscription",
                ["Username"] = @"Nom d’utilisateur :",
            },
            ["PasswordChange"] = new JObject
            {
                ["Back"] = @"Annuler",
                ["ConfirmNewPassword"] = @"Confirmer le nouveau mot de passe",
                ["ErrorNoResetCode"] = @"Veuillez saisir votre code de réinitialisation",
                ["ErrorNoOldPassword"] = @"Veuillez saisir votre ancien mot de passe",
                ["ErrorNoNewPassword"] = @"Veuillez saisir votre nouveau mot de passe",
                ["ErrorNoNewPasswordConfirmation"] = @"Veuillez confirmer votre nouveau mot de passe",
                ["AlertTitleError"] = @"Erreur !",
                ["InputLabelResetCode"] = @"Code de réinitialisation",
                ["InputLabelPassword"] = @"Ancien mot de passe",
                ["NewPassword"] = @"Nouveau mot de passe",
                ["Submit"] = @"Envoyer",
                ["AlertTitleSuccess"] = @"Succès !",
                ["Title"] = @"Réinitialiser le mot de passe",
            },
            ["Server"] = new JObject
            {
                ["Connecting"] = @"Connexion...",
                ["Failed"] = @"Erreur réseau",
                ["HandshakeFailure"] = @"Échec de la poignée de main",
                ["Offline"] = @"Hors ligne",
                ["Online"] = @"En ligne",
                ["ServerFull"] = @"Le serveur est plein",
                ["StatusLabel"] = @"État du serveur : {00}",
                ["Unknown"] = @"Inconnu",
                ["VersionMismatch"] = @"Version incompatible",
            },
            ["Shop"] = new JObject
            {
                ["Title"] = @"Boutique",
                ["BuyItem"] = @"Acheter un objet",
                ["BuyItemPrompt"] = @"Combien d’unités de {00} souhaitez-vous acheter ?",
                ["CannotSell"] = @"Cette boutique n’accepte pas cet objet !",
                ["Costs"] = @"Coûte {00} {01}",
                ["SellItem"] = @"Vendre un objet",
                ["SellItemPrompt"] = @"Combien d’unités de {00} souhaitez-vous vendre ?",
                ["SellPrompt"] = @"Voulez-vous vendre l’objet : {00} ?",
                ["SellsFor"] = @"Se vend pour {00} {01}",
                ["WontBuy"] = @"La boutique n’achètera pas cet objet",
            },
            ["SpellDescription"] = new JObject
            {
                ["Bound"] = @"Ne peut pas être désappris.",
                ["CastTime"] = @"Temps d’incantation :",
                ["Cooldown"] = @"Temps de recharge :",
                ["CooldownGroup"] = @"Groupe de recharge :",
                ["CritChance"] = @"Chance de critique :",
                ["CritMultiplier"] = @"Multiplicateur de critique :",
                ["DamageType"] = @"Type de dégâts :",
                ["Distance"] = @"Distance :",
                ["DoT"] = @"Dégâts sur la durée",
                ["Duration"] = @"Durée :",
                ["Effect"] = @"Effet :",
                ["Friendly"] = @"Sort de soutien",
                ["HoT"] = @"Soin sur la durée",
                ["IgnoreConsumedResourceBlock"] = @"Ignore les ressources consommées",
                ["IgnoreCooldownReduction"] = @"Ignore la réduction du temps de recharge",
                ["IgnoreGlobalCooldown"] = @"Ignore le temps de recharge global",
                ["IgnoreMapBlock"] = @"Ignore les blocs de carte",
                ["IgnoreResourceBlock"] = @"Ignore les ressources actives",
                ["IgnoreZDimension"] = @"Ignore les différences de hauteur",
                ["Instant"] = @"Instantané",
                ["Level"] = @"Niveau :",
                ["Multiplier"] = @"{00}x",
                ["Percentage"] = @"{00}%",
                ["RegularAndPercentage"] = @"{00} + {01}%",
                ["ScalingPercentage"] = @"Pourcentage d’échelonnement :",
                ["ScalingStat"] = @"Statistiques d’échelonnement :",
                ["StatBuff"] = @"Bonus de statistiques",
                ["Tick"] = @"Intervalles :",
                ["Tiles"] = @"{00} tuiles",
                ["Unfriendly"] = @"Sort nuisible",
            },
            ["Spells"] = new JObject
            {
                ["ForgetSpell"] = @"Oublier le sort",
                ["ForgetSpellPrompt"] = @"Êtes-vous sûr de vouloir oublier {00} ?",
                ["Title"] = @"Sorts",
                ["EmptySlot"] = @"Emplacement de sort vide",
            },
            ["Trading"] = new JObject
            {
                ["Accept"] = @"Accepter",
                ["InFight"] = @"Vous êtes actuellement en combat !",
                ["OfferItem"] = @"Proposer un objet",
                ["OfferItemPrompt"] = @"Combien d’unités de {00} souhaitez-vous proposer ?",
                ["Pending"] = @"En attente",
                ["RequestPrompt"] = @"{00} vous a invité à échanger des objets. Acceptez-vous ?",
                ["RevokeItem"] = @"Retirer l’objet",
                ["RevokeItemPrompt"] = @"Combien d’unités de {00} souhaitez-vous retirer ?",
                ["TheirOffer"] = @"Leur offre :",
                ["Title"] = @"Échange avec {00}",
                ["TradeRequest"] = @"Invitation d’échange",
                ["Value"] = @"Valeur : {00}",
                ["YourOffer"] = @"Votre offre :",
                ["OtherPlayer"] = @"L’autre joueur a accepté l’échange.",
                ["TooFast"] = @"Vous envoyez des messages trop rapidement ! Veuillez patienter.",
                ["Muted"] = @"Vous ne pouvez pas envoyer de messages d’échange en étant en sourdine.",
                ["Format"] = @"[Échange] {00} : {01}",
                ["SELL"] = @"[VENDRE]",
                ["BUY"] = @"[ACHETER]",
            },
            ["EscapeMenu"] = new JObject
            {
                ["CharacterSelect"] = @"Personnages",
                ["Close"] = @"Fermer",
                ["ExitToDesktop"] = @"Bureau",
                ["Logout"] = @"Déconnexion",
                ["Settings"] = @"Paramètres",
                ["Title"] = @"Menu",
            },
            ["Numbers"] = new JObject
            {
                ["Billions"] = @"b",
                ["Comma"] = @",",
                ["Decimal"] = @".",
                ["Millions"] = @"m",
                ["Thousands"] = @"k",
            },
            ["Update"] = new JObject
            {
                ["Checking"] = @"Recherche de mises à jour, veuillez patienter.",
                ["Done"] = @"Mise à jour terminée ! Lancement du jeu.",
                ["Error"] = @"Erreur de mise à jour ! Consultez les journaux pour plus d’informations.",
                ["FilesRemaining"] = @"{00} fichiers restants",
                ["PercentComplete"] = @"{00}%",
                ["RemainingSize"] = @"{00} restants",
                ["Restart"] = @"Mise à jour terminée ! Redémarrez {00} pour jouer.",
                ["Updating"] = @"Téléchargement des mises à jour, veuillez patienter.",
            },
            ["GameWindow"] = new JObject
            {
                ["EntityNameAndLevel"] = @"{00} [Niv. {01}]",
            },
        };
    }
}
