using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Intersect.Client.Localization;

internal static partial class ClientLocalizationOverrides
{
    private static partial void AddPtOverrides(IDictionary<string, JObject> overrides)
    {
        overrides["pt"] = new JObject
        {
            ["AdminWindow"] = new JObject
            {
                ["Access"] = "Acesso",
                ["Access1"] = "Moderador",
                ["Access2"] = "Administrador",
                ["AdditionalInterfaces"] = "Ferramentas Adicionais",
                ["AllowOverflow"] = "Permitir estouro do banco",
                ["Appearance"] = "Aparência",
                ["Ban"] = "Proibição",
                ["BanCaption"] = "Banir {00}",
                ["BanPrompt"] = "Banir {00} não permitirá que eles acessem este jogo pelo período que você definir!",
                ["Face"] = "Cara",
                ["GiveItem"] = "Dê item",
                ["Item"] = "Artigo",
                ["ItemManagement"] = "Itens",
                ["KickPlayer"] = "Chute",
                ["KillPlayer"] = "Matar",
                ["LeaveInstance"] = "Sair da instância",
                ["MailAttachmentItem"] = "Anexo {00} item",
                ["MailAttachmentQuantity"] = "Anexo {00} quantidade",
                ["MailBroadcast"] = "Transmissão de correio",
                ["MailMessage"] = "Mensagem",
                ["MailOnlineOnly"] = "Somente jogadores on-line",
                ["MailSend"] = "Enviar e-mail",
                ["MailSubject"] = "Assunto",
                ["MapList"] = "Lista de mapas",
                ["Mute"] = "Mudo",
                ["MuteCaption"] = "Silenciar {00}",
                ["MutePrompt"] = "Silenciar {00} não permitirá que eles conversem no jogo durante o tempo que você definir!",
                ["Name"] = "Nome",
                ["NamePlaceholder"] = "Nome do jogador",
                ["None"] = "Nenhum",
                ["Quantity"] = "Quantidade",
                ["QuickActions"] = "Ações rápidas",
                ["ReserveSpawn"] = "Reservar spawn para o jogador",
                ["SetFace"] = "Definir rosto",
                ["SetPower"] = "Definir potência",
                ["SetSprite"] = "Definir Sprite",
                ["SortMapList"] = "Classificar lista de mapas",
                ["SortMapListTooltip"] = "Ordene os mapas em uma hierarquia simples em ordem alfanumérica de acordo com a localidade do computador.",
                ["SpawnItem"] = "Item de geração",
                ["Sprite"] = "Sprite:",
                ["Title"] = "Administração",
                ["Unban"] = "Desbanir",
                ["UnbanCaption"] = "Desbanir {00}",
                ["UnbanPrompt"] = "Tem certeza de que deseja cancelar o banimento de {00}?",
                ["Unmute"] = "Ativar som",
                ["UnmuteCaption"] = "Ativar som {00}",
                ["UnmutePrompt"] = "Tem certeza de que deseja ativar o som de {00}?",
                ["WarpMeToPlayer"] = "Me deforme para",
                ["WarpPlayerToMe"] = "Warp para mim",
            },
            ["Alerts"] = new JObject
            {
                ["FallbackTitle"] = "Alerta",
                ["Titles"] = new JObject
                {
                    ["AlertType.Error"] = "Erro",
                    ["AlertType.Warning"] = "Aviso",
                },
            },
            ["BagContextMenu"] = new JObject
            {
                ["Withdraw"] = "Retirar {00}",
            },
            ["Bags"] = new JObject
            {
                ["RetrieveItem"] = "Recuperar item",
                ["RetrieveItemPrompt"] = "Quantos/much {00} você gostaria de recuperar?",
                ["StoreItem"] = "Armazenar item",
                ["StoreItemPrompt"] = "Quantos/much {00} você gostaria de armazenar?",
                ["Title"] = "Bolsa",
            },
            ["BanMute"] = new JObject
            {
                ["Cancel"] = "Cancelar",
                ["Duration"] = "Duração:",
                ["FiveDays"] = "5 dias",
                ["Forever"] = "Indefinidamente",
                ["FourDays"] = "4 dias",
                ["IncludeIp"] = "Incluir IP:",
                ["Okay"] = "Ok",
                ["OneDay"] = "1 dia",
                ["OneMonth"] = "1 mês",
                ["OneWeek"] = "1 semana",
                ["OneYear"] = "1 ano",
                ["Reason"] = "Razão:",
                ["SixMonths"] = "6 meses",
                ["ThreeDays"] = "3 dias",
                ["TwoDays"] = "2 dias",
                ["TwoMonths"] = "2 meses",
                ["TwoWeeks"] = "2 semanas",
            },
            ["Bank"] = new JObject
            {
                ["All"] = "Todos",
                ["BankValue"] = "Valor bancário: {00}",
                ["BankValueFull"] = "{00} Moedas Globais",
                ["DepositItem"] = "Item de depósito",
                ["DepositItemPrompt"] = "Quantos/much {00} você gostaria de depositar?",
                ["NoSpace"] = "Não há mais espaço no seu banco para esse item!",
                ["Sort"] = "Classificar",
                ["Title"] = "Banco",
                ["WithdrawItem"] = "Retirar item",
                ["WithdrawItemNoSpace"] = "Não há mais espaço em seu inventário para esse item!",
                ["WithdrawItemPrompt"] = "Quantos/much {00} você gostaria de sacar?",
            },
            ["BankContextMenu"] = new JObject
            {
                ["Withdraw"] = "Retirar {00}",
            },
            ["Bestiary"] = new JObject
            {
                ["AggressiveLabel"] = "Agressivo: {0}",
                ["FleeHpLabel"] = "Fugir HP%: {0}%",
                ["Locked"] = "Bloqueado",
                ["LockedInfo"] = "🔒 Informações bloqueadas.",
                ["LockedKills"] = "🔒 Derrota {0}/{1} vezes para desbloquear.",
                ["LorePlaceholder"] = "(Aqui você pode inserir um sistema de descrições opcionais para NPC)",
                ["MovementLabel"] = "Movimento: {0}",
                ["No"] = "Não",
                ["SearchPlaceholder"] = "Buscar...",
                ["SectionBehavior"] = "Comportamento",
                ["SectionDrops"] = "Gotas",
                ["SectionLore"] = "História",
                ["SectionSpells"] = "Hechizos",
                ["SectionStats"] = "Estatísticas",
                ["SwarmLabel"] = "Enxame: {0}",
                ["Title"] = "Bestiário",
                ["UnlockNotice"] = "{1} desbloqueado para {0}",
                ["Unlocked"] = "Desbloqueado",
                ["Yes"] = "Sim",
            },
            ["Breaking"] = new JObject
            {
                ["Break"] = "Pausa",
                ["BreakFail"] = "O item não pôde ser desmontado.",
                ["BreakSuccess"] = "O item foi desmontado com sucesso.",
                ["Close"] = "Fechar",
                ["ConfirmBreak"] = "Tem certeza de que deseja desmontar este item?",
                ["ItemLocked"] = "Este item não pode ser dividido.",
                ["NoItemSelected"] = "Nenhum item selecionado para quebrar!",
                ["NothingToGain"] = "Quebrar este item não produz materiais.",
                ["ResultItems"] = "Resultados possíveis",
                ["SelectedItem"] = "Item selecionado",
                ["Title"] = "Quebrar itens",
                ["WindowTitle"] = "Desmontagem de itens",
            },
            ["Character"] = new JObject
            {
                ["Agility"] = "Agilidade:",
                ["AttackSpeed"] = "Velocidade de Ataque: {00}s",
                ["BasicAttackDamage"] = "Dano Básico: {00} | Verdadeiro: {01}-{02}",
                ["CooldownReduction"] = "Redução do tempo de espera: {00}%",
                ["CriticalChance"] = "Chance Crítica: {00}%",
                ["Equipment"] = "Equipamento:",
                ["ExtraBuffs"] = "Bônus extras",
                ["ExtraExp"] = "Bônus EXP: {00}%",
                ["FlatCures"] = "Bônus de cura: {00}",
                ["FlatDamage"] = "Bônus de dano: {00}",
                ["HealthRegen"] = "Regeneração de Saúde: {00}%",
                ["LevelAndClass"] = "Nível: {00}, Classe: {01}",
                ["Lifesteal"] = "Roubo de vida: {00}%",
                ["Luck"] = "Sorte: {00}%",
                ["ManaRegen"] = "Regeneração de Mana: {00}%",
                ["Manasteal"] = "Manasteal: {00}%",
                ["Points"] = "Pontos: {00}",
                ["StatLabelValue"] = "{00}: {01}",
                ["Stats"] = "Estatísticas:",
                ["Tenacity"] = "Tenacidade: {00}%",
                ["Title"] = "Informações do personagem",
            },
            ["CharacterCreation"] = new JObject
            {
                ["Back"] = "Voltar",
                ["Class"] = "Classe",
                ["Create"] = "Criar",
                ["Female"] = "Feminino",
                ["Gender"] = "Gênero",
                ["Hint"] = "Personalizar",
                ["Hint2"] = "Seu personagem",
                ["InvalidName"] = "O nome do personagem é inválido. Use caracteres alfanuméricos com comprimento entre 2 e 20.",
                ["Male"] = "Masculino",
                ["Name"] = "Nome",
                ["Title"] = "Crie um novo personagem",
            },
            ["CharacterSelection"] = new JObject
            {
                ["ChangePassword"] = "Alterar senha",
                ["Delete"] = "Excluir",
                ["DeletePrompt"] = "Tem certeza de que deseja excluir {00}? Esta ação é irreversível!",
                ["DeleteTitle"] = "Excluir {00}",
                ["Empty"] = "Slot de personagem vazio",
                ["Info"] = "Nível: {00}, Classe: {01}",
                ["Logout"] = "Sair",
                ["Name"] = "{00}",
                ["New"] = "Novo",
                ["Play"] = "Jogar",
                ["Title"] = "Selecione um personagem para interpretar",
            },
            ["ChatContextMenu"] = new JObject
            {
                ["FriendInvite"] = "Enviar solicitação de amizade para {00}",
                ["GuildInvite"] = "Convide {00} para a Guilda",
                ["PM"] = "Enviar mensagem privada para {00}",
                ["PartyInvite"] = "Convide {00} para a festa",
            },
            ["Chatbox"] = new JObject
            {
                ["Channel"] = "Canal:",
                ["ChannelAdmin"] = "administrador",
                ["Channels"] = new JObject
                {
                    ["0"] = "locais",
                    ["1"] = "mundial",
                    ["2"] = "festa",
                    ["3"] = "guilda",
                    ["4"] = "comércio",
                },
                ["ChatTabButtons"] = new JObject
                {
                    ["ChatboxTab.All"] = "Todos",
                    ["ChatboxTab.Global"] = "Globais",
                    ["ChatboxTab.Guild"] = "Guilda",
                    ["ChatboxTab.Local"] = "locais",
                    ["ChatboxTab.Party"] = "Festa",
                    ["ChatboxTab.System"] = "Sistema",
                    ["ChatboxTab.Trade"] = "Comércio",
                },
                ["ClearLogButtonToolTip"] = "Limpar mensagens de registro de bate-papo",
                ["EnterChat"] = "Clique aqui para conversar.",
                ["EnterChat1"] = "Pressione '{00}' para conversar.",
                ["EnterChat2"] = "Pressione '{00}' ou '{01}' para conversar.",
                ["Send"] = "Enviar",
                ["Title"] = "Bate-papo",
                ["ToggleLogButtonToolTip"] = "Alternar visibilidade do registro de bate-papo",
                ["TooFast"] = "Você está conversando muito rápido!",
                ["UnableToCopy"] = "Parece que você não consegue copiar/paste nesta plataforma. Certifique-se de ter os pacotes 'xclip' ou 'wl-clipboard' instalados se estiver executando o Linux.",
            },
            ["Combat"] = new JObject
            {
                ["AttackWhileCastingDeny"] = "Você não pode atacar enquanto lança um feitiço.",
                ["Stats"] = new JObject
                {
                    ["Stat.Agility"] = "Agilidade",
                    ["Stat.Attack"] = "Ataque",
                    ["Stat.Defense"] = "Defesa",
                    ["Stat.Intelligence"] = "Inteligência",
                    ["Stat.Speed"] = "Velocidade",
                    ["Stat.Vitality"] = "Vitalidade",
                },
                ["WarningCharacterSelect"] = "Você está tentando sair durante o combate! Seu personagem permanecerá no jogo até o fim do combate. Tem certeza de que deseja sair agora?",
                ["WarningExitDesktop"] = "Você está tentando sair durante o combate! Seu personagem permanecerá no jogo até o fim do combate. Tem certeza de que deseja sair agora?",
                ["WarningLogout"] = "Você está tentando sair durante o combate! Seu personagem permanecerá no jogo até o fim do combate. Tem certeza de que deseja sair agora?",
                ["WarningTitle"] = "Aviso de Combate!",
            },
            ["Content"] = new JObject
            {
                ["Types"] = new JObject
                {
                    ["ContentType.Animation"] = "Animação",
                    ["ContentType.Entity"] = "Entidade",
                    ["ContentType.Face"] = "Cara",
                    ["ContentType.Fog"] = "Nevoeiro",
                    ["ContentType.Font"] = "Fonte",
                    ["ContentType.Image"] = "Imagem",
                    ["ContentType.Interface"] = "Interface (gui)",
                    ["ContentType.Item"] = "Artigo",
                    ["ContentType.Miscellaneous"] = "Diversos",
                    ["ContentType.Music"] = "Música",
                    ["ContentType.Paperdoll"] = "Boneca de papel",
                    ["ContentType.Resource"] = "Recurso",
                    ["ContentType.Shader"] = "Sombreador",
                    ["ContentType.Sound"] = "Som",
                    ["ContentType.Spell"] = "Feitiço",
                    ["ContentType.TextureAtlas"] = "Atlas de Textura",
                    ["ContentType.Tileset"] = "Conjunto de peças",
                },
            },
            ["Controls"] = new JObject
            {
                ["HotkeyXLabel"] = "Tecla de atalho {00}:",
                ["KeyDictionary"] = new JObject
                {
                    ["attackinteract"] = "Ataque/Interact:",
                    ["autotarget"] = "Alvo automático:",
                    ["block"] = "Bloco:",
                    ["enter"] = "Bate-papo:",
                    ["holdtozoomin"] = "Segure para ampliar:",
                    ["holdtozoomout"] = "Segure para diminuir o zoom:",
                    ["hotkey1"] = "Tecla de atalho 1:",
                    ["hotkey10"] = "Tecla de atalho 10:",
                    ["hotkey2"] = "Tecla de atalho 2:",
                    ["hotkey3"] = "Tecla de atalho 3:",
                    ["hotkey4"] = "Tecla de atalho 4:",
                    ["hotkey5"] = "Tecla de atalho 5:",
                    ["hotkey6"] = "Tecla de atalho 6:",
                    ["hotkey7"] = "Tecla de atalho 7:",
                    ["hotkey8"] = "Tecla de atalho 8:",
                    ["hotkey9"] = "Tecla de atalho 9:",
                    ["movedown"] = "Para baixo:",
                    ["moveleft"] = "Esquerda:",
                    ["moveright"] = "Certo:",
                    ["moveup"] = "Acima:",
                    ["nameof(Control.HoldToSoftRetargetOnSelfCast).ToLowerInvariant()"] = "Segure para redirecionar suavemente no autocast:",
                    ["nameof(Control.ToggleAutoSoftRetargetOnSelfCast).ToLowerInvariant()"] = "Alternar redirecionamento suave automático para autotransmissão:",
                    ["openadminpanel"] = "Abra o painel de administração:",
                    ["opencharacterinfo"] = "Abrir informações do personagem:",
                    ["opendebugger"] = "Abra o depurador:",
                    ["openfriends"] = "Abrir amigos:",
                    ["openguild"] = "Guilda aberta:",
                    ["openinventory"] = "Inventário aberto:",
                    ["openmenu"] = "Menu aberto:",
                    ["openparties"] = "Festas Abertas:",
                    ["openquests"] = "Missões abertas:",
                    ["opensettings"] = "Abra Configurações:",
                    ["openspells"] = "Feitiços abertos:",
                    ["pickup"] = "Retirar:",
                    ["screenshot"] = "Captura de tela:",
                    ["targetparty1"] = "Alvo Auto/Party 1:",
                    ["targetparty2"] = "Parte Alvo 2:",
                    ["targetparty3"] = "Parte Alvo 3:",
                    ["targetparty4"] = "Parte Alvo 4:",
                    ["targetparty5"] = "Parte Alvo 5:",
                    ["targetparty6"] = "Parte Alvo 6:",
                    ["targetparty7"] = "Parte Alvo 7:",
                    ["togglefullscreen"] = "Alternar tela cheia:",
                    ["togglegui"] = "Alternar interface:",
                    ["togglezoomin"] = "Alternar zoom:",
                    ["togglezoomout"] = "Alternar redução de zoom:",
                    ["turnaround"] = "Segure para virar:",
                },
                ["Listening"] = "Ouvindo",
            },
            ["Crafting"] = new JObject
            {
                ["Craft"] = "Artesanato 1",
                ["CraftAll"] = "Artesanato {00}",
                ["CraftChance"] = "Chance de falha: {00}%",
                ["CraftStop"] = "Pare",
                ["CraftingName"] = "Artesanato",
                ["CraftingTime"] = "Tempo de elaboração: {00}s",
                ["DestroyMaterialsChance"] = "Chance de destruir materiais: {00}%",
                ["Exp"] = "EXP: {00}",
                ["IncorrectResources"] = "Você não tem os recursos necessários para fabricar este item.",
                ["Ingredients"] = "Obrigatório:",
                ["Product"] = "Artesanato:",
                ["RecipeListEntry"] = "{00}) {01}",
                ["Recipes"] = "Receitas:",
            },
            ["Credits"] = new JObject
            {
                ["Back"] = "Voltar ao menu principal",
                ["Title"] = "Créditos",
            },
            ["Debug"] = new JObject
            {
                ["AssetsSearchPlaceholder"] = "Filtrar recursos...",
                ["ControlUnderCursor"] = "Controle sob o cursor",
                ["DrawDebugOutlines"] = "Desenhe contornos de depuração",
                ["Draws"] = "Empates",
                ["EnableLayoutHotReloading"] = "Ativar recarregamento dinâmico de layout experimental",
                ["EntitiesDrawn"] = "Entidades sorteadas",
                ["FormatTextureFromAtlas"] = "{00} (do atlas)",
                ["Fps"] = "FPS",
                ["FreePhysicalRAM"] = "RAM grátis (Físico)",
                ["FreeVRAM"] = "Grátis VRAM",
                ["FreeVirtualRAM"] = "RAM grátis (virtual)",
                ["IncludeTextNodesInHover"] = "Incluir nós de texto ao passar o mouse",
                ["InterfaceObjects"] = "Objetos de interface",
                ["KnownEntities"] = "Entidades conhecidas",
                ["KnownMaps"] = "Mapas conhecidos",
                ["LightsDrawn"] = "Luzes desenhadas",
                ["Map"] = "Mapa",
                ["MapsDrawn"] = "Mapas desenhados",
                ["Ping"] = "Pingar",
                ["ReloadAsset"] = "Recarregar ativo",
                ["RenderTargetAllocations"] = "Renderizar alocações de destino",
                ["SectionGPUAllocations"] = "GPU Alocações",
                ["SectionGPUStatistics"] = "GPU Estatísticas",
                ["SectionSystemStatistics"] = "Estatísticas do sistema",
                ["ShutdownServer"] = "Desligar servidor",
                ["ShutdownServerAndExit"] = "Desligar servidor e sair",
                ["TabLabelAssets"] = "Ativos",
                ["TabLabelInfo"] = "Informações",
                ["TabLabelSystem"] = "Sistema",
                ["TextureAllocations"] = "Alocações de textura",
                ["TextureCount"] = "Ativos de textura",
                ["Time"] = "Hora",
                ["Title"] = "Depurar",
                ["TitleX"] = "Depurar #{0}",
                ["TotalPhysicalRAM"] = "Total RAM (Físico)",
                ["TotalVRAM"] = "Total VRAM",
                ["TotalVirtualRAM"] = "Total RAM (Virtual)",
                ["UsedVRAM"] = "Usado VRAM",
                ["ViewClickedNodeInDebugger"] = "Ver nó clicado no depurador",
                ["ViewClickedNodeInDebuggerTooltip"] = "Segure Alt para desligar temporariamente (para que você possa desligar esta opção)",
            },
            ["Enchanting"] = new JObject
            {
                ["Chance"] = "Chance de sucesso",
                ["Close"] = "Fechar",
                ["Cost"] = "Custo de encantamento",
                ["Enchant"] = "Encantar",
                ["EnchantFail"] = "O encantamento falhou. Melhor sorte da próxima vez!",
                ["EnchantSuccess"] = "O item foi encantado com sucesso!",
                ["InsufficientCurrency"] = "Você não tem dinheiro suficiente para encantar este item.",
                ["MaxEnchantReached"] = "O item atingiu o nível máximo de encantamento!",
                ["NoItemSelected"] = "Nenhum item selecionado para encantamento!",
                ["Projection"] = "Projeção",
                ["SelectedItem"] = "Item selecionado",
                ["Title"] = "Encantamento de itens",
                ["UseAmulet"] = "Use amuleto protetor",
                ["WindowTitle"] = "Encantar Itens",
            },
            ["EntityBox"] = new JObject
            {
                ["Exp"] = "EXP:",
                ["ExpValue"] = "{00} / {01}",
                ["Level"] = "Nv. {00}",
                ["Map"] = "{00}",
                ["MaxLevel"] = "Nível máximo",
                ["NameAndLevel"] = "{00} {01}",
                ["Vital0"] = "HP:",
                ["Vital0Value"] = "{00} / {01}",
                ["Vital1"] = "MP:",
                ["Vital1Value"] = "{00} / {01}",
            },
            ["EntityContextMenu"] = new JObject
            {
                ["AddFriend"] = "Adicionar amigo",
                ["InspectPlayer"] = "Inspecionar jogador",
                ["InviteToGuild"] = "Convidar para Guilda",
                ["InviteToParty"] = "Convidar para festa",
                ["ManagePlayerShop"] = "Organizar minha loja",
                ["PrivateMessage"] = "Mensagem Privada",
                ["Trade"] = "Comércio",
            },
            ["Errors"] = new JObject
            {
                ["DisconnectionEvent"] = "Forneça esta mensagem ao seu administrador: {0}",
                ["DisplayNotSupported"] = "Configuração de exibição inválida!",
                ["DisplayNotSupportedError"] = "A resolução de tela cheia {00} não é suportada neste dispositivo!",
                ["HostNotFound"] = "DNS erro de resolução, informe isso ao administrador do jogo.",
                ["InvalidStateReturnToMainMenu"] = "Foi detectado um estado inválido e tivemos que retornar ao menu principal.",
                ["LoadFile"] = "Falha ao carregar um {00}. Por favor, envie ao administrador do jogo uma cópia do seu arquivo de log de erros no diretório logs.",
                ["LostConnection"] = "Conexão perdida com o servidor do jogo. Verifique se você está conectado à Internet e tente novamente!",
                ["NotConnected"] = "Não conectado ao servidor do jogo. Está on-line?",
                ["OpenAllLink"] = "https://goo.gl/Nbx6hx",
                ["OpenGlLink"] = "https://goo.gl/RSP3ts",
                ["PasswordInvalid"] = "A senha é inválida. Use caracteres alfanuméricos com comprimento entre 4 e 20.",
                ["ResourcesNotFound"] = "O diretório de recursos não foi encontrado! O Intersect será fechado agora.",
                ["Title"] = "Erro!",
                ["UsernameInvalid"] = "O nome de usuário é inválido. Use caracteres alfanuméricos com comprimento entre 2 e 20.",
            },
            ["EscapeMenu"] = new JObject
            {
                ["CharacterSelect"] = "Personagens",
                ["Close"] = "Fechar",
                ["ExitToDesktop"] = "Área de trabalho",
                ["Logout"] = "Sair",
                ["Settings"] = "Configurações",
                ["Title"] = "Cardápio",
            },
            ["EventWindow"] = new JObject
            {
                ["Continue"] = "Continuar",
            },
            ["ForgotPass"] = new JObject
            {
                ["Back"] = "Voltar",
                ["Disclaimer"] = "Se existir uma conta com o nome de usuário ou endereço de e-mail fornecido, um e-mail com um código de redefinição de senha será enviado para o endereço de e-mail associado à conta.",
                ["Submit"] = "Enviar",
                ["Title"] = "Redefinição de senha",
                ["UsernameOrEmailPlaceholder"] = "Nome de usuário ou endereço de e-mail",
            },
            ["Friends"] = new JObject
            {
                ["AddFriend"] = "Adicionar amigo",
                ["AddFriendPrompt"] = "Quem você gostaria de adicionar como amigo?",
                ["InFight"] = "Você está atualmente em uma luta!",
                ["Offline"] = "Off-line",
                ["RemoveFriend"] = "Remover amigo",
                ["RemoveFriendPrompt"] = "Deseja remover {00} da sua lista de amigos?",
                ["Request"] = "Pedido de amizade",
                ["RequestPrompt"] = "{00} enviou a você um pedido de amizade. Você aceita?",
                ["Title"] = "Amigos",
            },
            ["GameMenu"] = new JObject
            {
                ["Achievements"] = "Conquistas",
                ["Character"] = "Informações do personagem",
                ["Friends"] = "Amigos",
                ["Items"] = "Inventário",
                ["Jobs"] = "Empregos",
                ["Menu"] = "Abrir Menu",
                ["Party"] = "Festa",
                ["Quest"] = "Registro de missão",
                ["Spells"] = "Livro de feitiços",
            },
            ["GameWindow"] = new JObject
            {
                ["EntityNameAndLevel"] = "{00} [Nv. {01}]",
            },
            ["General"] = new JObject
            {
                ["FpsLabelFormat"] = "{0}fps",
                ["MapItemStackable"] = "{01} {00}",
                ["None"] = "Nenhum",
                ["PingLabelFormat"] = "{0}ms",
            },
            ["Guilds"] = new JObject
            {
                ["Add"] = "+",
                ["Bank"] = "{00} Banco da Guilda",
                ["Demote"] = "Rebaixar para {00}",
                ["DemotePrompt"] = "Tem certeza de que deseja rebaixar {00} para a classificação {01}?",
                ["DemoteTitle"] = "Rebaixar membro da guilda",
                ["Guild"] = "Guilda",
                ["GuildTip"] = "Envie a {00} um convite para sua guilda.",
                ["Invite"] = "Convidar",
                ["InviteAlreadyInGuild"] = "O jogador que você está tentando convidar já está em uma guilda ou tem um convite pendente.",
                ["InviteMemberPrompt"] = "Quem você gostaria de convidar para {00}?",
                ["InviteMemberTitle"] = "Convidar jogador",
                ["InviteRequestPrompt"] = "{00} gostaria de convidar você para se juntar à guilda deles, {01}. Você aceita?",
                ["InviteRequestPromptMissingGuild"] = "{00} gostaria de convidar você para se juntar à guilda deles. Você aceita?",
                ["InviteRequestTitle"] = "Convite da Guilda",
                ["Kick"] = "Chute",
                ["KickPrompt"] = "Tem certeza que quer chutar {00}?",
                ["KickTitle"] = "Expulsar membro da guilda",
                ["Leave"] = "Sair",
                ["LeavePrompt"] = "Tem certeza de que deseja sair da sua guilda?",
                ["LeaveTitle"] = "Sair da Guilda",
                ["NotAllowedDeposit"] = "Você não tem permissão para depositar itens no banco da guilda de {00}.",
                ["NotAllowedSwap"] = "Você não tem permissão para trocar itens no banco da guilda de {00}.",
                ["NotAllowedWithdraw"] = "Você não tem permissão para retirar dinheiro do banco da guilda de {00}.",
                ["NotInGuild"] = "Você não está atualmente em uma guilda!",
                ["OfflineListEntry"] = "[{00}] {01} - {02}",
                ["OnlineListEntry"] = "[{00}] {01} - {02}",
                ["PM"] = "PM",
                ["Promote"] = "Promover para {00}",
                ["PromotePrompt"] = "Tem certeza de que deseja promover {00} para a classificação {01}?",
                ["PromoteTitle"] = "Promover membro da guilda",
                ["Tooltip"] = "Nv. {00} {01}",
                ["Transfer"] = "Transferência",
                ["TransferTitle"] = "Guilda de transferência",
                ["TransferToMemberPrompt"] = "Esta ação transferirá completamente toda a propriedade de sua guilda para \\c{{#80ff80}}{00}\\c{{}} e você perderá sua classificação de \\c{{#ff9f40}}{01}\\c{{}}.\n\nSe você tem certeza de que deseja entregar sua guilda, digite '\\c{{#ff8080}}{02}\\c{{}}' abaixo.",
            },
            ["InputBox"] = new JObject
            {
                ["Cancel"] = "Cancelar",
                ["No"] = "Não",
                ["Okay"] = "Ok",
                ["Yes"] = "Sim",
            },
            ["Internals"] = new JObject
            {
                ["Alignment"] = "Alinhamento",
                ["AutoSizeToContentHeight"] = "AutoSizeToContentHeight",
                ["AutoSizeToContentHeightOnChildResize"] = "ASTH no redimensionamento filho",
                ["AutoSizeToContentWidth"] = "AutoSizeToContentWidth",
                ["AutoSizeToContentWidthOnChildResize"] = "ASTW no redimensionamento filho",
                ["AutoSizeToContents"] = "AutoSizeToContents",
                ["Bounds"] = "Limites",
                ["Color"] = "Cor",
                ["ColorOverride"] = "Substituição de cores",
                ["CoordinateX"] = "X",
                ["CoordinateY"] = "S",
                ["CoordinateZ"] = "Z",
                ["Dock"] = "Doca",
                ["ExperimentalFeatureTooltip"] = "Este recurso é experimental e pode causar problemas quando ativado.",
                ["Font"] = "Fonte",
                ["FontSize"] = "Tamanho da fonte",
                ["GlobalItem"] = "{00} Global",
                ["InnerBounds"] = "Limites Internos",
                ["IsDisabled"] = "Está desativado",
                ["IsDisabledByTree"] = "IsDisabledByTree",
                ["IsVisibleInParent"] = "IsVisibleInParent",
                ["IsVisibleInTree"] = "ÉVisívelInTree",
                ["LocalItem"] = "Local {00}",
                ["Margin"] = "Margem",
                ["Name"] = "Nome",
                ["NotApplicable"] = "N/A",
                ["OuterBounds"] = "Limites Externos",
                ["Padding"] = "Preenchimento",
                ["ResolutionXByY"] = "{0}x{1}",
                ["TextAlign"] = "Alinhamento de texto",
                ["Type"] = "Tipo",
            },
            ["Inventory"] = new JObject
            {
                ["All"] = "Todos",
                ["DropItemPrompt"] = "Quantas unidades de {00} você gostaria de descartar?",
                ["DropItemTitle"] = "Soltar item",
                ["DropPrompt"] = "Deseja descartar o item: {00}?",
                ["EquippedSymbol"] = "E",
                ["Sort"] = "Classificar",
                ["Title"] = "Inventário",
            },
            ["ItemContextMenu"] = new JObject
            {
                ["Bag"] = "Bolsa {00}",
                ["Bank"] = "Banco {00}",
                ["Cast"] = "Elenco {00}",
                ["Drop"] = "Soltar {00}",
                ["Equip"] = "Equipar {00}",
                ["Learn"] = "Aprenda {00}",
                ["Open"] = "Abra {00}",
                ["Sell"] = "Vender {00}",
                ["Show"] = "Mostrar {00}",
                ["Trade"] = "Oferta {00}",
                ["Unequip"] = "Desequipar {00}",
                ["Use"] = "Usar {00}",
            },
            ["ItemDescription"] = new JObject
            {
                ["Amount"] = "Quantidade:",
                ["AttackSpeed"] = "Velocidade de Ataque:",
                ["AttackSpeedComparison"] = "Velocidade de Ataque: {00} ({01})",
                ["BagSlots"] = "Slots de bolsa:",
                ["Bagged"] = "Ensacado",
                ["Banked"] = "Bancado",
                ["BaseDamage"] = "Dano Básico:",
                ["BaseDamageType"] = "Tipo de dano:",
                ["BlockAbsorption"] = "Absorção de bloco:",
                ["BlockAmount"] = "Quantidade do bloco:",
                ["BlockChance"] = "Chance de bloqueio:",
                ["BonusEffects"] = new JObject
                {
                    ["0"] = "Configurações",
                    ["1"] = "Redução do tempo de espera:",
                    ["10"] = "Anticrítico:",
                    ["11"] = "Penetração de Armadura:",
                    ["12"] = "Redução de danos:",
                    ["13"] = "Reflexão de dano:",
                    ["14"] = "Bônus de dano:",
                    ["15"] = "Bônus de cura:",
                    ["2"] = "Roubo de vida:",
                    ["3"] = "Tenacidade:",
                    ["4"] = "Sorte:",
                    ["5"] = "Experiência bônus:",
                    ["6"] = "Manasteal:",
                    ["7"] = "Precisão:",
                    ["8"] = "Evasão:",
                    ["9"] = "Chance Crítica:",
                },
                ["CastSpell"] = "Lança feitiço: {00}",
                ["ConsumableTypes"] = new JObject
                {
                    ["0"] = "Restaura HP:",
                    ["1"] = "Restaura MP:",
                    ["2"] = "Experiência em bolsas:",
                    ["3"] = "Aplica efeito:",
                },
                ["CritChance"] = "Chance Crítica:",
                ["CritMultiplier"] = "Multiplicador Crítico:",
                ["DamageTypes"] = new JObject
                {
                    ["0"] = "Físico",
                    ["1"] = "Magia",
                    ["2"] = "Verdadeiro",
                },
                ["Description"] = "{00}",
                ["DropOnDeath"] = "Chance de queda ao morrer:",
                ["Dropped"] = "Caiu",
                ["GuildBanked"] = "Guilda bancada",
                ["ItemLimits"] = "Não pode ser {00}",
                ["ItemSubtypes"] = new JObject
                {
                    ["Common"] = "Comum",
                    ["Epic"] = "Épico",
                    ["Legendary"] = "Lendário",
                    ["None"] = "Nenhum",
                    ["Rare"] = "Raro",
                    ["Uncommon"] = "Incomum",
                },
                ["ItemTypes"] = new JObject
                {
                    ["0"] = "Nenhum",
                    ["1"] = "Equipamento",
                    ["2"] = "Consumível",
                    ["3"] = "Moeda",
                    ["4"] = "Feitiço",
                    ["5"] = "Especial",
                    ["6"] = "Bolsa",
                    ["7"] = "Recurso",
                },
                ["Multiplier"] = "{00}x",
                ["Percentage"] = "{00}%",
                ["RegularAndPercentage"] = "{00} + {01}%",
                ["ResourceBonusLabel"] = "Bônus",
                ["ResourceEffectLabel"] = "Efeito",
                ["ResourceStatModifiedLabel"] = "Estatística modificada",
                ["ResourceVitalModifiedLabel"] = "Vital Modificado",
                ["ScalingPercentage"] = "Porcentagem de escala:",
                ["ScalingStat"] = "Estatística de escala:",
                ["SingleUse"] = "Uso único",
                ["Sold"] = "Vendido",
                ["StatCounts"] = new JObject
                {
                    ["0"] = "Ataque:",
                    ["1"] = "Inteligência:",
                    ["2"] = "Defesa:",
                    ["3"] = "Vitalidade:",
                    ["4"] = "Velocidade:",
                    ["5"] = "Agilidade:",
                },
                ["StatGrowthRange"] = "{00} a {01}",
                ["Stats"] = new JObject
                {
                    ["0"] = "Ataque",
                    ["1"] = "Inteligência",
                    ["2"] = "Defesa",
                    ["3"] = "Vitalidade",
                    ["4"] = "Velocidade",
                    ["5"] = "Agilidade",
                },
                ["TeachSpell"] = "Ensina Feitiço: {00}",
                ["Traded"] = "Negociado",
                ["TwoHand"] = "2H",
                ["UnknownEffect"] = "Efeito desconhecido",
                ["UnknownItemType"] = "Tipo desconhecido",
                ["UnknownStat"] = "Estatística desconhecida",
                ["UnknownVital"] = "Vital Desconhecido",
                ["Vitals"] = new JObject
                {
                    ["0"] = "HP:",
                    ["1"] = "MP:",
                },
                ["VitalsRegen"] = new JObject
                {
                    ["0"] = "HP Regeneração:",
                    ["1"] = "MP Regeneração:",
                },
            },
            ["Job"] = new JObject
            {
                ["Alchemy"] = "Alquimia",
                ["Blacksmith"] = "Ferreiro",
                ["Cooking"] = "Cozinhando",
                ["Crafting"] = "Artesanato",
                ["Exp"] = "EXP: ",
                ["ExpValue"] = "{0} / {1}",
                ["Farming"] = "Agricultura",
                ["Fishing"] = "Pesca",
                ["Hunting"] = "Caça",
                ["Jewerly"] = "joalheiro",
                ["Level"] = "Nível {0}",
                ["Lumberjack"] = "Lenhador",
                ["MaxLevel"] = "Nível máximo",
                ["Mining"] = "Mineração",
                ["None"] = "Nenhum",
                ["Tailoring"] = "Alfaiataria",
                ["Tanner"] = "Curtidor",
                ["job"] = "Janela de empregos",
            },
            ["Keys"] = new JObject
            {
                ["KeyDictionary"] = new JObject
                {
                    ["a"] = "A",
                    ["add"] = "Add",
                    ["alt"] = "Alt",
                    ["apps"] = "Apps",
                    ["attn"] = "Attn",
                    ["b"] = "B",
                    ["back"] = "Back",
                    ["browserback"] = "BrowserBack",
                    ["browserfavorites"] = "BrowserFavorites",
                    ["browserforward"] = "BrowserForward",
                    ["browserhome"] = "BrowserHome",
                    ["browserrefresh"] = "BrowserRefresh",
                    ["browsersearch"] = "BrowserSearch",
                    ["browserstop"] = "BrowserStop",
                    ["c"] = "C",
                    ["cancel"] = "Cancel",
                    ["capital"] = "Capital",
                    ["capslock"] = "CapsLock",
                    ["clear"] = "Clear",
                    ["control"] = "Control",
                    ["controlkey"] = "ControlKey",
                    ["crsel"] = "Crsel",
                    ["d"] = "D",
                    ["d0"] = "0",
                    ["d1"] = "1",
                    ["d2"] = "2",
                    ["d3"] = "3",
                    ["d4"] = "4",
                    ["d5"] = "5",
                    ["d6"] = "6",
                    ["d7"] = "7",
                    ["d8"] = "8",
                    ["d9"] = "9",
                    ["decimal"] = "Decimal",
                    ["delete"] = "Delete",
                    ["divide"] = "Divide",
                    ["down"] = "Down",
                    ["e"] = "E",
                    ["end"] = "End",
                    ["enter"] = "Enter",
                    ["eraseeof"] = "EraseEof",
                    ["escape"] = "Escape",
                    ["execute"] = "Execute",
                    ["exsel"] = "Exsel",
                    ["f"] = "F",
                    ["f1"] = "F1",
                    ["f10"] = "F10",
                    ["f11"] = "F11",
                    ["f12"] = "F12",
                    ["f13"] = "F13",
                    ["f14"] = "F14",
                    ["f15"] = "F15",
                    ["f16"] = "F16",
                    ["f17"] = "F17",
                    ["f18"] = "F18",
                    ["f19"] = "F19",
                    ["f2"] = "F2",
                    ["f20"] = "F20",
                    ["f21"] = "F21",
                    ["f22"] = "F22",
                    ["f23"] = "F23",
                    ["f24"] = "F24",
                    ["f3"] = "F3",
                    ["f4"] = "F4",
                    ["f5"] = "F5",
                    ["f6"] = "F6",
                    ["f7"] = "F7",
                    ["f8"] = "F8",
                    ["f9"] = "F9",
                    ["finalmode"] = "FinalMode",
                    ["g"] = "G",
                    ["h"] = "H",
                    ["hanguelmode"] = "HanguelMode",
                    ["hangulmode"] = "HangulMode",
                    ["hanjamode"] = "HanjaMode",
                    ["help"] = "Help",
                    ["home"] = "Home",
                    ["i"] = "I",
                    ["imeaccept"] = "IMEAccept",
                    ["imeaceept"] = "IMEAceept",
                    ["imeconvert"] = "IMEConvert",
                    ["imemodechange"] = "IMEModeChange",
                    ["imenonconvert"] = "IMENonconvert",
                    ["insert"] = "Insert",
                    ["j"] = "J",
                    ["junjamode"] = "JunjaMode",
                    ["k"] = "K",
                    ["kanamode"] = "KanaMode",
                    ["kanjimode"] = "KanjiMode",
                    ["keycode"] = "KeyCode",
                    ["l"] = "L",
                    ["launchapplication1"] = "LaunchApplication1",
                    ["launchapplication2"] = "LaunchApplication2",
                    ["launchmail"] = "LaunchMail",
                    ["lbutton"] = "Left Mouse",
                    ["lcontrolkey"] = "L Control",
                    ["left"] = "Left",
                    ["linefeed"] = "LineFeed",
                    ["lmenu"] = "L Alt",
                    ["lshiftkey"] = "L Shift",
                    ["lwin"] = "LWin",
                    ["m"] = "M",
                    ["mbutton"] = "Middle Mouse",
                    ["medianexttrack"] = "MediaNextTrack",
                    ["mediaplaypause"] = "MediaPlayPause",
                    ["mediaprevioustrack"] = "MediaPreviousTrack",
                    ["mediastop"] = "MediaStop",
                    ["menu"] = "Menu",
                    ["modifiers"] = "Modifiers",
                    ["multiply"] = "Multiply",
                    ["n"] = "N",
                    ["next"] = "Next",
                    ["noname"] = "NoName",
                    ["none"] = "None",
                    ["numlock"] = "NumLock",
                    ["numpad0"] = "NumPad 0",
                    ["numpad1"] = "NumPad 1",
                    ["numpad2"] = "NumPad 2",
                    ["numpad3"] = "NumPad 3",
                    ["numpad4"] = "NumPad 4",
                    ["numpad5"] = "NumPad 5",
                    ["numpad6"] = "NumPad 6",
                    ["numpad7"] = "NumPad 7",
                    ["numpad8"] = "NumPad 8",
                    ["numpad9"] = "NumPad 9",
                    ["o"] = "O",
                    ["oem1"] = "1",
                    ["oem102"] = "0",
                    ["oem2"] = "2",
                    ["oem3"] = "3",
                    ["oem4"] = "4",
                    ["oem5"] = "5",
                    ["oem6"] = "6",
                    ["oem7"] = "7",
                    ["oem8"] = "8",
                    ["oembackslash"] = "\\",
                    ["oemclear"] = "OemClear",
                    ["oemclosebrackets"] = "]",
                    ["oemcomma"] = ",",
                    ["oemminus"] = "-",
                    ["oemopenbrackets"] = "[",
                    ["oemperiod"] = ".",
                    ["oempipe"] = "|",
                    ["oemplus"] = "+",
                    ["oemquestion"] = "?",
                    ["oemquotes"] = "'",
                    ["oemsemicolon"] = "OemSemicolon",
                    ["oemtilde"] = "`",
                    ["p"] = "P",
                    ["pa1"] = "Pa1",
                    ["packet"] = "Packet",
                    ["pagedown"] = "Page Down",
                    ["pageup"] = "Page Up",
                    ["pause"] = "Pause",
                    ["play"] = "Play",
                    ["print"] = "Print",
                    ["printscreen"] = "PrintScreen",
                    ["prior"] = "Prior",
                    ["processkey"] = "ProcessKey",
                    ["q"] = "Q",
                    ["r"] = "R",
                    ["rbutton"] = "Right Mouse",
                    ["rcontrolkey"] = "R Control",
                    ["return"] = "Return",
                    ["right"] = "Right",
                    ["rmenu"] = "R Alt",
                    ["rshiftkey"] = "R Shift",
                    ["rwin"] = "RWin",
                    ["s"] = "S",
                    ["scroll"] = "Scroll",
                    ["select"] = "Select",
                    ["selectmedia"] = "SelectMedia",
                    ["separator"] = "Separator",
                    ["shift"] = "Shift",
                    ["shiftkey"] = "ShiftKey",
                    ["sleep"] = "Sleep",
                    ["snapshot"] = "Snapshot",
                    ["space"] = "Space",
                    ["subtract"] = "Subtract",
                    ["t"] = "T",
                    ["tab"] = "Tab",
                    ["u"] = "U",
                    ["up"] = "Up",
                    ["v"] = "V",
                    ["volumedown"] = "VolumeDown",
                    ["volumemute"] = "VolumeMute",
                    ["volumeup"] = "VolumeUp",
                    ["w"] = "W",
                    ["x"] = "X",
                    ["xbutton1"] = "XButton1",
                    ["xbutton2"] = "XButton2",
                    ["y"] = "Y",
                    ["z"] = "Z",
                    ["zoom"] = "Zoom",
                },
                ["KeyNameWithModifier"] = "{00} + {01}",
            },
            ["LoginWindow"] = new JObject
            {
                ["Back"] = "Voltar",
                ["ForgotPassword"] = "Esqueceu a senha?",
                ["Login"] = "Entrar",
                ["Password"] = "Senha",
                ["SavePassword"] = "Salvar senha",
                ["Title"] = "Entrar",
                ["Username"] = "Nome de usuário",
            },
            ["MailBox"] = new JObject
            {
                ["additem"] = "Adicionar item",
                ["attachments"] = "Anexos",
                ["close"] = "Fechar",
                ["closeButton"] = "❌ Fechar",
                ["itemnone"] = "Nenhum",
                ["mailitem"] = "Artigo",
                ["mailmsg"] = "Mensagem",
                ["mailquantity"] = "Quantidade",
                ["mails"] = "Correios",
                ["mailtitle"] = "Título",
                ["mailto"] = "Para",
                ["noSubject"] = "Sem assunto",
                ["send"] = "Enviar",
                ["sendMailButton"] = "📤 Enviar e-mail",
                ["sender"] = "Remetente",
                ["sendtitle"] = "Enviar e-mail",
                ["take"] = "Receber e-mail (excluir)",
                ["title"] = "Caixa de correio",
                ["unknownSender"] = "Remetente desconhecido",
            },
            ["Main"] = new JObject
            {
                ["GameName"] = "Cruzar",
            },
            ["MainMenu"] = new JObject
            {
                ["Credits"] = "Créditos",
                ["Exit"] = "Sair",
                ["Login"] = "Entrar",
                ["Register"] = "Cadastre-se",
                ["Settings"] = "Configurações",
                ["SettingsTooltip"] = "Configurações",
                ["Start"] = "Começar",
                ["Title"] = "Menu Principal",
            },
            ["MapItemWindow"] = new JObject
            {
                ["LootButton"] = "Saquear tudo",
                ["Title"] = "Saque",
            },
            ["Market"] = new JObject
            {
                ["Buy"] = "Comprar",
                ["all"] = "Todos",
                ["headerItemName"] = "Nome do item",
                ["headerPrice"] = "Preço",
                ["headerQuantity"] = "Quantidade",
                ["invalidItem"] = "⚠️ Item não encontrado no inventário.",
                ["invalidPrice"] = "❌ O preço deve ser maior que zero.",
                ["invalidQuantity"] = "❌ A quantidade deve ser maior que zero.",
                ["itemNameLabel"] = "Nome do item:",
                ["itemSubTypeLabel"] = "Subtipos",
                ["itemTypeLabel"] = "Tipo:",
                ["listedSuccessfully"] = "Listagem criada com sucesso!",
                ["maxPriceLabel"] = "Preço máximo:",
                ["minPriceLabel"] = "Preço mínimo:",
                ["noItemSelected"] = "⚠️ Nenhum item selecionado.",
                ["noResults"] = "❌ Nenhum resultado encontrado.",
                ["price"] = "Preço",
                ["priceOutOfRange"] = "❌ O preço deve estar entre {0} e {1} 🪙.",
                ["pricehint"] = "Preço sugerido: {0}",
                ["pricerange"] = "Intervalo sugerido: {0}/{1}",
                ["publish"] = "Publicar",
                ["publish_colon"] = "Publicar:",
                ["quantity"] = "Quantidade",
                ["quantityExceeds"] = "❌ Quantidade excede os itens disponíveis ({0}).",
                ["retryButton"] = "Tentar novamente",
                ["searchButton"] = "Pesquisar",
                ["selectitem"] = "Selecione um item do seu inventário",
                ["sellButton"] = "Vender",
                ["sellwindow"] = "Vender no Mercado",
                ["splitpackages"] = "Dividido em pacotes (1, 10, 100, 1000)",
                ["taxes_0"] = "🧾 Imposto estimado: 0",
                ["taxes_estimated"] = "🧾 Imposto estimado: {0}",
                ["windowTitle"] = "Mercado global",
            },
            ["Numbers"] = new JObject
            {
                ["Billions"] = "b",
                ["Comma"] = ",",
                ["Decimal"] = ".",
                ["Millions"] = "eu",
                ["Thousands"] = "k",
            },
            ["Parties"] = new JObject
            {
                ["InFight"] = "Você está lutando no momento!",
                ["InvitePrompt"] = "{00} convidou você para a festa deles. Você aceita?",
                ["Kick"] = "Chute {00}",
                ["KickLabel"] = "Chute",
                ["Leader"] = "Líder",
                ["LeaderTip"] = "Líder do Partido",
                ["Leave"] = "Sair da festa",
                ["LeaveTip"] = "Deixar dica",
                ["Name"] = "{00} - Nv. {01}",
                ["PartyInvite"] = "Convite para festa",
                ["Title"] = "Festa",
                ["Vital0"] = "HP:",
                ["Vital0Value"] = "{00} / {01}",
                ["Vital1"] = "MP:",
                ["Vital1Value"] = "{00} / {01}",
            },
            ["Achievements"] = new JObject
            {
                ["CategoryLabel"] = "Categoria: {00}",
                ["Completed"] = "Conquista concluída",
                ["CompletedNotification"] = "Conquista concluída: {00}",
                ["DifficultyLabel"] = "Dificuldade: {00}",
                ["FilterCompleted"] = "Concluídas",
                ["FilterInProgress"] = "Em progresso",
                ["FilterPending"] = "Pendentes",
                ["InProgress"] = "Conquista em progresso",
                ["Pending"] = "Conquista pendente",
                ["Progress"] = "Progresso:",
                ["ProgressValue"] = "{00}/{01}",
                ["ProgressValueSimple"] = "{00}",
                ["RewardCurrency"] = "Moeda: {00}",
                ["RewardExperience"] = "Experiência: {00}",
                ["RewardNone"] = "Sem recompensas",
                ["RewardItem"] = "{00}x {01}",
                ["RewardResource"] = "{00}x {01}",
                ["RewardTitles"] = "Títulos: {00}",
                ["RewardsTitle"] = "Recompensas",
                ["Title"] = "Conquistas",
            },
            ["PasswordChange"] = new JObject
            {
                ["AlertTitleError"] = "Erro!",
                ["AlertTitleSuccess"] = "Sucesso!",
                ["Back"] = "Cancelar",
                ["ConfirmNewPassword"] = "Confirme a nova senha",
                ["ErrorNoNewPassword"] = "Por favor digite sua nova senha",
                ["ErrorNoNewPasswordConfirmation"] = "Por favor confirme sua nova senha",
                ["ErrorNoOldPassword"] = "Por favor insira sua senha anterior",
                ["ErrorNoResetCode"] = "Por favor insira seu código de redefinição",
                ["InputLabelPassword"] = "Senha antiga",
                ["InputLabelResetCode"] = "Redefinir código",
                ["NewPassword"] = "Nova senha",
                ["ResponseMessages"] = new JObject
                {
                    ["PasswordResetResultType.InvalidRequest"] = "Não foi possível alterar a senha porque a solicitação era inválida.",
                    ["PasswordResetResultType.InvalidToken"] = "Não foi possível alterar a senha porque o token ou senha de redefinição era inválido ou expirou.",
                    ["PasswordResetResultType.NoUserFound"] = "Não foi possível alterar a senha porque o usuário não foi encontrado.",
                    ["PasswordResetResultType.Success"] = "Alterou a senha com sucesso.",
                    ["PasswordResetResultType.Unknown"] = "Ocorreu um erro desconhecido ao alterar a senha.",
                },
                ["Submit"] = "Enviar",
                ["Title"] = "Redefinição de senha",
            },
            ["PlayerShops"] = new JObject
            {
                ["BrowseStatus"] = "Selecione um item para começar.",
                ["BrowserAvailable"] = "Disponível: {0}",
                ["BrowserBuy"] = "Comprar",
                ["BrowserEmpty"] = "Esta loja não possui itens à venda.",
                ["BrowserOwner"] = "Proprietário: {0}",
                ["BrowserPriceEach"] = "Preço: {0} cada",
                ["BrowserTitle"] = "Loja de {0}",
                ["BrowserTotal"] = "Total: {0}",
                ["Cancel"] = "Cancelar",
                ["ClearSlot"] = "Limpar slot",
                ["CreateShop"] = "Entre no modo comerciante",
                ["CreatorTitle"] = "Loja de jogadores",
                ["DecorationLabel"] = "Decoração",
                ["EmptySlot"] = "Espaço vazio",
                ["ErrorInvalidInventory"] = "O item selecionado não está mais em seu inventário.",
                ["ErrorInvalidPrice"] = "O preço deve ser maior que zero.",
                ["ErrorInvalidQuantity"] = "A quantidade deve ser maior que zero.",
                ["ErrorMissingItems"] = "Adicione pelo menos um item.",
                ["ErrorMissingName"] = "Insira um nome de loja.",
                ["ErrorNotEnoughItems"] = "Não há itens suficientes no espaço de inventário {0}.",
                ["Hint"] = "Arraste itens para os slots para configurar sua loja.",
                ["PriceInput"] = "Preço por unidade",
                ["QuantityInput"] = "Quantidade",
                ["SelectSlot"] = "Selecione um espaço de listagem para editar.",
                ["SelectedItemLabel"] = "Selecionado: {0}",
                ["ShopNameLabel"] = "Nome da loja",
                ["ShopNamePlaceholder"] = "Insira um nome de loja amigável",
                ["SlotPrice"] = "Preço: {0}",
                ["SlotQuantity"] = "Quantidade: {0}/{1}",
                ["StatusReady"] = "Pronto para enviar.",
                ["StatusSubmitting"] = "Enviando solicitação...",
                ["UnknownItem"] = "Item desconhecido",
            },
            ["QuestLog"] = new JObject
            {
                ["Abandon"] = "Abandonar",
                ["AbandonPrompt"] = "Tem certeza de que deseja encerrar a missão \"{00}\"?",
                ["AbandonTitle"] = "Abandonar missão: {00}",
                ["Back"] = "Voltar",
                ["Completed"] = "Missão concluída",
                ["CurrentTask"] = "Tarefa Atual:",
                ["InProgress"] = "Missão em andamento",
                ["NotStarted"] = "Missão não iniciada",
                ["TaskItem"] = "{00}/{01} {02}(s) reunidos.",
                ["TaskNpc"] = "{00}/{01} {02}(s) morto.",
                ["Title"] = "Registro de missão",
            },
            ["QuestOffer"] = new JObject
            {
                ["Accept"] = "Aceitar",
                ["Decline"] = "Recusar",
                ["Title"] = "Oferta de missão",
            },
            ["QuestRewardExp"] = new JObject
            {
                ["FactionHonorGenericTooltip"] = "Honra da Facção",
                ["FactionHonorTooltip"] = "{0} Honra",
                ["FactionNeutralName"] = "Neutro",
                ["FactionNidrajName"] = "Nidraj",
                ["FactionSerolfName"] = "Serolf",
                ["GuildExpTooltip"] = "Guilda EXP",
                ["JobExpTooltip"] = "{0} EXP",
                ["JobGenericTooltip"] = "Trabalho EXP",
                ["PlayerExpTooltip"] = "Jogador EXP",
            },
            ["Regex"] = new JObject
            {
                ["Password"] = "^[-_=\\+`~!@#\\$%\\^&\\*()\\[\\]{}\\\\|;\\:'\",<\\.>/\\?a-zA-Z0-9]{4,64}$",
                ["Username"] = "^[a-zA-Z0-9]{2,20}$",
            },
            ["Registration"] = new JObject
            {
                ["Back"] = "Voltar",
                ["ConfirmPassword"] = "Confirme a senha:",
                ["Email"] = "E-mail:",
                ["EmailInvalid"] = "O e-mail é inválido.",
                ["Password"] = "Senha:",
                ["PasswordMismatch"] = "As senhas não coincidem.",
                ["Register"] = "Cadastre-se",
                ["Title"] = "Cadastre-se",
                ["Username"] = "Nome de usuário:",
            },
            ["Server"] = new JObject
            {
                ["Connecting"] = "Conectando...",
                ["Failed"] = "Erro de rede",
                ["HandshakeFailure"] = "Erro de aperto de mão",
                ["Offline"] = "Off-line",
                ["Online"] = "On-line",
                ["ServerFull"] = "Servidor está cheio",
                ["StatusLabel"] = "Status do servidor: {00}",
                ["Unknown"] = "Desconhecido",
                ["VersionMismatch"] = "Incompatibilidade de versão",
            },
            ["Settings"] = new JObject
            {
                ["Apply"] = "Aplicar",
                ["AudioSettingsTab"] = "Áudio",
                ["AutoCloseWindows"] = "Fechar janelas automaticamente",
                ["AutoSoftRetargetOnSelfCast"] = "Redirecionamento suave automático em autotransmissão",
                ["AutoToggleChatLog"] = "Alternar automaticamente a visibilidade do registro de bate-papo",
                ["AutoTurnToTarget"] = "Giro automático para o alvo",
                ["Cancel"] = "Cancelar",
                ["ControlsTab"] = "Controles",
                ["EnableLighting"] = "Ativar efeitos de luz",
                ["EnableScrollingWorldZoom"] = "Ative a rolagem para alterar a escala mundial no jogo",
                ["FPS"] = "FPS",
                ["FormatResolution"] = "{00}x{01}",
                ["FormatZoom"] = "{00}x",
                ["Fps120"] = "120",
                ["Fps30"] = "30",
                ["Fps60"] = "60",
                ["Fps90"] = "90",
                ["ShowAchievementNotifications"] = "Mostrar notificações de conquistas",
                ["Fullscreen"] = "Tela cheia",
                ["GameSettingsTab"] = "Jogo",
                ["InformationSettings"] = "Informação",
                ["InterfaceSettings"] = "Interface",
                ["Language"] = "Idioma",
                ["LanguageReloadNotice"] = "Algumas janelas precisam ser reabertas.",
                ["MusicVolume"] = "Volume da música: {00}%",
                ["Resolution"] = "Resolução",
                ["ResolutionCustom"] = "Resolução personalizada",
                ["Restore"] = "Restaurar padrões",
                ["SectionVolume"] = "Volume",
                ["ShowExperienceAsPercentage"] = "Mostrar experiência como porcentagem",
                ["ShowFPSCounter"] = "Mostrar contador FPS",
                ["ShowAchievementNotifications"] = "Mostrar notificações de conquistas",
                ["ShowFriendOverheadHpBar"] = "Mostrar barra HP aos amigos",
                ["ShowFriendOverheadInformation"] = "Mostrar informações gerais aos amigos",
                ["ShowGuildOverheadHpBar"] = "Mostrar barra HP de sobrecarga do membro da guilda",
                ["ShowGuildOverheadInformation"] = "Mostrar informações gerais dos membros da guilda",
                ["ShowHealthAsPercentage"] = "Mostrar saúde como porcentagem",
                ["ShowManaAsPercentage"] = "Mostrar mana como porcentagem",
                ["ShowMyOverheadHpBar"] = "Mostrar minha barra HP suspensa",
                ["ShowMyOverheadInformation"] = "Mostrar minhas informações gerais",
                ["ShowNpcOverheadHpBar"] = "Mostrar barra NPC de sobrecarga HP",
                ["ShowNpcOverheadInformation"] = "Mostrar informações gerais de NPC",
                ["ShowPartyOverheadHpBar"] = "Mostrar barra HP de sobrecarga do membro do grupo",
                ["ShowPartyOverheadInformation"] = "Mostrar informações gerais dos membros do grupo",
                ["ShowPingCounter"] = "Mostrar contador de ping",
                ["ShowPlayerOverheadHpBar"] = "Mostrar barra HP dos jogadores acima da cabeça",
                ["ShowPlayerOverheadInformation"] = "Mostrar informações gerais dos jogadores",
                ["SimplifiedEscapeMenu"] = "Menu de escape simplificado",
                ["SoundVolume"] = "Volume do som: {00}%",
                ["StickyTarget"] = "Alvo pegajoso",
                ["TargetingSettings"] = "Segmentação",
                ["Title"] = "Configurações",
                ["TypewriterText"] = "Texto de máquina de escrever",
                ["UIScale"] = "Escala UI",
                ["UnlimitedFps"] = "Sem limite",
                ["VideoSettingsTab"] = "Vídeo",
                ["VolumeMusic"] = "Música",
                ["VolumeSoundEffects"] = "Efeitos Sonoros",
                ["Vsync"] = "Sincronização V",
                ["WorldScale"] = "Escala Mundial",
            },
            ["Shop"] = new JObject
            {
                ["BuyItem"] = "Comprar item",
                ["BuyItemPrompt"] = "Quantas unidades de {00} você gostaria de comprar?",
                ["CannotSell"] = "Esta loja não aceita esse item!",
                ["Costs"] = "Custos {00} {01}(s)",
                ["SellItem"] = "Vender item",
                ["SellItemPrompt"] = "Quantas unidades de {00} você gostaria de vender?",
                ["SellPrompt"] = "Deseja vender o item: {00}?",
                ["SellsFor"] = "Vende por {00} {01}(s)",
                ["Title"] = "Loja",
                ["WontBuy"] = "A loja não comprará este item",
            },
            ["ShopContextMenu"] = new JObject
            {
                ["Buy"] = "Compre {00}",
            },
            ["SpellContextMenu"] = new JObject
            {
                ["Cast"] = "Elenco {00}",
                ["Forget"] = "Esqueça {00}",
                ["LevelUp"] = "Subir de nível {00}",
            },
            ["SpellDescription"] = new JObject
            {
                ["Bound"] = "Não pode ser desaprendido.",
                ["CastTime"] = "Tempo de lançamento:",
                ["Cooldown"] = "Recarga:",
                ["CooldownGroup"] = "Grupo de resfriamento:",
                ["CritChance"] = "Chance Crítica:",
                ["CritMultiplier"] = "Multiplicador Crítico:",
                ["DamageType"] = "Tipo de dano:",
                ["DamageTypes"] = new JObject
                {
                    ["0"] = "Físico",
                    ["1"] = "Magia",
                    ["2"] = "Verdadeiro",
                },
                ["Distance"] = "Distância:",
                ["DoT"] = "Danos ao longo do tempo",
                ["Duration"] = "Duração:",
                ["Effect"] = "Efeito:",
                ["Effects"] = new JObject
                {
                    ["0"] = "Configurações",
                    ["1"] = "Silêncio",
                    ["10"] = "Dormir",
                    ["11"] = "Ao acertar",
                    ["12"] = "Provocação",
                    ["13"] = "Empurrão para trás",
                    ["14"] = "Vampirismo",
                    ["2"] = "Atordoar",
                    ["3"] = "Armadilha",
                    ["4"] = "Cego",
                    ["5"] = "Furtivo",
                    ["6"] = "Transformações",
                    ["7"] = "Limpar",
                    ["8"] = "Invulnerável",
                    ["9"] = "Escudo",
                },
                ["Friendly"] = "Feitiço de Suporte",
                ["HoT"] = "Cura com o tempo",
                ["IgnoreConsumedResourceBlock"] = "Ignora recursos consumidos",
                ["IgnoreCooldownReduction"] = "Ignora a redução do tempo de espera",
                ["IgnoreGlobalCooldown"] = "Ignora o resfriamento global",
                ["IgnoreMapBlock"] = "Ignora blocos de mapa",
                ["IgnoreResourceBlock"] = "Ignora recursos ativos",
                ["IgnoreZDimension"] = "Ignora diferenças de altura",
                ["Instant"] = "Instantâneo",
                ["Level"] = "Nível:",
                ["Multiplier"] = "{00}x",
                ["Percentage"] = "{00}%",
                ["RegularAndPercentage"] = "{00} + {01}%",
                ["ScalingPercentage"] = "Porcentagem de escala:",
                ["ScalingStat"] = "Estatística de escala:",
                ["SpellTypes"] = new JObject
                {
                    ["0"] = "Feitiço de Combate",
                    ["1"] = "Distorcer para mapa",
                    ["2"] = "Distorcer para o alvo",
                    ["3"] = "Traço",
                    ["4"] = "Especial",
                    ["5"] = "Convocar NPC",
                    ["6"] = "Ressurreição",
                },
                ["StatBuff"] = "Buff de estatísticas",
                ["StatCounts"] = new JObject
                {
                    ["0"] = "Ataque:",
                    ["1"] = "Inteligência:",
                    ["2"] = "Defesa:",
                    ["3"] = "Vitalidade:",
                    ["4"] = "Velocidade:",
                    ["5"] = "Agilidade:",
                },
                ["Stats"] = new JObject
                {
                    ["0"] = "Ataque",
                    ["1"] = "Inteligência",
                    ["2"] = "Defesa",
                    ["3"] = "Vitalidade",
                    ["4"] = "Velocidade",
                    ["5"] = "Agilidade",
                },
                ["TargetTypes"] = new JObject
                {
                    ["0"] = "Auto elenco",
                    ["1"] = "Alvo - Intervalo: blocos {00}",
                    ["2"] = "AOE",
                    ["3"] = "Projétil - Alcance: {00} Blocos",
                    ["4"] = "Ao acertar",
                    ["5"] = "Armadilha",
                },
                ["Tick"] = "Marca cada:",
                ["Tiles"] = "{00} Blocos",
                ["Unfriendly"] = "Feitiço Danificante",
                ["VitalCosts"] = new JObject
                {
                    ["0"] = "HP Custo:",
                    ["1"] = "MP Custo:",
                },
                ["VitalDamage"] = new JObject
                {
                    ["0"] = "HP Danos:",
                    ["1"] = "MP Danos:",
                },
                ["VitalRecovery"] = new JObject
                {
                    ["0"] = "HP Recuperação:",
                    ["1"] = "MP Recuperação:",
                },
            },
            ["Spells"] = new JObject
            {
                ["EmptySlot"] = "Slot de feitiço vazio",
                ["ForgetSpell"] = "Esqueça o feitiço",
                ["ForgetSpellPrompt"] = "Tem certeza de que deseja esquecer {00}?",
                ["Title"] = "Feitiços",
            },
            ["TradeContextMenu"] = new JObject
            {
                ["Withdraw"] = "Revogar {00}",
            },
            ["Trading"] = new JObject
            {
                ["Accept"] = "Aceitar",
                ["BUY"] = "[BUY]",
                ["Format"] = "[Negociação] {00}: {01}",
                ["InFight"] = "Você está lutando no momento!",
                ["Muted"] = "Você não pode enviar mensagens comerciais enquanto estiver silenciado.",
                ["OfferItem"] = "Item de oferta",
                ["OfferItemPrompt"] = "Quantas unidades de {00} você gostaria de oferecer?",
                ["OtherPlayer"] = "O outro jogador aceitou a troca.",
                ["Pending"] = "Pendente",
                ["RevokeItem"] = "Revogar item",
                ["RevokeItemPrompt"] = "Quantas unidades de {00} você gostaria de revogar?",
                ["SELL"] = "[SELL]",
                ["TheirOffer"] = "Sua oferta:",
                ["Title"] = "Negociando com {00}",
                ["TooFast"] = "Você está enviando mensagens muito rapidamente! Por favor, aguarde.",
                ["TradeRequest"] = "Convite de negociação",
                ["Value"] = "Valor: {00}",
                ["YourOffer"] = "Sua oferta:",
            },
            ["Update"] = new JObject
            {
                ["Checking"] = "Verificando atualizações, aguarde.",
                ["Done"] = "Atualização concluída! Lançando jogo.",
                ["Error"] = "Erro de atualização! Verifique os registros para obter mais informações.",
                ["FilesRemaining"] = "{00} Arquivos restantes",
                ["PercentComplete"] = "{00}%",
                ["RemainingSize"] = "{00} Esquerda",
                ["Restart"] = "Atualização concluída! Reinicie {00} para jogar.",
                ["Updating"] = "Baixando atualizações, aguarde.",
            },
            ["Words"] = new JObject
            {
                ["LcaseSound"] = "som",
                ["LcaseSprite"] = "ator",
            },
        };
    }
}
