using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Intersect.Client.Localization;

internal static partial class ClientLocalizationOverrides
{
    private static partial void AddEsOverrides(IDictionary<string, JObject> overrides)
    {
        overrides["es"] = new JObject
        {
            ["Market"] = new JObject
            {
                ["sellwindow"] = @"Vender en el mercado",
                ["selectitem"] = @"Seleccione un artículo de su inventario",
                ["publish_colon"] = @"Publicar:",
                ["quantity"] = @"Cantidad",
                ["price"] = @"Precio",
                ["taxes_estimated"] = @"🧾 Impuesto estimado: {0}",
                ["taxes_0"] = @"🧾 Impuesto estimado: 0",
                ["splitpackages"] = @"Dividir en paquetes (1, 10, 100, 1000)",
                ["publish"] = @"Publicar",
                ["noItemSelected"] = @"⚠️ Ningún artículo seleccionado.",
                ["invalidItem"] = @"⚠️ Artículo no encontrado en el inventario.",
                ["invalidQuantity"] = @"❌ La cantidad debe ser mayor que cero.",
                ["invalidPrice"] = @"❌ El precio debe ser mayor que cero.",
                ["quantityExceeds"] = @"❌ La cantidad excede los artículos disponibles ({0}).",
                ["priceOutOfRange"] = @"❌ El precio debe estar entre {0} y {1} 🪙.",
                ["pricehint"] = @"Precio sugerido: {0}",
                ["pricerange"] = @"Rango sugerido: {0}/{1}",
                ["listedSuccessfully"] = @"¡Listado creado exitosamente!",
                ["windowTitle"] = @"Mercado mundial",
                ["itemNameLabel"] = @"Nombre del artículo:",
                ["itemTypeLabel"] = @"Tipo:",
                ["all"] = @"Todos",
                ["minPriceLabel"] = @"Precio mínimo:",
                ["maxPriceLabel"] = @"Precio máximo:",
                ["searchButton"] = @"Buscar",
                ["sellButton"] = @"Vender",
                ["retryButton"] = @"Reintentar",
                ["headerItemName"] = @"Nombre del artículo",
                ["headerQuantity"] = @"Cantidad",
                ["headerPrice"] = @"Precio",
                ["noResults"] = @"❌ No se encontraron resultados.",
                ["itemSubTypeLabel"] = @"Subtipos",
                ["Buy"] = @"Comprar",
            },
            ["PlayerShops"] = new JObject
            {
                ["CreatorTitle"] = @"Tienda de jugadores",
                ["ShopNameLabel"] = @"Nombre de la tienda",
                ["ShopNamePlaceholder"] = @"Ingrese un nombre amigable para la tienda",
                ["Hint"] = @"Arrastre elementos a las ranuras para configurar su tienda.",
                ["DecorationLabel"] = @"Decoración",
                ["SelectSlot"] = @"Seleccione un espacio de listado para editar.",
                ["QuantityInput"] = @"Cantidad",
                ["PriceInput"] = @"Precio por unidad",
                ["ClearSlot"] = @"Borrar ranura",
                ["CreateShop"] = @"Entrar en modo comerciante",
                ["Cancel"] = @"Cancelar",
                ["StatusReady"] = @"Listo para enviar.",
                ["StatusSubmitting"] = @"Enviando solicitud...",
                ["ErrorMissingName"] = @"Ingrese un nombre de tienda.",
                ["ErrorMissingItems"] = @"Añade al menos un artículo.",
                ["ErrorInvalidQuantity"] = @"La cantidad debe ser mayor que cero.",
                ["ErrorInvalidPrice"] = @"El precio debe ser mayor que cero.",
                ["ErrorInvalidInventory"] = @"El artículo seleccionado ya no está en su inventario.",
                ["ErrorNotEnoughItems"] = @"No hay suficientes artículos en el espacio de inventario {0}.",
                ["SelectedItemLabel"] = @"Seleccionado: {0}",
                ["EmptySlot"] = @"Ranura vacía",
                ["SlotQuantity"] = @"Cantidad: {0}/{1}",
                ["SlotPrice"] = @"Precio: {0}",
                ["BrowserTitle"] = @"Tienda de {0}",
                ["BrowserOwner"] = @"Propietario: {0}",
                ["BrowserPriceEach"] = @"Precio: {0} c/u",
                ["BrowserAvailable"] = @"Disponible: {0}",
                ["BrowserTotal"] = @"Total: {0}",
                ["BrowserBuy"] = @"comprar",
                ["BrowserEmpty"] = @"Esta tienda no tiene artículos a la venta.",
                ["BrowseStatus"] = @"Seleccione un elemento para comenzar.",
                ["UnknownItem"] = @"Artículo desconocido",
            },
            ["MailBox"] = new JObject
            {
                ["title"] = @"Buzón de correo",
                ["sendtitle"] = @"Enviar correo",
                ["send"] = @"enviar",
                ["close"] = @"Cerrar",
                ["itemnone"] = @"Ninguno",
                ["mailto"] = @"a",
                ["mailtitle"] = @"Título",
                ["mailmsg"] = @"Mensaje",
                ["mailitem"] = @"Artículo",
                ["mailquantity"] = @"Cantidad",
                ["mails"] = @"Correos",
                ["sender"] = @"Remitente",
                ["take"] = @"Recibir correo (Delete)",
                ["additem"] = @"Agregar artículo",
                ["attachments"] = @"Adjuntos",
                ["sendMailButton"] = @"📤 Enviar correo",
                ["closeButton"] = @"❌ Cerrar",
                ["unknownSender"] = @"Remitente desconocido",
                ["noSubject"] = @"Sin Asunto",
            },
            ["Breaking"] = new JObject
            {
                ["WindowTitle"] = @"Desmontaje del artículo",
                ["Title"] = @"Romper elementos",
                ["SelectedItem"] = @"Artículo seleccionado",
                ["ResultItems"] = @"Posibles resultados",
                ["Break"] = @"Romper",
                ["NoItemSelected"] = @"¡No se ha seleccionado ningún artículo para romper!",
                ["BreakSuccess"] = @"El artículo fue desmantelado con éxito.",
                ["BreakFail"] = @"El artículo no se pudo desmontar.",
                ["ConfirmBreak"] = @"¿Estás seguro de que quieres desmantelar este artículo?",
                ["Close"] = @"Cerrar",
                ["ItemLocked"] = @"Este artículo no se puede descomponer.",
                ["NothingToGain"] = @"Romper este objeto no produce materiales.",
            },
            ["Enchanting"] = new JObject
            {
                ["WindowTitle"] = @"Encantar objetos",
                ["Title"] = @"Encantamiento de objetos",
                ["SelectedItem"] = @"Artículo seleccionado",
                ["Cost"] = @"Costo de encantamiento",
                ["Chance"] = @"Oportunidad de éxito",
                ["UseAmulet"] = @"Usar amuleto protector",
                ["Enchant"] = @"encantar",
                ["NoItemSelected"] = @"¡No se ha seleccionado ningún objeto para encantar!",
                ["EnchantSuccess"] = @"¡El objeto fue encantado con éxito!",
                ["EnchantFail"] = @"El encantamiento falló. ¡Más suerte la próxima vez!",
                ["InsufficientCurrency"] = @"No tienes suficiente moneda para encantar este artículo.",
                ["Close"] = @"Cerrar",
                ["Projection"] = @"Proyección",
                ["MaxEnchantReached"] = @"¡El objeto ha alcanzado el nivel máximo de encantamiento!",
            },
            ["Job"] = new JObject
            {
                ["job"] = @"Ventana de trabajos",
                ["Farming"] = @"agricultura",
                ["Fishing"] = @"pesca",
                ["Mining"] = @"Minería",
                ["Lumberjack"] = @"leñador",
                ["Hunting"] = @"Caza",
                ["Blacksmith"] = @"herrero",
                ["Cooking"] = @"Cocinar",
                ["Alchemy"] = @"Alquimia",
                ["Crafting"] = @"Elaboración",
                ["Jewerly"] = @"joyería",
                ["Tanner"] = @"curtidor",
                ["Tailoring"] = @"sastrería",
                ["None"] = @"Ninguno",
                ["MaxLevel"] = @"Nivel máximo",
                ["ExpValue"] = @"{0} / {1}",
                ["Exp"] = @"EXP: ",
                ["Level"] = @"Nivel {0}",
            },
            ["AdminWindow"] = new JObject
            {
                ["Access"] = @"Acceso",
                ["Access1"] = @"Moderador",
                ["Access2"] = @"administrador",
                ["Ban"] = @"Prohibición",
                ["BanCaption"] = @"Prohibir {00}",
                ["BanPrompt"] = @"¡Prohibir a {00} no le permitirá acceder a este juego durante el tiempo que establezcas!",
                ["SortMapList"] = @"Ordenar lista de mapas",
                ["SortMapListTooltip"] = @"Ordene los mapas en una jerarquía plana en orden alfanumérico según la configuración regional de la computadora.",
                ["Face"] = @"cara",
                ["KickPlayer"] = @"patada",
                ["KillPlayer"] = @"matar",
                ["QuickActions"] = @"Acciones rápidas",
                ["AdditionalInterfaces"] = @"Herramientas adicionales",
                ["MapList"] = @"Lista de mapas",
                ["Mute"] = @"Silenciar",
                ["MuteCaption"] = @"Silenciar {00}",
                ["MutePrompt"] = @"¡Silenciar a {00} no les permitirá chatear en el juego durante el tiempo que establezcas!",
                ["Name"] = @"Nombre",
                ["NamePlaceholder"] = @"Nombre del jugador",
                ["None"] = @"Ninguno",
                ["LeaveInstance"] = @"Deja Instancia",
                ["SetFace"] = @"Establecer cara",
                ["SetPower"] = @"Establecer potencia",
                ["SetSprite"] = @"Establecer objeto",
                ["Appearance"] = @"Apariencia",
                ["Sprite"] = @"duende:",
                ["Item"] = @"Artículo",
                ["ItemManagement"] = @"Artículos",
                ["Quantity"] = @"Cantidad",
                ["AllowOverflow"] = @"Permitir desbordamiento bancario",
                ["ReserveSpawn"] = @"Reserva de generación para el jugador",
                ["GiveItem"] = @"Dar artículo",
                ["SpawnItem"] = @"Objeto de generación",
                ["MailBroadcast"] = @"Difusión de correo",
                ["MailSubject"] = @"Asunto",
                ["MailMessage"] = @"Mensaje",
                ["MailAttachmentItem"] = @"Adjunto {00} elemento",
                ["MailAttachmentQuantity"] = @"Adjunto {00} cantidad",
                ["MailOnlineOnly"] = @"Sólo jugadores en línea",
                ["MailSend"] = @"Enviar correo",
                ["Title"] = @"administración",
                ["Unban"] = @"Desbanear",
                ["UnbanCaption"] = @"Desbanear {00}",
                ["UnbanPrompt"] = @"¿Estás seguro de que quieres desbanear {00}?",
                ["Unmute"] = @"Dejar de silenciar",
                ["UnmuteCaption"] = @"Activar el silencio {00}",
                ["UnmutePrompt"] = @"¿Estás seguro de que quieres reactivar el sonido de {00}?",
                ["WarpPlayerToMe"] = @"Deformarme",
                ["WarpMeToPlayer"] = @"Deformarme a",
            },
            ["Bags"] = new JObject
            {
                ["RetrieveItem"] = @"Recuperar artículo",
                ["RetrieveItemPrompt"] = @"¿Cuántos {00} te gustaría recuperar?",
                ["StoreItem"] = @"Artículo de la tienda",
                ["StoreItemPrompt"] = @"¿Cuántos {00} te gustaría almacenar?",
                ["Title"] = @"Bolsa",
            },
            ["Bank"] = new JObject
            {
                ["DepositItem"] = @"Artículo de depósito",
                ["DepositItemPrompt"] = @"¿Cuántos {00} te gustaría depositar?",
                ["NoSpace"] = @"¡No queda espacio en tu banco para ese artículo!",
                ["Title"] = @"banco",
                ["WithdrawItem"] = @"Retirar artículo",
                ["WithdrawItemPrompt"] = @"¿Cuánto/cuánto {00} le gustaría retirar?",
                ["WithdrawItemNoSpace"] = @"¡No queda espacio en tu inventario para ese artículo!",
                ["All"] = @"Todos",
                ["Sort"] = @"ordenar",
                ["BankValue"] = @"Valor bancario: {00}",
                ["BankValueFull"] = @"{00} Monedas Globales",
            },
            ["BanMute"] = new JObject
            {
                ["Cancel"] = @"Cancelar",
                ["Duration"] = @"Duración:",
                ["FiveDays"] = @"5 dias",
                ["FourDays"] = @"4 dias",
                ["Forever"] = @"indefinidamente",
                ["IncludeIp"] = @"Incluir IP:",
                ["OneDay"] = @"1 dia",
                ["OneMonth"] = @"1 mes",
                ["OneWeek"] = @"1 semana",
                ["OneYear"] = @"1 año",
                ["Okay"] = @"Está bien",
                ["Reason"] = @"Razón:",
                ["SixMonths"] = @"6 meses",
                ["ThreeDays"] = @"3 dias",
                ["TwoDays"] = @"2 dias",
                ["TwoMonths"] = @"2 meses",
                ["TwoWeeks"] = @"2 semanas",
            },
            ["Bestiary"] = new JObject
            {
                ["Title"] = @"Bestiario",
                ["SearchPlaceholder"] = @"Buscar...",
                ["SectionStats"] = @"Estadísticas",
                ["SectionDrops"] = @"Gotas",
                ["SectionSpells"] = @"hechizos",
                ["SectionBehavior"] = @"Comportamiento",
                ["SectionLore"] = @"historia",
                ["Locked"] = @"bloqueado",
                ["Unlocked"] = @"desbloqueado",
                ["UnlockNotice"] = @"Desbloqueado {1} para {0}",
                ["LockedKills"] = @"🔒 Derrota {0}/{1} veces para desbloquear.",
                ["LockedInfo"] = @"🔒 Información bloqueada.",
                ["AggressiveLabel"] = @"Agresivo: {0}",
                ["MovementLabel"] = @"Movimiento: {0}",
                ["FleeHpLabel"] = @"Huir % de HP: {0}%",
                ["SwarmLabel"] = @"Enjambre: {0}",
                ["Yes"] = @"sí",
                ["No"] = @"No",
                ["LorePlaceholder"] = @"(Aquí puedes insertar un sistema de descripciones opcionales para NPC)",
            },
            ["Character"] = new JObject
            {
                ["AttackSpeed"] = @"Velocidad de ataque: {00}s",
                ["CooldownReduction"] = @"Reducción de tiempo de reutilización: {00}%",
                ["Equipment"] = @"Equipo:",
                ["ExtraBuffs"] = @"Mejoras adicionales",
                ["ExtraExp"] = @"EXP de bonificación: {00}%",
                ["HealthRegen"] = @"Regeneración de salud: {00}%",
                ["CriticalChance"] = @"Probabilidad crítica: {00}%",
                ["LevelAndClass"] = @"Nivel: {00}, Clase: {01}",
                ["Lifesteal"] = @"Robo de vida: {00}%",
                ["Luck"] = @"Suerte: {00}%",
                ["ManaRegen"] = @"Regeneración de maná: {00}%",
                ["Manasteal"] = @"Robo de maná: {00}%",
                ["BasicAttackDamage"] = @"Daño básico: {00} | Verdadero: {01}-{02}",
                ["Points"] = @"Puntos: {00}",
                ["StatLabelValue"] = @"{00}: {01}",
                ["Stats"] = @"Estadísticas:",
                ["Agility"] = @"Agilidad:",
                ["Tenacity"] = @"Tenacidad: {00}%",
                ["FlatDamage"] = @"Bonificación por daños: {00}",
                ["FlatCures"] = @"Bonificación de curación: {00}",
                ["Title"] = @"Información del personaje",
            },
            ["CharacterCreation"] = new JObject
            {
                ["Back"] = @"Atrás",
                ["Class"] = @"clase",
                ["Create"] = @"crear",
                ["Female"] = @"Mujer",
                ["Gender"] = @"Género",
                ["Hint"] = @"Personalizar",
                ["Hint2"] = @"tu personaje",
                ["InvalidName"] = @"El nombre del personaje no es válido. Utilice caracteres alfanuméricos con una longitud entre 2 y 20.",
                ["Male"] = @"masculino",
                ["Name"] = @"Nombre",
                ["Title"] = @"Crear un nuevo personaje",
            },
            ["CharacterSelection"] = new JObject
            {
                ["Delete"] = @"Eliminar",
                ["DeletePrompt"] = @"¿Está seguro de que desea eliminar {00}? ¡Esta acción es irreversible!",
                ["DeleteTitle"] = @"Eliminar {00}",
                ["Empty"] = @"Ranura de personaje vacía",
                ["Info"] = @"Nivel: {00}, Clase: {01}",
                ["Logout"] = @"Cerrar sesión",
                ["ChangePassword"] = @"Cambiar contraseña",
                ["Name"] = @"{00}",
                ["New"] = @"Nuevo",
                ["Play"] = @"Jugar",
                ["Title"] = @"Selecciona un personaje para jugar",
            },
            ["Chatbox"] = new JObject
            {
                ["Channel"] = @"Canal:",
                ["ChannelAdmin"] = @"administrador",
                ["ClearLogButtonToolTip"] = @"Borrar mensajes del registro de chat",
                ["EnterChat"] = @"Haga clic aquí para charlar.",
                ["EnterChat1"] = @"Presione '{00}' para chatear.",
                ["EnterChat2"] = @"Presione '{00}' o '{01}' para chatear.",
                ["Send"] = @"enviar",
                ["Title"] = @"Charla",
                ["ToggleLogButtonToolTip"] = @"Alternar visibilidad del registro de chat",
                ["TooFast"] = @"¡Estás charlando demasiado rápido!",
                ["UnableToCopy"] = @"Parece que no puedes copiar/pegar en esta plataforma. Asegúrese de tener instalados los paquetes 'xclip' o 'wl-clipboard' si está ejecutando Linux.",
            },
            ["Combat"] = new JObject
            {
                ["AttackWhileCastingDeny"] = @"No puedes atacar mientras lanzas un hechizo.",
                ["WarningCharacterSelect"] = @"¡Estás intentando cerrar sesión mientras estás en combate! Tu personaje permanecerá en el juego hasta que finalice el combate. ¿Está seguro de que desea cerrar sesión ahora?",
                ["WarningExitDesktop"] = @"¡Estás intentando salir mientras estás en combate! Tu personaje permanecerá en el juego hasta que finalice el combate. ¿Estás seguro de que quieres dejar de fumar ahora?",
                ["WarningLogout"] = @"¡Estás intentando cerrar sesión mientras estás en combate! Tu personaje permanecerá en el juego hasta que finalice el combate. ¿Está seguro de que desea cerrar sesión ahora?",
                ["WarningTitle"] = @"¡Advertencia de combate!",
            },
            ["Content"] = new JObject
            {
            },
            ["Controls"] = new JObject
            {
                ["HotkeyXLabel"] = @"Tecla de acceso rápido {00}:",
                ["Listening"] = @"Escuchando",
            },
            ["Crafting"] = new JObject
            {
                ["Craft"] = @"Manualidad 1",
                ["CraftAll"] = @"Elaboración {00}",
                ["CraftChance"] = @"Posibilidad de fallo: {00}%",
                ["CraftingTime"] = @"Tiempo de elaboración: {00}s",
                ["CraftStop"] = @"Detener",
                ["DestroyMaterialsChance"] = @"Posibilidad de destruir materiales: {00}%",
                ["IncorrectResources"] = @"No tienes los recursos necesarios para crear este artículo.",
                ["Ingredients"] = @"Requerido:",
                ["Product"] = @"Elaboración:",
                ["Recipes"] = @"Recetas:",
                ["RecipeListEntry"] = @"{00}) {01}",
                ["Exp"] = @"EXP: {00}",
                ["CraftingName"] = @"Elaboración",
            },
            ["Credits"] = new JObject
            {
                ["Back"] = @"Volver al menú principal",
                ["Title"] = @"Créditos",
            },
            ["Debug"] = new JObject
            {
                ["SectionGPUStatistics"] = @"Estadísticas de GPU",
                ["SectionGPUAllocations"] = @"Asignaciones de GPU",
                ["SectionSystemStatistics"] = @"Estadísticas del sistema",
                ["RenderTargetAllocations"] = @"Representar asignaciones de objetivos",
                ["TextureAllocations"] = @"Asignaciones de textura",
                ["TextureCount"] = @"Activos de textura",
                ["UsedVRAM"] = @"VRAM usada",
                ["FreeVRAM"] = @"VRAM gratis",
                ["TotalVRAM"] = @"VRAM total",
                ["FreeVirtualRAM"] = @"RAM libre (virtual)",
                ["TotalVirtualRAM"] = @"RAM total (virtual)",
                ["FreePhysicalRAM"] = @"RAM libre (física)",
                ["TotalPhysicalRAM"] = @"RAM total (física)",
                ["ControlUnderCursor"] = @"Control debajo del cursor",
                ["DrawDebugOutlines"] = @"Dibujar contornos de depuración",
                ["Draws"] = @"Sorteos",
                ["EnableLayoutHotReloading"] = @"Habilitar la recarga en caliente del diseño experimental",
                ["IncludeTextNodesInHover"] = @"Incluir nodos de texto al pasar el mouse",
                ["ViewClickedNodeInDebugger"] = @"Ver el nodo en el que se hizo clic en el depurador",
                ["ViewClickedNodeInDebuggerTooltip"] = @"Mantenga presionado Alt para desactivar esto temporalmente (para que pueda desactivar esta opción)",
                ["EntitiesDrawn"] = @"Entidades dibujadas",
                ["Fps"] = @"FPS",
                ["InterfaceObjects"] = @"Objetos de interfaz",
                ["KnownEntities"] = @"Entidades conocidas",
                ["KnownMaps"] = @"Mapas conocidos",
                ["LightsDrawn"] = @"luces dibujadas",
                ["Map"] = @"Mapa",
                ["MapsDrawn"] = @"Mapas dibujados",
                ["Ping"] = @"hacer ping",
                ["ShutdownServer"] = @"Apagar servidor",
                ["ShutdownServerAndExit"] = @"Apagar el servidor y salir",
                ["FormatTextureFromAtlas"] = @"{00} (del atlas)",
                ["Time"] = @"tiempo",
                ["Title"] = @"Depurar",
                ["TitleX"] = @"Depuración #{0}",
                ["TabLabelSystem"] = @"Sistema",
                ["TabLabelInfo"] = @"Información",
                ["TabLabelAssets"] = @"Activos",
                ["ReloadAsset"] = @"Recargar activo",
                ["AssetsSearchPlaceholder"] = @"Filtrar activos...",
            },
            ["EntityBox"] = new JObject
            {
                ["Exp"] = @"EXP:",
                ["ExpValue"] = @"{00} / {01}",
                ["Level"] = @"Lv. {00}",
                ["Map"] = @"{00}",
                ["MaxLevel"] = @"Nivel máximo",
                ["NameAndLevel"] = @"{00} {01}",
                ["Vital0"] = @"HP:",
                ["Vital0Value"] = @"{00} / {01}",
                ["Vital1"] = @"diputado:",
                ["Vital1Value"] = @"{00} / {01}",
            },
            ["Alerts"] = new JObject
            {
                ["FallbackTitle"] = @"Alerta",
            },
            ["Errors"] = new JObject
            {
                ["DisconnectionEvent"] = @"Proporcione este mensaje a su administrador: {0}",
                ["DisplayNotSupported"] = @"¡Configuración de pantalla no válida!",
                ["DisplayNotSupportedError"] = @"¡La resolución de pantalla completa {00} no es compatible con este dispositivo!",
                ["HostNotFound"] = @"Error de resolución de DNS. Infórmalo al administrador del juego.",
                ["LoadFile"] = @"No se pudo cargar un {00}. Envíe al administrador del juego una copia de su archivo de registro de errores en el directorio de registros.",
                ["LostConnection"] = @"Se perdió la conexión con el servidor del juego. ¡Asegúrate de estar conectado a Internet e inténtalo de nuevo!",
                ["NotConnected"] = @"No conectado al servidor del juego. ¿Está en línea?",
                ["InvalidStateReturnToMainMenu"] = @"Se detectó un estado no válido y tuvimos que volver al menú principal.",
                ["OpenAllLink"] = @"https://goo.gl/Nbx6hx",
                ["OpenGlLink"] = @"https://goo.gl/RSP3ts",
                ["PasswordInvalid"] = @"La contraseña no es válida. Utilice caracteres alfanuméricos con una longitud entre 4 y 20.",
                ["ResourcesNotFound"] = @"¡No se pudo encontrar el directorio de recursos! Intersect ahora se cerrará.",
                ["Title"] = @"¡Error!",
                ["UsernameInvalid"] = @"El nombre de usuario no es válido. Utilice caracteres alfanuméricos con una longitud entre 2 y 20.",
            },
            ["Words"] = new JObject
            {
                ["LcaseSound"] = @"sonido",
                ["LcaseSprite"] = @"duende",
            },
            ["EventWindow"] = new JObject
            {
                ["Continue"] = @"Continuar",
            },
            ["ForgotPass"] = new JObject
            {
                ["Back"] = @"Atrás",
                ["Disclaimer"] = @"Si existe una cuenta con el nombre de usuario o dirección de correo electrónico proporcionados, se enviará un correo electrónico con un código de restablecimiento de contraseña a la dirección de correo electrónico asociada con la cuenta.",
                ["UsernameOrEmailPlaceholder"] = @"Nombre de usuario o dirección de correo electrónico",
                ["Submit"] = @"Enviar",
                ["Title"] = @"Restablecer contraseña",
            },
            ["Friends"] = new JObject
            {
                ["AddFriend"] = @"Agregar amigo",
                ["AddFriendPrompt"] = @"¿A quién te gustaría agregar como amigo?",
                ["InFight"] = @"¡Actualmente estás en una pelea!",
                ["Offline"] = @"Sin conexión",
                ["RemoveFriend"] = @"Eliminar amigo",
                ["RemoveFriendPrompt"] = @"¿Quieres eliminar a {00} de tu lista de amigos?",
                ["Request"] = @"Solicitud de amistad",
                ["RequestPrompt"] = @"{00} te ha enviado una solicitud de amistad. ¿Aceptas?",
                ["Title"] = @"Amigos",
            },
            ["GameMenu"] = new JObject
            {
                ["Character"] = @"Información del personaje",
                ["Friends"] = @"Amigos",
                ["Items"] = @"inventario",
                ["Menu"] = @"Abrir menú",
                ["Party"] = @"fiesta",
                ["Quest"] = @"Registro de misiones",
                ["Spells"] = @"Libro de hechizos",
                ["Jobs"] = @"Empleos",
            },
            ["General"] = new JObject
            {
                ["MapItemStackable"] = @"{01} {00}",
                ["None"] = @"Ninguno",
                ["FpsLabelFormat"] = @"{0}fps",
                ["PingLabelFormat"] = @"{0}ms",
            },
            ["Guilds"] = new JObject
            {
                ["Add"] = @"+",
                ["Bank"] = @"{00} Banco del gremio",
                ["Demote"] = @"Degradado a {00}",
                ["DemotePrompt"] = @"¿Está seguro de que desea degradar a {00} para clasificarlo como {01}?",
                ["DemoteTitle"] = @"Degradar miembro del gremio",
                ["Guild"] = @"gremio",
                ["GuildTip"] = @"Envía a {00} una invitación a tu gremio.",
                ["Invite"] = @"invitar",
                ["InviteAlreadyInGuild"] = @"El jugador al que intentas invitar ya está en un gremio o tiene una invitación pendiente.",
                ["InviteMemberPrompt"] = @"¿A quién te gustaría invitar a {00}?",
                ["InviteMemberTitle"] = @"Invitar jugador",
                ["InviteRequestPrompt"] = @"{00} quisiera invitarte a unirte a su gremio, {01}. ¿Aceptas?",
                ["InviteRequestPromptMissingGuild"] = @"{00} quisiera invitarte a unirte a su gremio. ¿Aceptas?",
                ["InviteRequestTitle"] = @"Invitación al gremio",
                ["Kick"] = @"patada",
                ["KickPrompt"] = @"¿Estás seguro de que quieres patear a {00}?",
                ["KickTitle"] = @"Miembro del gremio Kick",
                ["Leave"] = @"salir",
                ["LeavePrompt"] = @"¿Estás seguro de que quieres dejar tu gremio?",
                ["LeaveTitle"] = @"Dejar el gremio",
                ["NotAllowedDeposit"] = @"No tienes permiso para depositar artículos en el banco del gremio de {00}.",
                ["NotAllowedSwap"] = @"No tienes permiso para intercambiar artículos dentro del banco del gremio de {00}.",
                ["NotAllowedWithdraw"] = @"No tienes permiso para retirar dinero del banco del gremio de {00}.",
                ["NotInGuild"] = @"¡Actualmente no estás en un gremio!",
                ["OfflineListEntry"] = @"[{00}] {01} - {02}",
                ["OnlineListEntry"] = @"[{00}] {01} - {02}",
                ["PM"] = @"PM",
                ["Promote"] = @"Promocionar a {00}",
                ["PromotePrompt"] = @"¿Está seguro de que desea promocionar {00} para clasificar a {01}?",
                ["PromoteTitle"] = @"Promocionar miembro del gremio",
                ["Tooltip"] = @"Lv. {00} {01}",
                ["Transfer"] = @"Transferir",
                ["TransferTitle"] = @"Gremio de transferencia",
            },
            ["InputBox"] = new JObject
            {
                ["Cancel"] = @"Cancelar",
                ["No"] = @"No",
                ["Okay"] = @"Está bien",
                ["Yes"] = @"Sí",
            },
            ["MapItemWindow"] = new JObject
            {
                ["LootButton"] = @"Saquear todo",
                ["Title"] = @"Botín",
            },
            ["Internals"] = new JObject
            {
                ["Bounds"] = @"límites",
                ["Color"] = @"Color",
                ["ColorOverride"] = @"Anulación de color",
                ["CoordinateX"] = @"x",
                ["CoordinateY"] = @"Y",
                ["CoordinateZ"] = @"z",
                ["ExperimentalFeatureTooltip"] = @"Esta función es experimental y puede causar problemas cuando está habilitada.",
                ["GlobalItem"] = @"Mundial {00}",
                ["LocalItem"] = @"Local {00}",
                ["Name"] = @"Nombre",
                ["NotApplicable"] = @"N/A",
                ["ResolutionXByY"] = @"{0}x{1}",
                ["Type"] = @"Tipo",
                ["InnerBounds"] = @"Límites internos",
                ["Margin"] = @"Margen",
                ["Padding"] = @"Relleno",
                ["Dock"] = @"Muelle",
                ["Alignment"] = @"Alineación",
                ["TextAlign"] = @"Alinear texto",
                ["OuterBounds"] = @"Límites exteriores",
                ["Font"] = @"fuente",
                ["AutoSizeToContents"] = @"Tamaño automático al contenido",
                ["FontSize"] = @"Tamaño de fuente",
                ["AutoSizeToContentWidth"] = @"Tamaño automático al ancho del contenido",
                ["AutoSizeToContentHeight"] = @"Tamaño automático a altura del contenido",
                ["AutoSizeToContentWidthOnChildResize"] = @"ASTW sobre cambio de tamaño infantil",
                ["AutoSizeToContentHeightOnChildResize"] = @"ASTH sobre el cambio de tamaño del niño",
                ["IsVisibleInParent"] = @"EsVisibleEnPadre",
                ["IsVisibleInTree"] = @"Es visible en el árbol",
                ["IsDisabled"] = @"Está deshabilitado",
                ["IsDisabledByTree"] = @"EstáDisabledByTree",
            },
            ["Inventory"] = new JObject
            {
                ["DropItemPrompt"] = @"¿Cuántas unidades de {00} te gustaría descartar?",
                ["DropItemTitle"] = @"Soltar artículo",
                ["DropPrompt"] = @"¿Desea eliminar el artículo: {00}?",
                ["EquippedSymbol"] = @"mi",
                ["Title"] = @"inventario",
                ["Sort"] = @"ordenar",
                ["All"] = @"Todo",
            },
            ["EntityContextMenu"] = new JObject
            {
                ["AddFriend"] = @"Agregar amigo",
                ["InviteToGuild"] = @"Invitar al gremio",
                ["InviteToParty"] = @"Invitar a la fiesta",
                ["PrivateMessage"] = @"Mensaje privado",
                ["Trade"] = @"Comercio",
                ["InspectPlayer"] = @"Insjugador atractivo",
                ["ManagePlayerShop"] = @"Organizar mi tienda",
            },
            ["ItemContextMenu"] = new JObject
            {
                ["Bag"] = @"Bolsa {00}",
                ["Bank"] = @"Banco {00}",
                ["Cast"] = @"Elenco {00}",
                ["Drop"] = @"Soltar {00}",
                ["Equip"] = @"Equipar {00}",
                ["Learn"] = @"Aprende {00}",
                ["Open"] = @"Abierto {00}",
                ["Sell"] = @"Vender {00}",
                ["Show"] = @"Mostrar {00}",
                ["Trade"] = @"Oferta {00}",
                ["Unequip"] = @"Desequipar {00}",
                ["Use"] = @"Utilice {00}",
            },
            ["SpellContextMenu"] = new JObject
            {
                ["Cast"] = @"Elenco {00}",
                ["Forget"] = @"Olvídate de {00}",
                ["LevelUp"] = @"Nivel Up {00}",
            },
            ["BankContextMenu"] = new JObject
            {
                ["Withdraw"] = @"Retirar {00}",
            },
            ["BagContextMenu"] = new JObject
            {
                ["Withdraw"] = @"Retirar {00}",
            },
            ["TradeContextMenu"] = new JObject
            {
                ["Withdraw"] = @"Revocar {00}",
            },
            ["ChatContextMenu"] = new JObject
            {
                ["FriendInvite"] = @"Enviar solicitud de amistad a {00}",
                ["GuildInvite"] = @"Invitar a {00} al gremio",
                ["PartyInvite"] = @"Invitar a {00} a una fiesta",
                ["PM"] = @"Enviar mensaje privado a {00}",
            },
            ["ShopContextMenu"] = new JObject
            {
                ["Buy"] = @"Comprar {00}",
            },
            ["ItemDescription"] = new JObject
            {
                ["Amount"] = @"Cantidad:",
                ["AttackSpeed"] = @"Velocidad de ataque:",
                ["AttackSpeedComparison"] = @"Velocidad de ataque: {00} ({01})",
                ["BagSlots"] = @"Ranuras para bolsas:",
                ["Bagged"] = @"Embolsado",
                ["Banked"] = @"bancarizado",
                ["BaseDamage"] = @"Daño básico:",
                ["BaseDamageType"] = @"Tipo de daño:",
                ["BlockAbsorption"] = @"Absorción en bloque:",
                ["BlockAmount"] = @"Cantidad de bloque:",
                ["BlockChance"] = @"Oportunidad de bloqueo:",
                ["CastSpell"] = @"Lanza el hechizo: {00}",
                ["CritChance"] = @"Oportunidad crítica:",
                ["CritMultiplier"] = @"Multiplicador crítico:",
                ["Description"] = @"{00}",
                ["DropOnDeath"] = @"Caída de posibilidades de muerte:",
                ["Dropped"] = @"caído",
                ["GuildBanked"] = @"Gremio bancarizado",
                ["ItemLimits"] = @"No puede ser {00}",
                ["Multiplier"] = @"{00}x",
                ["Percentage"] = @"{00}%",
                ["RegularAndPercentage"] = @"{00} + {01}%",
                ["ResourceBonusLabel"] = @"Bono",
                ["ResourceEffectLabel"] = @"Efecto",
                ["ResourceStatModifiedLabel"] = @"Estadísticas modificadas",
                ["ResourceVitalModifiedLabel"] = @"Vital Modificado",
                ["ScalingPercentage"] = @"Porcentaje de escala:",
                ["ScalingStat"] = @"Estadísticas de escala:",
                ["SingleUse"] = @"De un solo uso",
                ["Sold"] = @"Vendido",
                ["StatGrowthRange"] = @"{00} a {01}",
                ["TeachSpell"] = @"Enseña hechizo: {00}",
                ["Traded"] = @"negociado",
                ["TwoHand"] = @"2H",
                ["UnknownEffect"] = @"Efecto desconocido",
                ["UnknownItemType"] = @"Tipo desconocido",
                ["UnknownStat"] = @"Estadística desconocida",
                ["UnknownVital"] = @"Vital desconocido",
            },
            ["Keys"] = new JObject
            {
                ["KeyNameWithModifier"] = @"{00} + {01}",
            },
            ["LoginWindow"] = new JObject
            {
                ["Back"] = @"Atrás",
                ["ForgotPassword"] = @"¿Has olvidado tu contraseña?",
                ["Login"] = @"Iniciar sesión",
                ["Password"] = @"Contraseña",
                ["SavePassword"] = @"Guardar contraseña",
                ["Title"] = @"Iniciar sesión",
                ["Username"] = @"Nombre de usuario",
            },
            ["Main"] = new JObject
            {
                ["GameName"] = @"Intersecarse",
            },
            ["MainMenu"] = new JObject
            {
                ["Credits"] = @"Créditos",
                ["Exit"] = @"Salir",
                ["Login"] = @"Iniciar sesión",
                ["Register"] = @"Registrarse",
                ["Settings"] = @"Configuración",
                ["SettingsTooltip"] = @"",
                ["Start"] = @"Empezar",
                ["Title"] = @"Menú principal",
            },
            ["Settings"] = new JObject
            {
                ["Apply"] = @"Aplicar",
                ["AudioSettingsTab"] = @"Audio",
                ["AutoCloseWindows"] = @"Cerrar ventanas automáticamente",
                ["AutoToggleChatLog"] = @"Alternar automáticamente la visibilidad del registro de chat",
                ["Cancel"] = @"Cancelar",
                ["EnableLighting"] = @"Habilitar efectos de luz",
                ["FormatResolution"] = @"{00}x{01}",
                ["FormatZoom"] = @"{00}x",
                ["Fps120"] = @"120",
                ["Fps30"] = @"30",
                ["Fps60"] = @"60",
                ["Fps90"] = @"90",
                ["ShowFPSCounter"] = @"Mostrar contador de FPS",
                ["ShowPingCounter"] = @"Mostrar contador de ping",
                ["Fullscreen"] = @"Pantalla completa",
                ["GameSettingsTab"] = @"Juego",
                ["InformationSettings"] = @"Información",
                ["InterfaceSettings"] = @"Interfaz",
                ["ControlsTab"] = @"Controles",
                ["Language"] = @"Idioma",
                ["LanguageReloadNotice"] = @"Algunas ventanas requieren reabrirse.",
                ["MusicVolume"] = @"Volumen de música: {00}%",
                ["SectionVolume"] = @"Volumen",
                ["VolumeMusic"] = @"musica",
                ["VolumeSoundEffects"] = @"Efectos de sonido",
                ["Resolution"] = @"Resolución",
                ["ResolutionCustom"] = @"Resolución personalizada",
                ["Restore"] = @"Restaurar valores predeterminados",
                ["SoundVolume"] = @"Volumen de sonido: {00}%",
                ["ShowExperienceAsPercentage"] = @"Mostrar experiencia como porcentaje",
                ["ShowFriendOverheadHpBar"] = @"Mostrar a tus amigos la barra de HP superior",
                ["ShowFriendOverheadInformation"] = @"Mostrar información general a amigos",
                ["ShowGuildOverheadHpBar"] = @"Mostrar la barra de HP superior de los miembros del gremio",
                ["ShowGuildOverheadInformation"] = @"Mostrar información general de los miembros del gremio",
                ["ShowHealthAsPercentage"] = @"Mostrar salud como porcentaje",
                ["ShowNpcOverheadHpBar"] = @"Mostrar barra de HP superior de NPC",
                ["ShowNpcOverheadInformation"] = @"Mostrar información general de NPC",
                ["ShowManaAsPercentage"] = @"Mostrar maná como porcentaje",
                ["ShowMyOverheadHpBar"] = @"Mostrar mi barra de HP superior",
                ["ShowMyOverheadInformation"] = @"Mostrar mi información general",
                ["ShowPartyOverheadHpBar"] = @"Mostrar la barra de HP superior del miembro del grupo",
                ["ShowPartyOverheadInformation"] = @"Mostrar información general de los miembros del grupo",
                ["ShowPlayerOverheadHpBar"] = @"Mostrar a los jugadores la barra de HP superior",
                ["ShowPlayerOverheadInformation"] = @"Mostrar información general a los jugadores",
                ["SimplifiedEscapeMenu"] = @"Menú de escape simplificado",
                ["StickyTarget"] = @"Objetivo pegajoso",
                ["FPS"] = @"FPS",
                ["TargetingSettings"] = @"Orientación",
                ["AutoTurnToTarget"] = @"Giro automático al objetivo",
                ["AutoSoftRetargetOnSelfCast"] = @"Reorientación suave automática en Self-Cast",
                ["Title"] = @"Configuración",
                ["TypewriterText"] = @"Texto de máquina de escribir",
                ["UIScale"] = @"Escala de interfaz de usuario",
                ["UnlimitedFps"] = @"Sin límite",
                ["VideoSettingsTab"] = @"Vídeo",
                ["Vsync"] = @"sincronización vertical",
                ["EnableScrollingWorldZoom"] = @"Habilite el desplazamiento para cambiar la escala mundial en el juego",
                ["WorldScale"] = @"Escala mundial",
            },
            ["Parties"] = new JObject
            {
                ["InFight"] = @"¡Actualmente estás peleando!",
                ["InvitePrompt"] = @"{00} te ha invitado a su fiesta. ¿Aceptas?",
                ["Kick"] = @"Patada {00}",
                ["KickLabel"] = @"patada",
                ["Leader"] = @"Líder",
                ["LeaderTip"] = @"líder del partido",
                ["Leave"] = @"Dejar la fiesta",
                ["LeaveTip"] = @"dejar propina",
                ["Name"] = @"{00} - Nv. {01}",
                ["PartyInvite"] = @"Invitación a la fiesta",
                ["Title"] = @"fiesta",
                ["Vital0"] = @"HP:",
                ["Vital0Value"] = @"{00} / {01}",
                ["Vital1"] = @"diputado:",
                ["Vital1Value"] = @"{00} / {01}",
            },
            ["QuestLog"] = new JObject
            {
                ["Abandon"] = @"abandonar",
                ["AbandonPrompt"] = @"¿Estás seguro de que quieres abandonar la misión ""{00}""?",
                ["AbandonTitle"] = @"Abandonar misión: {00}",
                ["Back"] = @"Atrás",
                ["Completed"] = @"Misión completada",
                ["CurrentTask"] = @"Tarea actual:",
                ["InProgress"] = @"Misión en progreso",
                ["NotStarted"] = @"Misión no iniciada",
                ["TaskItem"] = @"{00}/{01} {02}(s) reunidos.",
                ["TaskNpc"] = @"{00}/{01} {02}(s) asesinado.",
                ["Title"] = @"Registro de misiones",
            },
            ["QuestOffer"] = new JObject
            {
                ["Accept"] = @"Aceptar",
                ["Decline"] = @"Rechazar",
                ["Title"] = @"Oferta de misión",
            },
            ["QuestRewardExp"] = new JObject
            {
                ["PlayerExpTooltip"] = @"EXP del jugador",
                ["JobExpTooltip"] = @"{0} EXP",
                ["JobGenericTooltip"] = @"EXP de trabajo",
                ["GuildExpTooltip"] = @"EXP del gremio",
                ["FactionHonorTooltip"] = @"{0} Honor",
                ["FactionHonorGenericTooltip"] = @"Honor de facción",
                ["FactionNeutralName"] = @"Neutro",
                ["FactionSerolfName"] = @"Serlof",
                ["FactionNidrajName"] = @"Nidraj",
            },
            ["Regex"] = new JObject
            {
                ["Password"] = @"^[-_=\+`~!@#\$%\^&\*()\[\]{}\\|;\:'"",<\.>/\?a-zA-Z0-9]{4,64}$",
                ["Username"] = @"^[a-zA-Z0-9]{2,20}$",
            },
            ["Registration"] = new JObject
            {
                ["Back"] = @"Atrás",
                ["ConfirmPassword"] = @"Confirmar contraseña:",
                ["Email"] = @"Correo electrónico:",
                ["EmailInvalid"] = @"El correo electrónico no es válido.",
                ["Password"] = @"Contraseña:",
                ["PasswordMismatch"] = @"Las contraseñas no coinciden.",
                ["Register"] = @"Registrarse",
                ["Title"] = @"Registrarse",
                ["Username"] = @"Nombre de usuario:",
            },
            ["PasswordChange"] = new JObject
            {
                ["Back"] = @"Cancelar",
                ["ConfirmNewPassword"] = @"Confirmar nueva contraseña",
                ["ErrorNoResetCode"] = @"Por favor ingresa tu código de reinicio",
                ["ErrorNoOldPassword"] = @"Por favor ingrese su contraseña anterior",
                ["ErrorNoNewPassword"] = @"Por favor ingrese su nueva contraseña",
                ["ErrorNoNewPasswordConfirmation"] = @"Por favor confirma tu nueva contraseña",
                ["AlertTitleError"] = @"¡Error!",
                ["InputLabelResetCode"] = @"Restablecer código",
                ["InputLabelPassword"] = @"Contraseña antigua",
                ["NewPassword"] = @"Nueva contraseña",
                ["Submit"] = @"Enviar",
                ["AlertTitleSuccess"] = @"¡Éxito!",
                ["Title"] = @"Restablecer contraseña",
            },
            ["Server"] = new JObject
            {
                ["Connecting"] = @"Conectando...",
                ["Failed"] = @"Error de red",
                ["HandshakeFailure"] = @"Error de apretón de manos",
                ["Offline"] = @"Sin conexión",
                ["Online"] = @"En línea",
                ["ServerFull"] = @"El servidor está lleno",
                ["StatusLabel"] = @"Estado del servidor: {00}",
                ["Unknown"] = @"Desconocido",
                ["VersionMismatch"] = @"La versión no coincide",
            },
            ["Shop"] = new JObject
            {
                ["Title"] = @"Tienda",
                ["BuyItem"] = @"Comprar artículo",
                ["BuyItemPrompt"] = @"¿Cuántas unidades de {00} te gustaría comprar?",
                ["CannotSell"] = @"¡Esta tienda no acepta ese artículo!",
                ["Costs"] = @"Costos {00} {01}(s)",
                ["SellItem"] = @"Vender artículo",
                ["SellItemPrompt"] = @"¿Cuántas unidades de {00} le gustaría vender?",
                ["SellPrompt"] = @"¿Desea vender el artículo: {00}?",
                ["SellsFor"] = @"Se vende por {00} {01}(s)",
                ["WontBuy"] = @"La tienda no comprará este artículo",
            },
            ["SpellDescription"] = new JObject
            {
                ["Bound"] = @"No se puede desaprender.",
                ["CastTime"] = @"Hora de lanzamiento:",
                ["Cooldown"] = @"Enfriamiento:",
                ["CooldownGroup"] = @"Grupo de enfriamiento:",
                ["CritChance"] = @"Oportunidad crítica:",
                ["CritMultiplier"] = @"Multiplicador crítico:",
                ["DamageType"] = @"Tipo de daño:",
                ["Distance"] = @"Distancia:",
                ["DoT"] = @"Daños a lo largo del tiempo",
                ["Duration"] = @"Duración:",
                ["Effect"] = @"Efecto:",
                ["Friendly"] = @"Hechizo de apoyo",
                ["HoT"] = @"Cura con el tiempo",
                ["IgnoreConsumedResourceBlock"] = @"Ignora los recursos consumidos",
                ["IgnoreCooldownReduction"] = @"Ignora la reducción de tiempo de reutilización",
                ["IgnoreGlobalCooldown"] = @"Ignora el enfriamiento global",
                ["IgnoreMapBlock"] = @"Ignora los bloques del mapa",
                ["IgnoreResourceBlock"] = @"Ignora los recursos activos",
                ["IgnoreZDimension"] = @"Ignora las diferencias de altura",
                ["Instant"] = @"Instante",
                ["Level"] = @"Nivel:",
                ["Multiplier"] = @"{00}x",
                ["Percentage"] = @"{00}%",
                ["RegularAndPercentage"] = @"{00} + {01}%",
                ["ScalingPercentage"] = @"Porcentaje de escala:",
                ["ScalingStat"] = @"Estadísticas de escala:",
                ["StatBuff"] = @"Mejora de estadísticas",
                ["Tick"] = @"Marca cada:",
                ["Tiles"] = @"{00} Azulejos",
                ["Unfriendly"] = @"Hechizo dañino",
            },
            ["Spells"] = new JObject
            {
                ["ForgetSpell"] = @"Olvidar hechizo",
                ["ForgetSpellPrompt"] = @"¿Estás seguro de que quieres olvidar a {00}?",
                ["Title"] = @"Hechizos",
                ["EmptySlot"] = @"Ranura de hechizo vacía",
            },
            ["Trading"] = new JObject
            {
                ["Accept"] = @"Aceptar",
                ["InFight"] = @"¡Actualmente estás peleando!",
                ["OfferItem"] = @"Artículo de oferta",
                ["OfferItemPrompt"] = @"¿Cuántas unidades de {00} te gustaría ofrecer?",
                ["Pending"] = @"Pendiente",
                ["RevokeItem"] = @"Revocar artículo",
                ["RevokeItemPrompt"] = @"¿Cuántas unidades de {00} le gustaría revocar?",
                ["TheirOffer"] = @"Su oferta:",
                ["Title"] = @"Negociar con {00}",
                ["TradeRequest"] = @"Invitación comercial",
                ["Value"] = @"Valor: {00}",
                ["YourOffer"] = @"Su oferta:",
                ["OtherPlayer"] = @"El otro jugador ha aceptado el intercambio.",
                ["TooFast"] = @"¡Estás enviando mensajes demasiado rápido! Espere por favor.",
                ["Muted"] = @"No puedes enviar mensajes comerciales mientras estás silenciado.",
                ["Format"] = @"[Comercio] {00}: {01}",
                ["SELL"] = @"[VENDER]",
                ["BUY"] = @"[COMPRAR]",
            },
            ["EscapeMenu"] = new JObject
            {
                ["CharacterSelect"] = @"Personajes",
                ["Close"] = @"Cerrar",
                ["ExitToDesktop"] = @"Escritorio",
                ["Logout"] = @"Cerrar sesión",
                ["Settings"] = @"Configuración",
                ["Title"] = @"Menú",
            },
            ["Numbers"] = new JObject
            {
                ["Billions"] = @"b",
                ["Comma"] = @",",
                ["Decimal"] = @".",
                ["Millions"] = @"m",
                ["Thousands"] = @"k",
            },
            ["Update"] = new JObject
            {
                ["Checking"] = @"Buscando actualizaciones, espere.",
                ["Done"] = @"¡Actualización completada! Iniciando el juego.",
                ["Error"] = @"¡Error de actualización! Consulte los registros para obtener más información.",
                ["FilesRemaining"] = @"{00} archivos restantes",
                ["PercentComplete"] = @"{00}%",
                ["RemainingSize"] = @"{00} restante",
                ["Restart"] = @"¡Actualización completada! Reinicie {00} para jugar.",
                ["Updating"] = @"Descargando actualizaciones, espere.",
            },
            ["GameWindow"] = new JObject
            {
                ["EntityNameAndLevel"] = @"{00} [Nivel. {01}]",
            },
        };
    }
}
