using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace Intersect.Server.Localization;

internal static partial class ServerLocalizationOverrides
{
    private static partial void AddEsOverrides(IDictionary<string, JObject> overrides)
    {
        overrides["es"] = new JObject
        {
            ["Account"] = new JObject
            {
                ["AccountAlreadyExists"] = "¡La cuenta ya existe!",
                ["AccountDoesNotExist"] = "La cuenta no existe.",
                ["AdminOnly"] = "El servidor solo permite conectarse a administradores. ¡Vuelve más tarde!",
                ["AlreadyBanned"] = "{00} ya ha sido baneado.",
                ["AlreadyMuted"] = "{00} ya ha sido silenciado.",
                ["BadAccess"] = "¡Acceso denegado! ¡Nivel de poder inválido!",
                ["BadLogin"] = "Nombre de usuario o contraseña incorrectos.",
                ["BanStatus"] = "Tu cuenta ha sido baneada desde: {00} (UTC) por {01}. El baneo expira: {02} (UTC). Motivo del baneo: {03}",
                ["Banned"] = "¡{00} ha sido baneado!",
                ["CharacterExists"] = "Ya existe una cuenta con este nombre de personaje. Elige otro.",
                ["CharacterDeleted"] = "El personaje ha sido eliminado.",
                ["DeleteCharacterError"] = "Este personaje no se puede eliminar, puede estar conectado en combate.",
                ["EmailExists"] = "Ya existe una cuenta con esta dirección de correo electrónico.",
                ["EmailFail"] = "No se pudo enviar el correo de restablecimiento de contraseña en este momento. Inténtalo más tarde.",
                ["InvalidClass"] = "Clase inválida seleccionada. Inténtalo de nuevo.",
                ["InvalidEmail"] = "El correo elegido no cumple con los requisitos establecidos por el servidor.",
                ["InvalidName"] = "El nombre elegido no cumple con los requisitos establecidos por el servidor.",
                ["LoadFail"] = "No se pudo cargar la cuenta. Intenta iniciar sesión de nuevo.",
                ["PlayerSavingTryAgainLater"] = "'{00}' se está guardando actualmente, inténtalo más tarde.",
                ["MaxCharacters"] = "Ya has creado el número máximo de personajes. Elimina uno antes de crear otro.",
                ["Muted"] = "¡{00} ha sido silenciado!",
                ["MuteStatus"] = "Tu cuenta ha sido silenciada desde: {00} por {01}. El silencio expira: {02}. Motivo del silencio: {03}",
                ["NotAllowed"] = "No tienes permiso para hacer esto.",
                ["NotFound"] = "Error: ¡No se encontró la cuenta {00}!",
                ["RegistrationsBlocked"] = "Los registros de cuentas están bloqueados por el servidor.",
                ["UnbanFail"] = "No se pudo desbanear a {00}. ¡El usuario no está baneado!",
                ["UnbanSuccess"] = "¡{00} ha sido desbaneado!",
                ["UnknownErrorWhileSaving"] = "Ocurrió un error desconocido al guardar el usuario.",
                ["UnknownServerErrorRetryLogin"] = "Ocurrió un error desconocido del servidor, intenta iniciar sesión de nuevo.",
                ["UnmuteFail"] = "No se pudo desilenciar a {00}. ¡El usuario no está silenciado!",
                ["UnmuteSuccess"] = "¡{00} ha sido desilenciado!",
            },
            ["Alignment"] = new JObject
            {
                ["ChangedTo"] = "Ahora perteneces a {00}.",
                ["AlreadyInFaction"] = "Ya perteneces a esta facción.",
                ["GuildMismatch"] = "Tu gremio pertenece a una facción distinta.",
                ["WingsOn"] = "No puedes cambiar de facción mientras tus alas estén activadas.",
                ["WingsNeutral"] = "No puedes activar tus alas mientras estés en la facción neutral.",
                ["SwapCooldown"] = "Podrás cambiar nuevamente el {date}.",
            },
            ["Bag"] = new JObject
            {
                ["BagInBag"] = "¡No puedes guardar una bolsa dentro de otra bolsa!",
                ["BagInSelf"] = "¡No puedes guardar una bolsa dentro de sí misma!",
                ["DropNotEmpty"] = "¡No puedes dejar caer una bolsa a menos que esté vacía!",
                ["OnlySellEmpty"] = "¡No se puede vender la bolsa a menos que esté vacía!",
                ["OnlyTradeEmpty"] = "¡No se puede intercambiar la bolsa a menos que esté vacía!",
                ["SlotOccupied"] = "¡Ese espacio está ocupado por otro objeto!",
                ["WithdrawInvalid"] = "¡Artículo no válido seleccionado para recuperar!",
            },
            ["Bank"] = new JObject
            {
                ["DepositInvalid"] = "¡Artículo no válido seleccionado para depositar!",
                ["DepositSuccessNonStackable"] = "Has almacenado: {00}",
                ["DepositSuccessStackable"] = "Tienes almacenado: {00} {01}",
                ["InvalidSlotToSwap"] = "¡Espacios no válidos para intercambiar!",
                ["NotEnoughInInventory"] = "No hay {00} de {01} en su inventario para depositar.",
                ["NotEnoughBankSpaceForItem"] = "¡No hay suficiente espacio en el banco para almacenar {00} de {01}!",
                ["NotEnoughBankSpaceForOneOfItem"] = "¡No hay suficiente espacio en el banco para almacenar un {00}!",
                ["WithdrawInvalid"] = "¡Artículo no válido seleccionado para retirar!",
                ["WithdrawSuccessNonStackable"] = "Has retirado: {00}",
                ["WithdrawSuccessStackable"] = "Has retirado: {00} {01}",
            },
            ["Chat"] = new JObject
            {
                ["Admin"] = "[ADMIN] {00}: {01}",
                ["AdminCommand"] = "/admin",
                ["AllCommand"] = "/all",
                ["Announcement"] = "[ANNOUNCEMENT] {00}: {01}",
                ["AnnouncementCommand"] = "/announcement",
                ["Global"] = "[GLOBAL] {00}: {01}",
                ["GlobalCommand"] = "/global",
                ["Local"] = "{00}: {01}",
                ["LocalCommand"] = "/local",
                ["MessageCommand"] = "/message",
                ["Party"] = "[PARTY] {00}: {01}",
                ["PartyCommand"] = "/party",
                ["PrivateFrom"] = "[PM] Desde {00}: {01}",
                ["PrivateTo"] = "[PM] a {00}: {01}",
                ["PrivateMessageCommand"] = "/pm",
                ["ReplyCommand"] = "/reply",
                ["ReplyShortcutCommand"] = "/r",
                ["TooFast"] = "¡Estás charlando demasiado rápido!",
                ["Trade"] = "[MARKET] {00}: {01}",
                ["TradeCommand"] = "/trade",
                ["TradeNotAllowed"] = "¡Aún no puedes comerciar!",
            },
            ["Class"] = new JObject
            {
                ["LastClass"] = "última clase",
                ["LastClassError"] = "No se pudo eliminar la clase. ¡Debes tener al menos una clase en todo momento!",
            },
            ["Color"] = new JObject
            {
            },
            ["Combat"] = new JObject
            {
                ["AddSymbol"] = "+",
                ["Blocked"] = "¡BLOQUEADO!",
                ["Channeling"] = "Actualmente estás canalizando otra habilidad.",
                ["ChannelingNoAttack"] = "Actualmente estás canalizando un hechizo, no puedes atacar.",
                ["Cooldown"] = "Esta habilidad está en tiempo de reutilización.",
                ["Critical"] = "¡GOLPE CRÍTICO!",
                ["Dash"] = "¡DASH!",
                ["DynamicRequirement"] = "¡No cumples con los requisitos para lanzar el hechizo!",
                ["ImmuneToEffect"] = "¡INMUNE!",
                ["LevelDown"] = "¡BAJA DE NIVEL!",
                ["LevelUp"] = "¡SUBE DE NIVEL!",
                ["Vampirism"] = "¡VAMPIRISMO!",
                ["LowHealth"] = "No hay suficiente salud.",
                ["LowMana"] = "No hay suficiente maná.",
                ["Miss"] = "¡FALLO!",
                ["RemoveSymbol"] = "-",
                ["ResourceRequirements"] = "¡No cumples con los requisitos para cosechar este recurso!",
                ["Silenced"] = "No puedes lanzar esta habilidad mientras estás silenciado.",
                ["Sleep"] = "No puedes lanzar esta habilidad mientras duermes.",
                ["Snared"] = "No puedes lanzar esta habilidad mientras estás atrapado.",
                ["SleepAttacking"] = "Estás dormido y no puedes atacar.",
                ["SleepBlocking"] = "Estás dormido y no puedes bloquear.",
                ["StunAttacking"] = "Estás aturdido y no puedes atacar.",
                ["StunBlocking"] = "Estás aturdido y no puedes bloquear.",
                ["Stunned"] = "No puedes lanzar esta habilidad mientras estás aturdido.",
                ["TargetOutOfRange"] = "¡El objetivo está fuera de alcance!",
                ["ToolRequired"] = "¡Necesitas un {00} para interactuar con este recurso!",
                ["TryForgetBoundSpell"] = "No puedes olvidar este hechizo.",
                ["InvalidTarget"] = "Objetivo no válido para este hechizo.",
            },
            ["CommandOutput"] = new JObject
            {
                ["AccountCount"] = " - {00} Cuentas.",
                ["ActiveConnections"] = "Conexiones activas: {00}",
                ["ApiAccessGranted"] = "¡{00} ahora tiene acceso API!",
                ["ApiAccessRevoked"] = "¡A {00} se le ha revocado el acceso a API!",
                ["ApiRoleGranted"] = "¡{00} ahora tiene el rol {01} API!",
                ["ApiRoleNotFound"] = "API rol {00} ¡no encontrado!",
                ["ApiRoleNotGranted"] = "No se pudo asignar el rol API {00}, ¡el acceso API debe habilitarse para {01} primero!",
                ["ApiRolePrerequisite"] = "¡No se pudo otorgar el rol API {00}! Depende del rol {01}.",
                ["ApiRoleRevoked"] = "¡A {00} se le ha revocado su función {01} API!",
                ["ApiRoles"] = "Funciones API para {00}:",
                ["ApiRolesNotGranted"] = "No se han otorgado roles API.",
                ["CharacterCount"] = " - {00} Personajes.",
                ["CpsLocked"] = "CPS Bloqueado",
                ["CpsUnlocked"] = "CPS Desbloqueado",
                ["EventCount"] = " - {00} Eventos.",
                ["ExperimentalFeatureEnablement"] = "{00} es {01}.",
                ["GameTime"] = "El tiempo de juego es ahora: {00}",
                ["HelpFooter"] = "Escriba cualquier comando seguido de {00} para obtener parámetros e información de uso.",
                ["HelpHeader"] = "Lista de comandos disponibles:",
                ["ItemCount"] = " - {00} Artículos.",
                ["SetCount"] = " - {00} Conjuntos.",
                ["KillSuccess"] = "¡{00} ha sido asesinado!",
                ["ListAccount"] = "Cuenta",
                ["ListCharacter"] = "Personaje",
                ["ListId"] = "ID",
                ["MapCount"] = " - {00} Mapas.",
                ["MetricsDisabled"] = "Recopilación de métricas inhabilitada",
                ["MetricsEnabled"] = "Recopilación de métricas habilitada",
                ["NoClientsConnected"] = "No hay clientes conectados",
                ["NpcCount"] = " - {00} NPCs.",
                ["PowerChanged"] = "¡{00} ha actualizado su poder!",
                ["ServerInfo"] = "El servidor tiene:",
                ["SpellCount"] = " - {00} Hechizos.",
                ["StrayConnections"] = "Conexiones perdidas: {00}",
                ["VariableChanged"] = "'{01}' establecido en {02} (era {03}) ({00})",
                ["VariableListEmpty"] = "No hay variables para mostrar.",
                ["VariableNotFound"] = "Variable '{00}' no encontrada",
                ["VariablePrint"] = "{00} {01} = {02}",
            },
            ["Crafting"] = new JObject
            {
                ["AlreadyCrafting"] = "¡Ya estás creando un artículo!",
                ["CraftFailure"] = "¡El intento de crear el artículo {00} falló!",
                ["CraftFailureLostItems"] = "¡El intento de crear el artículo {00} falló y perdiste los materiales!",
                ["Crafted"] = "¡Has creado con éxito {00}!",
                ["InJournalMode"] = "¡No puedes crear artículos desde tu diario de artesanía!",
                ["NoSpace"] = "¡No tienes suficiente espacio en el inventario para crear {00}!",
                ["RequirementsNotMet"] = "¡No cumples con los requisitos para crear este artículo!",
                ["JobExperience"] = "Has recibido {00} puntos de experiencia en {01}.",
                ["UnknownJobType"] = "El tipo de trabajo {00} no se reconoce.",
            },
            ["Database"] = new JObject
            {
                ["Default"] = "Por defecto",
                ["MigratingAutomatically"] = "El indicador --migrate-automatically se pasó al servidor al inicio, por lo que no se le solicitará al usuario.",
                ["NoClasses"] = "¡No se encontraron clases! Creando una clase predeterminada.",
                ["NoMaps"] = "¡No se encontraron mapas! Creando un mapa vacío.",
                ["UpgradeBackup"] = "Haga una copia de seguridad de sus bases de datos de juegos y jugadores, luego escriba '{00}' para continuar o '{01}' para salir.",
                ["UpgradeExit"] = "EXIT",
                ["UpgradeReady"] = "READY",
                ["UpgradeRequired"] = "¡Sus bases de datos deben actualizarse! Este proceso podría dañar los datos de tu juego si se encuentra algún error.",
            },
            ["Errors"] = new JObject
            {
                ["ErrorFloodBurst"] = "[Flood]: {00} Paquetes en ráfaga [Usuario: {01} | Jugador: {02} | IP {03}]",
                ["ErrorFloodSize"] = "[Flood]: Tamaño del paquete: {00} [Usuario: {01} | Jugador: {02} | IP {03}]",
                ["ErrorLoadingConfiguration"] = "¡Error al cargar las opciones del servidor! Presione cualquier tecla para apagar.",
                ["ErrorLoadingStrings"] = "¡No se pudieron cargar las cadenas! Presione cualquier tecla para apagar.",
                ["ErrorLogged"] = "Se registró un error en errores.log.",
                ["ErrorServerCrash"] = "El servidor Intersect ha encontrado un error y debe cerrarse. La información del error se puede encontrar en resources/logs/errors.log. Presione enter para salir.",
                ["ErrorServerCrashNoHalt"] = "El servidor Intersect ha encontrado un error y debe cerrarse. La información del error se puede encontrar en resources/logs/errors.log.",
                ["ErrorTimeout"] = "Demasiadas solicitudes fallidas. ¡Espera e inténtalo de nuevo!",
                ["UnknownErrorTryAgain"] = "Se produjo un error desconocido, inténtelo nuevamente.",
            },
            ["Events"] = new JObject
            {
                ["CommandParameter"] = "\\param",
                ["EventNameCommand"] = "\\en",
                ["EventParameter"] = "\\evtparam",
                ["EventParameters"] = "\\evtparams",
                ["GlobalSwitch"] = "\\gs",
                ["GlobalVariable"] = "\\gv",
                ["GuildVariable"] = "\\guildvar",
                ["MilitaryHour"] = "\\24hour",
                ["OnlineCountCommand"] = "\\onlinecount",
                ["OnlineListCommand"] = "\\onlinelist",
                ["PeriodEvening"] = "PM",
                ["PeriodMorning"] = "AM",
                ["PlayerGuildCommand"] = "\\pg",
                ["PlayerNameCommand"] = "\\pn",
                ["PlayerSwitch"] = "\\ps",
                ["PlayerVariable"] = "\\pv",
                ["TimeHour"] = "\\hour",
                ["TimeMinute"] = "\\minute",
                ["TimePeriod"] = "\\period",
                ["TimeSecond"] = "\\second",
                ["UserVariable"] = "\\uservar",
                ["WatchdogKill"] = "El evento finalizó debido a que los comandos procesados ​​en un solo cuadro superaron el umbral de vigilancia de eventos. (Mapa: {00} Evento: {01})",
                ["WatchdogKillCommon"] = "Evento común eliminado debido a que los comandos procesados ​​en un solo cuadro superan el umbral de vigilancia de eventos. (Evento {00})",
            },
            ["Formulas"] = new JObject
            {
                ["Missing"] = "Falta el archivo Formulas.json. Se ha generado un archivo de fórmulas predeterminado.",
            },
            ["Friends"] = new JObject
            {
                ["Accept"] = "¡{00} ha aceptado tu solicitud de amistad!",
                ["AlreadyFriends"] = "Ya eres amigo de {00}.",
                ["Busy"] = "{00} está actualmente ocupado. Inténtelo de nuevo más tarde.",
                ["FriendLoggedIn"] = "{00} ha iniciado sesión.",
                ["FriendNotification"] = "¡Ahora eres amigo de {00}!",
                ["FriendRemoved"] = "El amigo ha sido eliminado.",
                ["FriendRequestSent"] = "Se ha enviado la solicitud de amistad.",
            },
            ["General"] = new JObject
            {
                ["DisabledLowerCase"] = "desactivado",
                ["EnabledLowerCase"] = "activado",
                ["Notice"] = "Aviso",
                ["NoticeError"] = "Aviso de error",
                ["UnknownErrorPleaseTryAgain"] = "Se produjo un error desconocido, inténtelo nuevamente.",
            },
            ["Guilds"] = new JObject
            {
                ["AlreadyInGuild"] = "¡Ya estás en un gremio!",
                ["Demoted"] = "¡{00} ha sido degradado a {01}!",
                ["DisbandGuild"] = "¡{00} ha sido disuelto!",
                ["ErrorWhileAcceptingInvite"] = "Ocurrió un error al guardar tu membresía del gremio, inténtalo de nuevo.",
                ["GuildChat"] = "[{00}] {01}: {02}",
                ["GuildCommand"] = "/guild",
                ["GuildLeaderLeave"] = "Un Guildmaster no puede abandonar su propio gremio. ¡Primero transfiera los derechos de propiedad!",
                ["GuildNameInUse"] = "¡El nombre de tu gremio elegido ya está en uso!",
                ["InviteAlreadyInGuild"] = "El jugador al que intentas invitar ya está en un gremio o tiene una invitación pendiente.",
                ["InviteDifferentFaction"] = "No puedes invitar a jugadores de una facción diferente.",
                ["InviteDeclined"] = "Ha rechazado la solicitud para unirse a {00}.",
                ["InviteDeclinedMissingGuild"] = "Has rechazado la solicitud para unirte al gremio.",
                ["InviteDeclinedResponse"] = "{00} ha rechazado su solicitud para unirse a {01}.",
                ["InviteDeclinedResponseMissingGuild"] = "{00} ha rechazado tu solicitud para unirse al gremio.",
                ["InviteNotOnline"] = "El jugador al que intentas invitar no está en línea o no existe.",
                ["InviteSent"] = "¡Has invitado a {00} a unirse a {01}!",
                ["NoLongerAllowedInInstance"] = "Ya no estás en el gremio en cuya instancia iniciaste sesión. Has sido transportado de regreso al supramundo.",
                ["NoSuchPlayer"] = "No existe tal jugador en este gremio.",
                ["NotAllowed"] = "No tienes permiso para hacer esto.",
                ["NotAllowedDeposit"] = "¡No tienes permiso para depositar artículos en el banco del gremio de {00}!",
                ["NotAllowedInInstance"] = "Debes estar en un gremio para pasar a una instancia de gremio.",
                ["NotAllowedSwap"] = "¡No tienes permiso para intercambiar artículos dentro del banco del gremio de {00}!",
                ["NotAllowedWithdraw"] = "¡No tienes permiso para retirar dinero del banco del gremio de {00}!",
                ["NotInGuild"] = "No estás en un gremio.",
                ["NotReceivedInvite"] = "Aún no has recibido ninguna invitación al gremio.",
                ["DifferentFaction"] = "Tu facción no coincide con la facción del gremio.",
                ["FactionApplied"] = "Tu facción ha sido cambiada para que coincida con la del gremio.",
                ["Promoted"] = "¡{00} ha sido ascendido a {01}!",
                ["RankLimit"] = "¡No pude unirme a {00} porque su gremio está lleno!",
                ["RankLimitResponse"] = "Este gremio ya alcanzó su límite de miembros para el rango {00}. Ascender o degradar a otros miembros para dejar espacio para {01}.",
                ["Transferred"] = "¡La propiedad del gremio de {00} ha sido transferida de {01} a {02}!",
                ["VariableInvalid"] = "¡Nombre de gremio no válido!",
                ["VariableNotString"] = "El nombre del gremio proporcionado no contiene ningún texto.",
                ["Welcome"] = "¡Bienvenido a {00}!",
                ["DeleteGuildLeader"] = "No puedes eliminar un personaje que sea un gremio {00}. Disuelve el gremio o transfiere la propiedad antes de volver a intentarlo.",
                ["GuildCreated"] = "¡El gremio se ha creado con éxito!",
                ["GuildCreationFailed"] = "No se pudo crear el gremio. Por favor inténtalo de nuevo.",
            },
            ["Intro"] = new JObject
            {
                ["ConsoleActive"] = "Escriba \"exit\" para cerrar el servidor o \"help\" para obtener una lista de comandos.",
                ["Loading"] = "Cargando, por favor espera.",
                ["ServerStarted"] = "Servidor iniciado. Usando el puerto UDP #{00}.",
                ["Support"] = "Para obtener ayuda, soporte y actualizaciones, visite: https://www.ascensiongamedev.com",
                ["Tagline"] = "Motor ORPG 2D gratuito",
                ["Version"] = "Versión {00}",
            },
            ["Items"] = new JObject
            {
                ["Bound"] = "No puedes soltar este artículo.",
                ["CannotUse"] = "¡No puedes usar este artículo!",
                ["Cooldown"] = "¡Debes esperar antes de volver a usar este artículo!",
                ["DynamicRequirement"] = "¡No cumples con los requisitos para utilizar este artículo!",
                ["Equipped"] = "No puedes dejar caer objetos equipados.",
                ["NoBag"] = "No puedes guardar este artículo en una bolsa.",
                ["NoBank"] = "No puede almacenar este artículo en un banco.",
                ["NoSpaceForItem"] = "¡No queda espacio para ese artículo!",
                ["NotEnough"] = "¡No hay suficientes {00}s!",
                ["NotImplemented"] = "El uso de este tipo de elemento aún no está implementado.",
                ["Sleep"] = "No puedes utilizar este artículo mientras duermes.",
                ["Stunned"] = "No puedes usar este objeto mientras estás aturdido.",
            },
            ["Sets"] = new JObject
            {
                ["DeleteSet"] = "Eliminar conjunto",
                ["DeleteSetInUse"] = "No se puede eliminar el conjunto mientras los elementos todavía hagan referencia a él.",
            },
            ["Mapping"] = new JObject
            {
                ["LastMap"] = "Último mapa",
                ["LastMapError"] = "No se pudo eliminar el mapa. ¡Debes tener al menos un mapa en todo momento!",
                ["LinkFailure"] = "Error en el enlace del mapa",
                ["LinkFailureError"] = "No se pudo vincular el mapa {00} al mapa {01}. Si esta fusión ocurriera, los mapas {02} y {03} ocuparían el mismo espacio en el mundo.",
                ["NewFolder"] = "Nueva carpeta",
            },
            ["Migration"] = new JObject
            {
                ["AlreadyUsingProvider"] = "Error de migración: ¡La base de datos {00} ya está usando {01}!",
                ["Cancel"] = "Presione cualquier otra tecla para cancelar la migración.",
                ["ConfirmCharacter"] = "y",
                ["DatabaseFileAlreadyExists"] = "{00} ya existe. ¿Sobrescribir? (y/n)",
                ["DefaultDatabase"] = "intersect_{00}_{01}",
                ["DefaultHost"] = "localhost",
                ["DefaultPortMySql"] = "3306",
                ["DefaultUsername"] = "root",
                ["EnterConnectionStringParameters"] = "Por favor ingrese los parámetros de su cadena de conexión:",
                ["GameDatabaseName"] = "Juego",
                ["LoggingDatabaseName"] = "Logging",
                ["MigratingDbSet"] = "Migrando entidades en {00}...",
                ["MigrationCanceled"] = "Migración cancelada",
                ["MigrationComplete"] = "¡Migración completa! Presione enter para salir.",
                ["MySqlConnecting"] = "Espere, intentando conectarse a la base de datos...",
                ["MySqlConnectionError"] = "¡Error al abrir la conexión a la base de datos! Error: {00}",
                ["MySqlNotEmpty"] = "¡La base de datos debe estar vacía antes de la migración! Elimine cualquier tabla antes de continuar. Migración cancelada.",
                ["MySqlTryAgain"] = "¿Le gustaría intentar ingresar su información de conexión nuevamente? (y/n)",
                ["PlayerDatabaseName"] = "Jugador",
                ["PromptDatabase"] = "Base de datos ({00}):",
                ["PromptHost"] = "Anfitrión ({00}):",
                ["PromptPassword"] = "Contraseña (vacía):",
                ["PromptPort"] = "Puerto ({00}):",
                ["PromptUsername"] = "Usuario ({00}):",
                ["SelectContext"] = "¿Qué base de datos le gustaría migrar?",
                ["SelectDatabase"] = "[{00}] {01} (actualmente usando {02}) {03}",
                ["SelectDatabaseType"] = "[{00}] {01}",
                ["SelectProvider"] = "Seleccione a qué motor migrar la base de datos {00}:",
                ["SqliteRecommended"] = "¡Se recomienda encarecidamente SQLite!",
                ["StartingMigration"] = "Iniciando la migración, ¡espere! Esto podría tardar varios minutos dependiendo del tamaño de tu juego.",
                ["StoppingServer"] = "Espere, detenga el servidor y guarde la base de datos actual...",
                ["TryAgainCharacter"] = "y",
            },
            ["NetDebug"] = new JObject
            {
                ["Hastebin"] = "Información de depuración de red cargada en {00} (copiada al portapapeles). ¡Comparte este enlace con AGD cuando solicites ayuda para poner tu juego en línea!",
                ["PleaseWait"] = "Espere mientras se ejecuta el diagnóstico de red...",
                ["SavedToFile"] = "¡Información de depuración de red guardada en netdebug.txt! ¡Sube ese archivo y compártelo con AGD cuando solicites ayuda para poner tu juego en línea!",
            },
            ["Networking"] = new JObject
            {
                ["ServerFull"] = "El servidor está actualmente lleno. Inténtelo de nuevo más tarde.",
            },
            ["Notifications"] = new JObject
            {
                ["Copyright"] = "Copyright (c) 2020-2025 Ascension Game Dev, Todos los derechos reservados",
                ["Product"] = "Motor de juego Intersect",
            },
            ["Parties"] = new JObject
            {
                ["AlreadyDenied"] = "¡Tu invitación a la fiesta ya ha sido rechazada!",
                ["Busy"] = "{00} está ocupado. ¡Inténtelo de nuevo más tarde!",
                ["CannotCreateInstance"] = "Sólo el líder del partido puede crear una instancia compartida.",
                ["Declined"] = "¡{00} ha rechazado tu invitación a la fiesta!",
                ["Disbanded"] = "El partido ha sido disuelto.",
                ["InInstance"] = "¡No puedes invitar a alguien a una fiesta mientras estás en una instancia!",
                ["InstanceFailed"] = "Su partido ha fallado en la instancia...",
                ["InstanceInProgress"] = "El partido aún no ha concluido su instancia.",
                ["InstanceInUse"] = "No se puede crear una instancia nueva: los miembros del grupo todavía están en la instancia anterior.",
                ["InstanceLivesRemaining"] = "¡A tu grupo le quedan {00} vidas en este caso!",
                ["InParty"] = "¡{00} ya está en una fiesta!",
                ["Joined"] = "¡{00} se ha unido a la fiesta!",
                ["Kicked"] = "¡Te han expulsado de la fiesta!",
                ["LeaderInviteOnly"] = "Sólo el líder del grupo puede enviar invitaciones a su grupo.",
                ["Left"] = "Has abandonado el partido.",
                ["LimitReached"] = "Has alcanzado el límite máximo de miembros del grupo. Expulsa a otro miembro antes de agregar más.",
                ["MemberKicked"] = "¡{00} ha sido expulsado de la fiesta!",
                ["MemberLeft"] = "¡{00} ha abandonado la fiesta!",
                ["NoMoreLivesRemaining"] = "¡A tu grupo no le quedan más vidas! Reaparecerás fuera de la instancia en tu próxima muerte.",
                ["NotInParty"] = "No estás en una fiesta.",
                ["OutOfRange"] = "El objetivo está fuera de alcance o fuera de línea.",
                ["WrongInstance"] = "Su partido actualmente está haciendo una instancia diferente.",
            },
            ["PasswordResetNotification"] = new JObject
            {
                ["Subject"] = "Intersect Game Engine - Código de restablecimiento de contraseña",
            },
            ["Player"] = new JObject
            {
                ["Admin"] = "¡{00} ha recibido poderes administrativos!",
                ["AdminJoined"] = "¡Eres administrador! Presione Insertar en cualquier momento para acceder al menú de administración o F2 para obtener información de depuración.",
                ["AdminSetPower"] = "¡Solo los administradores pueden configurar la energía!",
                ["BeenWarpedTo"] = "Has sido transportado a {00}.",
                ["CannotAlterOwnPower"] = "¡No puedes alterar tu propio poder!",
                ["CannotWarpToYourself"] = "No puedes deformarte a ti mismo.",
                ["Deadmin"] = "¡A {00} se le han revocado sus poderes administrativos!",
                ["HasWarpedTo"] = "{00} ha sido deformado para ti.",
                ["InstanceUpdate"] = "Su ID de instancia ha cambiado de {00} a {01}.",
                ["Kicked"] = "¡{00} ha sido expulsado por {01}!",
                ["Killed"] = "¡{00} ha sido asesinado por {01}!",
                ["Left"] = "{00} ha abandonado {01}.",
                ["LevelLost"] = "¡Has perdido un nivel! ¡Ahora estás en el nivel {00}!",
                ["LevelUp"] = "¡Has subido de nivel! ¡Ahora estás en el nivel {00}!",
                ["Moderator"] = "¡{00} ha recibido poderes de moderación!",
                ["ModeratorJoined"] = "¡Eres moderador! Presione Insertar en cualquier momento para acceder al menú de administración o F2 para obtener información de depuración.",
                ["Offline"] = "¡Usuario no conectado!",
                ["OverworldReturnAdmin"] = "Has devuelto {00} al supramundo.",
                ["OverworldReturned"] = "Has sido devuelto al supramundo.",
                ["PlayerNotFound"] = "¡El jugador '{00}' no fue encontrado!",
                ["InvalidItem"] = "Artículo no válido seleccionado.",
                ["InvalidQuantity"] = "La cantidad debe ser mayor que cero.",
                ["ItemGiveFailed"] = "No se puede dar {00}x {01} a {02}.",
                ["ItemGiveSuccess"] = "Le has dado {00}x {01} a {02}.",
                ["ItemReceivedFromAdmin"] = "{00} te dio {01}x {02}.",
                ["ItemSpawnFailed"] = "No se puede generar {00}x {01} para {02}.",
                ["ItemSpawnSuccess"] = "Generaste {00}x {01} para {02}.",
                ["ItemSpawnedNearYou"] = "{00} generó {01}x {02} cerca de ti.",
                ["PowerChanged"] = "¡Tu poder ha sido modificado!",
                ["ServerKicked"] = "¡{00} ha sido expulsado por el servidor!",
                ["ServerKilled"] = "¡{00} ha sido eliminado por el servidor!",
                ["LearnedSpell"] = "¡Has aprendido el hechizo {00}!",
                ["ForgotSpell"] = "¡Has olvidado el hechizo {00}!",
                ["StatPoints"] = "¡Tienes {00} puntos de estadísticas disponibles para gastar!",
                ["WarpedTo"] = "Deformado a {00}.",
                ["WarpedToYou"] = "{00} se transformó en ti.",
            },
            ["Portchecking"] = new JObject
            {
                ["AntivirusCheck"] = "2. Es posible que los programas antivirus también estén bloqueando las conexiones. Es posible que deba agregar Intersect Server.exe a sus exclusiones de antivirus.",
                ["CheckFirewalls"] = "1. Es posible que los firewalls estén bloqueando las conexiones a su servidor. Verifique los firewalls de su sistema (por ejemplo, iptables, FirewallD, Windows Firewall).",
                ["CheckRouterUpnp"] = "Parece que UPnP falló. Es posible que deba habilitar UPnP en su enrutador o reenviar puertos manualmente para permitir conexiones a su servidor.",
                ["ConnectionInfo"] = "Información de conexión:",
                ["DebuggingSteps"] = "Pasos de depuración (para permitir el acceso público):",
                ["DocumentationUrl"] = "https://docs.freemmorpgmaker.com/en-US/deploy/forwarding/",
                ["PortCheckerAndUpnpDisabled"] = "Tanto el servicio de verificación de puertos como UPnP se han deshabilitado. Verifique el estado del servidor manualmente con un cliente.",
                ["PortNotOpenTryingUpnp"] = "El puerto {0} no está abierto, intentando UPnP...",
                ["PortNotOpenUpnpDisabled"] = "El puerto {0} no está abierto, pero UPnP está deshabilitado. Revisa la redirección de puertos del router y el firewall del equipo.",
                ["ProbablyFirewall"] = "UPnP supuestamente tuvo éxito, pero el servidor no es accesible en el puerto {0}. Revisa el firewall del equipo donde se ejecuta este servidor.",
                ["PublicIp"] = "IP pública: {00}",
                ["PublicPort"] = "Puerto Público: {00}",
                ["RouterUpnpFailed"] = "UPnP falló. Verifica el estado del servidor manualmente usando un cliente.",
                ["TryingUpnp"] = "Intentando abrir el puerto usando UPnP...",
                ["UpnpSucceededPortCheckerDisabled"] = "UPnP tuvo éxito, pero el verificador de puertos está deshabilitado. Verifica el estado del servidor manualmente usando un cliente.",
                ["WithinRestrictedNetwork"] = "3. Si estás en un campus universitario o en una red empresarial, probablemente no tengas permiso para abrir puertos o alojar juegos. En ese caso, considera opciones de hosting externo.",
            },
            ["Quests"] = new JObject
            {
                ["Abandoned"] = "Misión abandonada: {00}!",
                ["Completed"] = "Misión: {00} completada!",
                ["Declined"] = "Misión rechazada: {00}!",
                ["ItemTask"] = "{00} actualizado! ¡{01}/{02} {03}(s) reunidos!",
                ["NpcTask"] = "{00} actualizado! {01}/{02} {03}(s) asesinados!",
                ["Started"] = "Misión iniciada: {00}!",
                ["TaskCompleted"] = "¡Tarea completada!",
                ["Updated"] = "Misión: {00} ¡actualizada!",
            },
            ["Regex"] = new JObject
            {
                ["Email"] = "^(([\\w-]+\\.)+[\\w-]+|([a-zA-Z]{1}|[\\w-]{2,}))@((([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])\\.([0-1]?[0-9]{1,2}|25[0-5]|2[0-4][0-9])){1}|([a-zA-Z]+[\\w-]+\\.)+[a-zA-Z]{2,4})$",
                ["GuildName"] = "^[a-zA-Z0-9 ]{3,20}$",
                ["Username"] = "^[a-zA-Z0-9]{2,20}$",
            },
            ["Shops"] = new JObject
            {
                ["Bound"] = "¡Este artículo está vinculado a usted y no se puede vender!",
                ["CannotAfford"] = "La transacción falló debido a fondos insuficientes.",
                ["DoesNotAccept"] = "¡Esta tienda no acepta ese artículo!",
                ["FailedToRemoveItem"] = "No se pudieron eliminar elementos de la ranura {00} para el jugador {01}. Cantidad a eliminar: {02} a {03}",
                ["InventoryFull"] = "¡No tienes suficiente espacio para comprar ese artículo!",
                ["SuccessfullyRemovedItem"] = "Se eliminaron con éxito {00} elementos de la ranura {01} para el jugador {02} en {03}.",
                ["TransactionFailed"] = "¡La transacción falló!",
            },
            ["Trading"] = new JObject
            {
                ["Accepted"] = "¡El intercambio fue exitoso!",
                ["AlreadyDenied"] = "¡Su solicitud comercial ya ha sido rechazada!",
                ["Bound"] = "¡Este artículo está vinculado a usted y no se puede comercializar!",
                ["Busy"] = "{00} está ocupado. ¡Inténtelo de nuevo más tarde!",
                ["Declined"] = "¡El intercambio fue rechazado!",
                ["InvalidOffer"] = "¡Artículo no válido seleccionado para ofrecer!",
                ["InvalidRevoke"] = "¡Artículo no válido seleccionado para revocar!",
                ["ItemsDropped"] = "Sin espacio en el inventario. ¡Algunos de tus artículos se han caído al suelo!",
                ["OfferAccepted"] = "{00} ha aceptado tu oferta. Por favor confirme el intercambio.",
                ["OutOfRange"] = "El objetivo comercial está fuera de alcance o fuera de línea.",
                ["RevokeNotAllowed"] = "No puedes revocar este artículo, ¡{00} ya aceptó el intercambio!",
            },
            ["Upnp"] = new JObject
            {
                ["FailedForwardingTcp"] = "No se pudo reenviar automáticamente el puerto TCP {00} usando UPnP. Es posible que UPnP esté deshabilitado en la configuración de su enrutador o que este puerto ya esté reenviado.",
                ["FailedForwardingUdp"] = "No se pudo reenviar automáticamente el puerto UDP {00} usando UPnP. Es posible que UPnP esté deshabilitado en la configuración de su enrutador o que este puerto ya esté reenviado.",
                ["ForwardedTcp"] = "El puerto TCP reenviado automáticamente el puerto {00} mediante UPnP.",
                ["ForwardedUdp"] = "El puerto UDP reenviado automáticamente el puerto {00} mediante UPnP.",
                ["InitializationFailed"] = "Error al inicializar el servicio UPnP. Es posible que no tenga un enrutador o que UPnP en su enrutador esté deshabilitado.",
                ["Initialized"] = "La inicialización del servicio UPnP fue exitosa.",
            },
            ["Mail"] = new JObject
            {
                ["inventoryfull"] = "No hay suficiente espacio en tu inventario",
                ["receiveitem"] = "¡Recibiste un artículo!",
                ["playernotfound"] = "¡Jugador no encontrado!",
                ["newmail"] = "¡Has recibido un nuevo correo!",
                ["mailnotfound"] = "¡Correo no encontrado!",
                ["invaliditem"] = "El artículo seleccionado no es válido o no se puede adjuntar al correo.",
                ["broadcastsent"] = "Correo de difusión enviado.",
                ["broadcastfailed"] = "No se pudo enviar el correo de difusión.",
                ["broadcastmissingtitle"] = "El asunto del correo es obligatorio.",
                ["broadcastmissingmessage"] = "Se requiere mensaje de correo.",
                ["broadcastmissingitem"] = "Se requiere al menos un elemento adjunto al correo.",
                ["broadcastinvalidquantity"] = "Las cantidades de archivos adjuntos de correo deben ser mayores que cero.",
                ["broadcasttoomanyattachments"] = "La difusión de correo puede incluir como máximo {00} elementos adjuntos.",
                ["broadcastnorecipients"] = "No hubo destinatarios para el correo de difusión.",
                ["invalidlisting"] = "Listado no válido.",
                ["listingcreated"] = "Su artículo ha sido listado en el mercado.",
                ["listingunavailable"] = "Este listado ya no está disponible.",
                ["notenoughmoney"] = "No tienes suficiente dinero.",
                ["inventoryfull"] = "Tu inventario está lleno.",
                ["itempurchased"] = "Has comprado el artículo.",
                ["salecompleted"] = "Venta de mercado completada",
                ["yoursolditem"] = "¡Has vendido un artículo a través del mercado!",
                ["expiredlisting"] = "Listado caducado",
                ["yourlistingexpired"] = "Uno de sus listados de mercado ha caducado. El artículo le ha sido devuelto.",
                ["transactionfailed"] = "La transacción de mercado fracasó.",
                ["cannotlist"] = "No puedes listar este artículo.",
                ["cannotremoveitem"] = "No se pudo eliminar el artículo de su inventario.",
            },
        };
    }
}
